[JS] Topic : Template Strings in JavaScript
girlscript/winter-of-contributing pull request #1078
Opened 2021-09-19 19:15 UTC by AbhinandanAdhikari

<hr>

## Description 📜

Created a tutorial for Template Strings in JavaScript.
Fixes #999 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [x] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-19 19:17 UTC, AbhinandanAdhikari commented
@paramsiddharth @dakshsethi @Creatoon @s4-2 Supervisor & Mentors! Please review my pull request.

2021-09-20 01:41 UTC, AbhinandanAdhikari commented
@paramsiddharth Sir, please review this Pull Request and add a label to it.

2021-09-20 02:01 UTC, Creatoon requested changes

2021-09-20 02:39 UTC, AbhinandanAdhikari commented on JavaScript/Topics/10.Template_Strings/README.md
> +Tagged Templates are allows to parse a Template literals with a function
@paramsiddharth @Creatoon @dakshsethi @s4-2 Made the changes, please review it.

2021-09-20 05:38 UTC, paramsiddharth commented
@dakshsethi @s4-2 Please review.

2021-09-20 05:41 UTC, paramsiddharth requested changes

2021-09-20 05:41 UTC, paramsiddharth commented on JavaScript/Topics/10.Template_Strings/README.md
> +console.log("Welcome Everyone \n To GWOC");
The padding doesn't match the literal.
```suggestion
console.log("Welcome Everyone\nTo GWOC");
```

2021-09-20 05:41 UTC, paramsiddharth commented on JavaScript/Topics/10.Template_Strings/README.md
> +```
Please also include a well-known of tagged templates. :)

2021-09-20 08:57 UTC, AbhinandanAdhikari commented
@paramsiddharth @dakshsethi  @Creatoon @s4-2 Made the changes for this Pull Request, please review it.

2021-09-20 10:50 UTC, dakshsethi approved these changes
Looks good to me!! 🔥🔥
@paramsiddharth @Creatoon @s4-2 please review and approve.

2021-09-20 15:18 UTC, AbhinandanAdhikari commented
@Creatoon @paramsiddharth Sir please review.

2021-09-21 04:42 UTC, paramsiddharth approved these changes

2021-09-21 04:43 UTC, paramsiddharth commented
@Creatoon @s4-2 Please review.

2021-09-21 05:33 UTC, merged