Selection sort in c
girlscript/winter-of-contributing pull request #1235
Opened 2021-09-20 11:09 UTC by AditiRout

<hr>

## Description 📜

Added a file to show implementation of Selection sort in c language 
Fixes #893

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-09-21 15:11 UTC, gunjan-g commented
@AditiRout great work, just put this file in correct folder

2021-09-21 15:11 UTC, gunjan-g requested changes
@AditiRout great work.
Just put this file in correct folder

2021-09-21 16:09 UTC, AditiRout commented
Thank u @gunjan-g maam, may I know which folder should I put it in or should I create a separate folder and then put my file?

2021-09-21 16:18 UTC, gunjan-g commented
> Thank u @gunjan-g maam, may I know which folder should I put it in or should I create a separate folder and then put my file?

Create a subfolder in data structures folder named sorting and put your files there

2021-09-21 19:49 UTC, Suvraneel requested changes

2021-09-21 19:49 UTC, Suvraneel commented on C_CPP/readme.md
> +-[Selection Sort in C](https://github.com/AditiRout/winter-of-contributing/blob/turtle/C_CPP/Selection%20sort%20in%20c.md)
Not this readme
Put this as readme inside the sorting folder

2021-09-21 19:51 UTC, Suvraneel requested changes

2021-09-21 19:51 UTC, Suvraneel commented on C_CPP/readme.md
> +-[Selection Sort in C](https://github.com/AditiRout/winter-of-contributing/blob/turtle/C_CPP/Selection%20sort%20in%20c.md)
Not this file, put this as readme inside the sorting folder

2021-09-21 20:14 UTC, Suvraneel requested changes
@AditiRout 
You've done the correct thing now but deleted the original readme...

2021-09-21 20:15 UTC, AditiRout commented
So what should I do now?

2021-09-21 20:16 UTC, AditiRout commented
@Suvraneel sir is there any other way to get the original readme

2021-09-21 20:17 UTC, Suvraneel commented
@AditiRout 
![image](https://user-images.githubusercontent.com/63473496/134241358-8f9d7576-a1fd-4f84-ae82-cdd1d9a6a0ee.png)

2021-09-21 20:22 UTC, AditiRout commented
@Suvraneel sir i tried from the fetch and merge from the branch turtle but the option is not available it shows that its already updated.

2021-09-21 20:24 UTC, Suvraneel commented
@AditiRout 
found your issue
Do 1 thing

Fetch upstream >  Comapre > then fetch from girlscript/C_CPP

2021-09-22 04:57 UTC, AditiRout commented
@Suvraneel sir could you please verify my work?

2021-09-22 13:59 UTC, Suvraneel commented
@AditiRout  Technically correct & perfect
I hope you have now learnt how to resolve git conflicts/merges :octocat:

One last thing, regarding content :
Just add Time & Space Complexity Analysis.. That will make the documentation complete

2021-09-22 18:42 UTC, Suvraneel commented
@AditiRout  Awesome :heart: Keep up!

2021-09-22 18:43 UTC, merged

2021-09-23 03:03 UTC, AditiRout commented
Thank you @Suvraneel sir