Frontend web development html css js
girlscript/winter-of-contributing pull request #1338
Opened 2021-09-20 16:06 UTC by Kalyani02072003

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-20 17:18 UTC, Kalyani02072003 commented
@Saviour1001 sir thank you for removing extra tags

2021-09-21 05:55 UTC, Baalamurgan commented
/assign

2021-09-21 05:56 UTC, Baalamurgan commented
Can I contribute?? @Saviour1001

2021-09-21 05:59 UTC, Kalyani02072003 commented
@Baalamurgan sir i just don't get it, as you can see i have started the work and committed it. can you please not do this as my name is removed from assignees

2021-09-21 05:59 UTC, Kalyani02072003 commented
/assign

2021-09-21 06:00 UTC, Baalamurgan commented
Okay okay. That is why I asked!

2021-09-21 06:03 UTC, Kalyani02072003 commented
@Baalamurgan its completely fine if we contribute it together.. you fine with it?

2021-09-21 06:04 UTC, Baalamurgan commented
Yeah @Kalyani02072003

2021-09-21 06:07 UTC, Kalyani02072003 commented
@Baalamurgan great... i don't know how to assign the issue to two person, if you know kindly do it

2021-09-21 06:07 UTC, Baalamurgan commented
How can I reach you?

2021-09-21 06:07 UTC, Kalyani02072003 commented
kalyanipatra2003@gmail.com my email

2021-09-21 06:08 UTC, Baalamurgan commented
> [kalyanipatra2003@gmail.com](mailto:kalyanipatra2003@gmail.com) my email

Cool

2021-09-21 08:40 UTC, Baalamurgan commented
@Saviour1001 Can you assign myself to this issue. I want to work with @Kalyani02072003

2021-09-21 13:45 UTC, Saviour1001 commented
@Baalamurgan @Kalyani02072003 you can ask regarding this issue to your domain's supervisor. I just got into this issue as I saw it had too many unnecessary labels on it.

2021-09-21 14:29 UTC, Baalamurgan commented
/assign

2021-09-21 14:56 UTC, Kalyani02072003 commented
/assign

2021-09-22 09:18 UTC, praveenscience commented
@Baalamurgan What are you trying to do? 😅  This is a PR to be reviewed! 😅
Since you got it assigned, can you please review it right now and tell me what's your report? 😁
Will definitely consider your reviews now. It's been assigned to you, @Baalamurgan to review this PR.

@Kalyani02072003 You cannot review your own work. Let the other person review (my work given to Bala). 😅

2021-09-22 09:23 UTC, praveenscience commented
@Baalamurgan Need your review on this within an hour, or I am removing you from the reviewers. 😊

2021-09-22 09:37 UTC, Baalamurgan commented
Sure @praveenscience.

2021-09-22 09:38 UTC, Kalyani02072003 commented
@praveenscience so sir my work is done right? now its up to you and @Baalamurgan to review my work and do something with my pull request right?

2021-09-22 09:44 UTC, praveenscience commented
@Kalyani02072003 Yes, perfectly right! 🎉

2021-09-22 09:56 UTC, Baalamurgan requested changes
You have done only 1 topic called "Lists" in HTML.
There are way many topics in Frontend web development with html, cs, js.
Try to combine all the 3 languages and explain it.

2021-09-22 09:59 UTC, Kalyani02072003 commented
> You have done only 1 topic called "Lists" in HTML.
> There are way many topics in Frontend web development with html, cs, js.
> Can you try to combine all the 3 languages and explain it.

what are those topics sir, as the heading was first mentioned as HTML lists only. Do let me know, I will write it before night

2021-09-22 13:53 UTC, praveenscience commented
@Baalamurgan This is fine for this PR... No need more. I'll review the PR in few mins.

2021-09-22 13:54 UTC, Baalamurgan commented
Okay @praveenscience

2021-09-24 05:04 UTC, praveenscience requested changes
Can you please address the changes? Thanks.

2021-09-24 05:04 UTC, praveenscience commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +
Make sure in Markdown, you have not more than one empty line.

2021-09-24 05:04 UTC, praveenscience commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +# HTML LISTS
Use sentence case for Lists.

2021-09-24 05:04 UTC, praveenscience commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +
No need of space.

2021-09-24 05:04 UTC, praveenscience commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +how they are implemented.
Make it a single line.

2021-09-24 05:04 UTC, praveenscience commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +
Remove unnecessary spaces.

2021-09-24 05:04 UTC, praveenscience commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +### Ordered List
Why jumping to h3 instead of h2? Make it h2.

2021-09-24 05:04 UTC, praveenscience commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +
Remove all Unnecessary spaces.

2021-09-24 05:04 UTC, praveenscience commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +### HOW TO CREATE LISTS IN HTML ?
Grammar:

1. Use Sentence Case
2. No space before `?`

2021-09-24 05:04 UTC, praveenscience commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +
No need of extra lines.

2021-09-24 05:04 UTC, praveenscience commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +
Remove extra lines.

2021-09-24 05:04 UTC, praveenscience commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +</HTML> `
Use code fence with syntax. Use lowercase tags like `<html>` and `<body>` instead of `<HTML>` and `<BODY>`.

2021-09-24 05:04 UTC, praveenscience commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +`-` club incharge
Why is this complete section messed up?
Why is the heading and contents are in the same line?
Why is everything in ALL CAPS?

2021-09-24 05:09 UTC, Kalyani02072003 commented
yes sir will make changes

2021-09-24 17:31 UTC, 2024-SANDHYA requested changes
Instead of writing like this, provide the output image

![image](https://user-images.githubusercontent.com/75671152/134716828-6bee5cfc-7c9e-4e07-8253-b3c8fc10eac0.png)

2021-09-24 17:34 UTC, Kalyani02072003 commented
> Instead of writing like this, provide the output image
> 
> ![image](https://user-images.githubusercontent.com/75671152/134716828-6bee5cfc-7c9e-4e07-8253-b3c8fc10eac0.png)

so I should include a screenshot in it right?

2021-09-24 17:47 UTC, 2024-SANDHYA commented
> 
> 
> > Instead of writing like this, provide the output image
> > ![image](https://user-images.githubusercontent.com/75671152/134716828-6bee5cfc-7c9e-4e07-8253-b3c8fc10eac0.png)
> 
> so I should include a screenshot in it right?

What does the output mean? Ofc yes !!

2021-09-24 18:28 UTC, Kalyani02072003 commented
@2024-SANDHYA maam added the output image kindly check

2021-09-25 14:26 UTC, iamsunil25 commented
@praveenscience can you assign me this issue?

2021-09-25 15:49 UTC, 2024-SANDHYA requested changes
🤦🏻  Why you've added this? YOU NEED TO PROVIDE ONLY OUTPUT

![Screenshot 2021-09-25 at 21-17-48 Frontend web development html css js by Kalyani02072003 · Pull Request #1338 · girlscript](https://user-images.githubusercontent.com/75671152/134777532-cc484739-a72e-44ab-8251-f49549344d14.png)

2021-09-25 17:19 UTC, Kalyani02072003 commented
> 🤦🏻 Why you've added this? YOU NEED TO PROVIDE ONLY OUTPUT
> 
> ![Screenshot 2021-09-25 at 21-17-48 Frontend web development html css js by Kalyani02072003 · Pull Request #1338 · girlscript](https://user-images.githubusercontent.com/75671152/134777532-cc484739-a72e-44ab-8251-f49549344d14.png)

how do I do that? i am sorry for asking that, but I thought I need to add the output link in the md file.

2021-09-27 06:57 UTC, Kalyani02072003 commented
@2024-SANDHYA maam please check if it is correct or not now?

2021-09-27 07:47 UTC, kashishahuja2002 reviewed
Yes now it is correct, only ss is there, code is not there.

2021-09-27 07:56 UTC, kashishahuja2002 requested changes
Add proper indentation in code. Also, add an output screenshot for dl. The output ss for ol and ul is not correct. Check it.

2021-09-27 07:56 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +Here the elements are evenly arranged in a definite fashion and are not random.
Add an empty line before this line

2021-09-27 07:56 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +Here these numbers are not organized. first is four, second is nine and so on. There is no definite sequence is followed here.
Add an empty line before this line

2021-09-27 07:56 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +
Remove this line

2021-09-27 17:04 UTC, kashishahuja2002 requested changes
Output is still not correct.

2021-09-27 17:04 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +4.
Remove no. 4, just add empty line.

2021-09-27 17:04 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +-
Remove ( - ), just add empty line.

2021-09-27 17:26 UTC, Kalyani02072003 commented
@kashishahuja2002 maam please check now

2021-09-28 03:34 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +` <html>
Remove a ` from here.

2021-09-28 03:34 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +</html> `
Remove one ` from here also

2021-09-28 03:35 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML-LISTS#842.md
> +![Screenshot (90)](https://user-images.githubusercontent.com/71889838/134722755-93a6a1ef-aa8b-4636-bf6c-750d8a635186.png)
SS isn't right, also include dl in ss.

2021-09-28 06:15 UTC, kashishahuja2002 approved these changes
Good to go. @praveenscience

2021-10-02 18:09 UTC, praveenscience approved these changes
I just made it look good. 👍  Please check this out. These are the changes I made:

- Grammar fix.
- Paragraphs and Lists should have at least a line space.
- Headings & Paragraphs should have at least a line space.
- Image alt should be given in a better way.
- Use Indian English not American English.
- Paragraphs should have a line space.
- Spaces after and before inline code.
- Remove "are nothing but". Why there's even a nothing and a but?
- No need of All Caps in HTMLs.
- Spelling mistake: Related ≠ Realted.
- Confusion in "-" vs. ":".
- Headings should be in Sentence Case.
- Errors in Code.
  - No code fence for bigger codes.
  - You cannot have direct text descendents to `<UL>` or `<OL>` tags. It has to be only `<LI>` tags.
  - The `<HEAD>` tag cannot contain arbitrary text in them.
  - Code not properly indented.
  - HTML DocType Definition Missing.
- Spelling mistake: veiwed ≠ viewed.
- Shorter headings and longer paragraphs.

/cc: @kashishahuja2002 @2024-SANDHYA @Baalamurgan

2021-10-02 19:23 UTC, praveenscience approved these changes

2021-10-03 07:47 UTC, 2024-SANDHYA approved these changes

2021-10-03 07:48 UTC, merged