DSA_1.1.3.4.Arrays_Range_Queries_410
girlscript/winter-of-contributing pull request #1354
Opened 2021-09-20 17:17 UTC by Harsh-Chaudhary7

<hr>

## Description 📜

I have documented the explanation of Merge sort tree and its implmentation too. please review it.@nimisha-yadav 
Fixes #410

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

[DSA_1.1.3.4_Arrays_ Range_Queries_410.md](https://github.com/girlscript/winter-of-contributing/files/7197495/DSA_1.1.3.4_Arrays_.Range_Queries_410.md)

<hr>

2021-09-20 18:03 UTC, harshsri28 requested changes
update the problem statement something like explanation of merge sort tree and it's implementation , rest is looking fine.

2021-09-20 18:03 UTC, harshsri28 commented on DSA/1.1 Arrays/3. Range Queries/DSA_1.1.3.4_Arrays_ Range_Queries_#410.md
> +Given an array of N elements and you have to answer Q queries of the form L R K , To Count the numbers
update the problem statement something like explanation of merge sort tree and it's implementation , rest is looking fine.

2021-09-21 01:39 UTC, Harsh-Chaudhary7 commented
> update the problem statement something like explanation of merge sort tree and it's implementation , rest is looking fine.
Updation done please review it. @harshsri28

2021-09-21 13:46 UTC, harshsri28 approved these changes
LGTM

2021-09-21 15:33 UTC, Harsh-Chaudhary7 commented
Please review it @nimisha-yadav.

2021-09-21 20:05 UTC, nimisha-yadav requested changes
LGTM. Just rename your file 1.1.3.4_Merge_Sort_Tree.md

2021-09-22 02:31 UTC, Harsh-Chaudhary7 commented
Renaming done @nimisha-yadav

2021-09-22 06:58 UTC, nimisha-yadav approved these changes
Congrats on getting your PR merged!

2021-09-22 06:58 UTC, merged