Friend function branch
girlscript/winter-of-contributing pull request #1487
Opened 2021-09-21 04:49 UTC by shreya0204

<hr>

## Description 📜

Added introduction to friend function along with examples and explanation in documentation format. 
Fixes # <883> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

2021-09-21 05:13 UTC, rohan-kulkarni-25 requested changes

2021-09-21 05:13 UTC, rohan-kulkarni-25 commented on Frontend_Web_Development_React_Angular_Vue/React/Week 1/All_About_npm.md
> +After this you will get a number of entries to fill and you can fill them according to your preference. All this will lead to the creation of a file with name `package` in your main folder. Once you'
- Please replace `package` by `package.json`

2021-09-21 05:13 UTC, rohan-kulkarni-25 commented on Frontend_Web_Development_React_Angular_Vue/React/Week 1/All_About_npm.md
> +[Here](https://www.npmjs.com/) you can search your desired packages.
- You can replace this link by `On [npm](https://www.npmjs.com/) you can search your desired packages.`

2021-09-21 05:32 UTC, shreya0204 commented
@Saviour1001 Sorry for tagging but please review this PR. I have followed all the step-by-step procedures you have said in the meeting but I don't know why I am seeing other's commits and other's files changed in mine. Can you please see this and tell me what I made wrong 🙁

2021-09-21 05:52 UTC, Suvraneel commented
@shreya dont worry about the changed files by others, we'll see only the last 2 made by you

2021-09-21 06:10 UTC, shreya0204 commented
> @shreya0204 dont worry about the changed files by others, we'll see only the last 2 made by you

Thanks for the confirmation, I was worried thinking about what I made wrong :)

2021-09-21 20:42 UTC, Suvraneel commented
@shreya0204 Since that time much has changed in the repo

Do this in your PR branch:  Fetch > Compare > pull from girlscript/C_CPP to your main branch

![image](https://user-images.githubusercontent.com/63473496/134244505-434aa0dc-d2f1-437d-8934-6ea94125d694.png)

2021-09-22 03:53 UTC, shreya0204 commented
> @shreya0204 Acually your worries were correct...
> 
> Do this in your PR branch: Fetch upstream > Compare > pull from girlscript/C_CPP to your friend-function branch
> 
> ![image](https://user-images.githubusercontent.com/63473496/134244505-434aa0dc-d2f1-437d-8934-6ea94125d694.png)

Yes, I have fetched and merged in my branch do I have to make a new PR?

2021-09-22 04:38 UTC, Suvraneel commented
@shreya0204 Not from girlscript:main 🤦🏻 
From girlscript/C_CPP branch

Do this in your PR branch: Fetch upstream > Compare > pull from girlscript/C_CPP to your friend-function branch

2021-09-22 04:46 UTC, shreya0204 commented
@Suvraneel Sorry 😅Yeah It's done now, I have merged from C_CPP branch to friend-function branch

2021-09-23 09:51 UTC, Suvraneel requested changes
Content is great, passed plagiarism checks too...

one last thing, before merge -
1. Move this file to C_CPP/Virtual Functions, Friend Functions & Friend Classes/
2. Add a line for this in C_CPP/Virtual Functions, Friend Functions & Friend Classes/readme.md

2021-09-23 12:33 UTC, shreya0204 commented
@Suvraneel Thanks. It's done 👍

2021-09-24 06:40 UTC, Suvraneel commented
@shreya0204 GG ❤️ :octocat: 💯

2021-09-24 06:40 UTC, merged

2021-09-24 07:53 UTC, shreya0204 commented
@Suvraneel Yay yay! Thank you so much!