[JS] Topic: Promises in Javascript
girlscript/winter-of-contributing pull request #1522
Opened 2021-09-21 07:36 UTC by aniketpathak028

## Description 📜

Created a tutorial for Promises in Javascript and elaborated upon the following points:

- What is a Promise in Javascript?
- Why do we need Promises?
- How to create a Promise? (Syntax)
- Chained Promises
- Methods in Promises
- Examples

Fixes  #1241

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-21 12:00 UTC, aniketpathak028 commented
@paramsiddharth sorry for bothering you multiple times today 😅, 
I have completed this Promises PR please suggest changes if required!
Thanks 😇

2021-09-21 14:15 UTC, aniketpathak028 commented
@creatoon @dakshsethi pls review this PR

2021-09-22 05:34 UTC, paramsiddharth commented
@Creatoon @dakshsethi @s4-2 Please review.

2021-09-22 05:34 UTC, paramsiddharth approved these changes

2021-09-22 06:01 UTC, s4-2 approved these changes
Looks good to me, well done:)

2021-09-22 18:15 UTC, dakshsethi requested changes

2021-09-22 18:15 UTC, dakshsethi commented on JavaScript/Topics/12.Promises/README.md
> +---
Make it `# Promises in JavaScript`

2021-09-22 18:15 UTC, dakshsethi commented on JavaScript/Topics/12.Promises/README.md
> +
Show code snippets of all  `Methods in Promises`

2021-09-23 01:41 UTC, Creatoon requested changes

2021-09-23 01:41 UTC, Creatoon commented on JavaScript/Topics/12.Promises/README.md
> +// "Producing Code" (May take some time)
```suggestion
// "Processing Code" (May take some time)
```

2021-09-23 01:41 UTC, Creatoon commented on JavaScript/Topics/12.Promises/README.md
> +  function(value) { /* code if successful */ },
```suggestion
  function(value), { /* code if successful */ },
```

2021-09-23 01:41 UTC, Creatoon commented on JavaScript/Topics/12.Promises/README.md
> +	then(function () {
```suggestion
	then(function (result) {
```

2021-09-23 01:41 UTC, Creatoon commented on JavaScript/Topics/12.Promises/README.md
> +	catch(function () {
```suggestion
	catch(function (error) {
```

2021-09-23 03:27 UTC, aniketpathak028 commented
@Creatoon @dakshsethi made all those changes that were suggested! Please approve. 🙂
Thanks

2021-09-23 03:30 UTC, Creatoon approved these changes

2021-09-23 05:02 UTC, merged