Topic: Web Browser
girlscript/winter-of-contributing pull request #1523
Opened 2021-09-21 07:38 UTC by daminimehra

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev React/Angular/Vue
- [ ] Golang
- [ ] Interview Prep
- [ ] Java_Domain
- [ ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python_Domain
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-21 08:19 UTC, Creatoon commented
@daminimehra see browser is a runtime and a runtime consits many things, like js engine, call stack and heap, event loop, callback queue and some browser api's like fetch, console(you covered), so also add these things also add the image of browser runtime.

Talk about different browsers and their engines like for chrome - V8 engine and firefox - spidermonkey, just list them for knowledge

And define whole chrome browser runtime keeping all the stuff in mind in a correct order, leave those which you covered

2021-09-21 08:49 UTC, dakshsethi requested changes

2021-09-21 08:49 UTC, dakshsethi commented on JavaScript/Topics/3.Web_Browser/README.md
> +
Crop the image as the rest of the part is not required
Just show the tabs and the thing it is printing
Too much unnecessary white blank space of webpage is not needed

2021-09-21 08:49 UTC, dakshsethi commented on JavaScript/Topics/3.Web_Browser/README.md
> +
Explain why DOM does not get affected with a paragraph.
Explain why writing the `<script>` tag at the end of `<body>` is a good practice.

2021-09-21 08:49 UTC, dakshsethi commented on JavaScript/Topics/3.Web_Browser/README.md
> +
Same here, crop this image too.

2021-09-21 12:19 UTC, daminimehra commented
Sir Pls close this PR. Actually, I have deleted that fork repo and now I am not able to find the location to my branch in file finder and not able to make changes.
I will make new as soon as possible with all the suggested changes by mentors.
@paramsiddharth @dakshsethi

2021-09-21 12:19 UTC, closed without merging

2021-09-22 05:33 UTC, paramsiddharth commented
@daminimehra If you find any problems, just let us know. Meanwhile I'll check out your response in Discord.