first commit
girlscript/winter-of-contributing pull request #1540
Opened 2021-09-21 08:12 UTC by Raghavshalu

<hr>

## Description 📜
Differences between const, var and let with their syntax and examples..........it includes why const and let is more preferable in that time.
JS: Documentation for difference between const, var and let #395.

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm a GWOC'21 contributor
 
<hr>

2021-09-21 08:52 UTC, Creatoon requested changes

2021-09-21 08:52 UTC, Creatoon commented on JavaScript/Topics/5.Syntax/Variable_Initialization/README.md
> +# Difference between const, var and let
```suggestion
# Difference between var, let & const
```
Write in correct order of arrival

2021-09-21 08:52 UTC, Creatoon commented on JavaScript/Topics/5.Syntax/Variable_Initialization/README.md
> +There are 3 ways to declare a JavaScript variable:
```suggestion
There are 3 ways to declare a JavaScript variables:
```

2021-09-21 08:52 UTC, Creatoon commented on JavaScript/Topics/5.Syntax/Variable_Initialization/README.md
> +    var carName;
```suggestion
var carName;
```
Why space

2021-09-21 08:52 UTC, Creatoon commented on JavaScript/Topics/5.Syntax/Variable_Initialization/README.md
> +    document.getElementById("demo").innerHTML = carName;
```suggestion
    document.getElementById("demo").textContent = carName;
```

carName is just a string not an html element

2021-09-21 08:57 UTC, Raghavshalu commented
@Creatoon Now it is ohk?

2021-09-22 00:28 UTC, Creatoon requested changes

2021-09-22 00:28 UTC, Creatoon commented on JavaScript/Topics/5.Syntax/Variable_Initialization/README.md
> +In the example below, we create a variable called carName and assign the value "Volvo" to it.
```suggestion
In the example above, we create a variable called carName and assign the value "Volvo" to it.
```

I think you are talking about above example

2021-09-22 00:28 UTC, Creatoon commented on JavaScript/Topics/5.Syntax/Variable_Initialization/README.md
> +    var carName = "Volvo";
```suggestion
      var carName = "Volvo";
```

2021-09-22 00:28 UTC, Creatoon commented on JavaScript/Topics/5.Syntax/Variable_Initialization/README.md
> +    document.getElementById("demo").textContent = carName;
```suggestion
      document.getElementById("demo").textContent = carName;
```

2021-09-22 00:28 UTC, Creatoon commented on JavaScript/Topics/5.Syntax/Variable_Initialization/README.md
> +    document.getElementById("demo").textContent = carName;
Indent them properly inside script tag

2021-09-22 00:28 UTC, Creatoon commented
@Raghavshalu  Just make these changes, i will approve

2021-09-22 03:26 UTC, Raghavshalu commented
@Creatoon i have made those changes please review and approve it.

2021-09-22 03:27 UTC, Creatoon approved these changes

2021-09-22 05:29 UTC, paramsiddharth commented
@dakshsethi @s4-2 Please review.

2021-09-22 05:30 UTC, paramsiddharth approved these changes

2021-09-22 05:47 UTC, s4-2 commented
@Raghavshalu  Please write issue number correctly as there should be a gap **Fixes #395**

2021-09-22 05:49 UTC, s4-2 commented
@Raghavshalu Add your name as a contributor at the end of the file.

2021-09-22 05:57 UTC, Raghavshalu commented
@s4-2 Done mam.😊

2021-09-22 06:18 UTC, s4-2 approved these changes
@Raghavshalu  Well done, looks to me.

2021-09-22 06:55 UTC, merged