Data Science with Python: Introduction to Keras #416
girlscript/winter-of-contributing pull request #1719
Opened 2021-09-21 17:15 UTC by freny24

<hr>

## Description 📜

Explained basics of Keras using code snippets [#416 ]

<hr>

## Type of change

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

2021-09-22 07:51 UTC, prathimacode-hub commented
Your README and .ipynb file both lack details. Be elaborative. And follow the project structure mentioned. Make sure to note files needed for a successful PR. This is not sufficient. @freny24

2021-09-24 09:21 UTC, Kareem-negm reviewed
your work is good for now just keep doing and good luck

2021-09-24 09:21 UTC, Kareem-negm commented on Datascience_With_Python/Deep Learning/DSWP/Intoduction_to_Keras.ipynb
> +    "! pip install tensorflow"
if you hide this cell output it's will be nice

2021-09-24 09:21 UTC, Kareem-negm commented on Datascience_With_Python/Deep Learning/DSWP/Intoduction_to_Keras.ipynb
> +    "print(x)\n",
try to add this "print " as a DF output to be more readable

2021-09-24 09:23 UTC, Kareem-negm commented on Datascience_With_Python/DS Datasets/README.md
> +     I used Heart rate prediction CSV file to predict heart rate among various patients using Tensorflow and Keras. I downloaded the data set from Kaggle
it's shown as a scroll bar, please check it again

2021-09-29 06:23 UTC, prathimacode-hub requested changes
Changes to be done 👍 

The project files of .ipynb and main README.md file should be in "/Datascience_with_Python/Deep Learning/Tutorials/Introduction to Keras/" repo
The file name of .ipynb file should be in snake case and README.md file
And datasets should be added in "/Datascience_with_Python/DS Datasets/Introduction to Keras/" repo

Kindly work on the project structure changes. @freny24

2021-09-29 08:02 UTC, closed without merging