Frontend Web Development CSS ANIMATION
girlscript/winter-of-contributing pull request #1739
Opened 2021-09-21 18:16 UTC by priyanka001tech

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #1056 
<h2>Add documentation about CSS Animation</h2> 
In the Road-map of GWOC I saw a topic named CSS animation so I have made a documentation for that which includes different properties of animation and live examples also. 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-09-21 18:28 UTC, priyanka001tech commented
Hello @ghulamyazdani @code-reaper08 , Pls check this once and let me know if I need to do some fixes or its fine

2021-09-21 19:39 UTC, code-reaper08 requested changes
Kindly look into the directory structure. You are pushing these into `Web_Development/Javascript/CSS_ANIMATION/README.md`

@ghulamyazdani have a look here.

2021-09-21 19:39 UTC, code-reaper08 commented on Web_Development/Javascript/CSS_ANIMATION/README.md
> +#**CSS ANIMATION :--**
Getting `#` here in live file too. Try correcting this.

2021-09-22 12:46 UTC, priyanka001tech commented
@code-reaper08  I have solved the issue please check CSS Animation added #1969

2021-09-29 04:31 UTC, closed without merging