[JS] Topic: Tutorial on Object Oriented Javascript(using functions)
girlscript/winter-of-contributing pull request #1772
Opened 2021-09-21 20:15 UTC by arp99

<hr>

## Description 📜
Wrote a tutorial on Object Oriented Javascript(using functions)

Fixes #460 
References:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Inheritance_and_the_prototype_chain
https://www.youtube.com/watch?v=OSjTmET11OQ&ab_channel=codeWithSimran
https://www.freecodecamp.org/news/how-javascript-implements-oop/
https://medium.com/@ryansolid/oop-with-functions-in-javascript-a3ec30e4750a
https://www.simplilearn.com/tutorials/javascript-tutorial/oop-in-javascript 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

2021-09-22 05:39 UTC, paramsiddharth commented
@Creatoon @dakshsethi @s4-2 Please review.

2021-09-22 05:40 UTC, paramsiddharth approved these changes

2021-09-22 06:11 UTC, s4-2 commented
@arp99 Your doc looks good to me. I'll suggest you to change the format of link in **Description --> Reference** Write as **1 [freecodecamp](https://www.freecodecamp.org/news/how-javascript-implements-oop/)** and so on. Hope you got it:)

2021-09-22 17:49 UTC, arp99 commented
> A very documented Markdown file!! Great job @arp99 🔥🔥🔥
> Add `__Contributor:__ [Arpan Mondal](https://www.github.com/arp99)` at the end of every MD file.

I have added a commit, please do check

2021-09-22 18:02 UTC, dakshsethi requested changes

2021-09-22 18:02 UTC, dakshsethi commented on JavaScript/Topics/11.OOP_Javascript_Using_Functions/Inheritence/README.md
> +> <cite>[Arpan Mondal](https://github.com/arp99)</cite>
Update this also as i have mentioned.

2021-09-22 18:57 UTC, arp99 commented on JavaScript/Topics/11.OOP_Javascript_Using_Functions/Inheritence/README.md
> +> <cite>[Arpan Mondal](https://github.com/arp99)</cite>
Done

2021-09-22 20:12 UTC, dakshsethi approved these changes
Looks good to me!! 🔥🔥🔥

2021-09-23 01:52 UTC, Creatoon approved these changes

2021-09-23 04:15 UTC, paramsiddharth approved these changes

2021-09-23 04:15 UTC, merged