[JS] Topic: History of JavaScript
girlscript/winter-of-contributing pull request #190
Opened 2021-09-16 08:29 UTC by sushovanb02

<hr>

## Description 📜
Created a document on the history of JavaScript. 
Fixes #70 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [x] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-16 14:50 UTC, sushovanb02 commented
@paramsiddharth sir please review my work

2021-09-16 15:54 UTC, sushovanb02 commented
@paramsiddharth sir just asking for my future PRs, is use of images for explaining topics appreciated like I have done in this PR or textual content is better

2021-09-16 16:19 UTC, paramsiddharth commented
> @paramsiddharth sir just asking for my future PRs, is use of images for explaining topics appreciated like I have done in this PR or textual content is better

I think you have done an excellent job, and this is exactly the kind of contribution I would expect to have. Well done! Keep doing
it with graphics, I encourage that.

2021-09-16 16:26 UTC, sushovanb02 commented
Thank u sir!

2021-09-16 17:42 UTC, dakshsethi commented
I think the timeline of JavaScript will look good if displayed in a tabular format as it will be easy to read also.

2021-09-17 07:13 UTC, sushovanb02 commented
@dakshsethi @paramsiddharth sir, as requested I have changed the timeline into tabular form. Please have a look and confirm if I am good to go

2021-09-17 13:20 UTC, paramsiddharth requested changes
The rest looks good to me!

2021-09-17 13:20 UTC, paramsiddharth commented on Web_Development/Javascript/Topics/2.History/History_Of_JavaScript.md
> +
Please rename this file to `README.md` like last time.

2021-09-17 13:20 UTC, paramsiddharth commented on Web_Development/Javascript/Topics/2.History/History_Of_JavaScript.md
> +# TIMELINE OF JAVASCRIPT
Use "Title Case" instead of "UPPER CASE" for the headers! That makes it look better.

2021-09-17 13:46 UTC, sushovanb02 commented
@paramsiddharth sir changed as u said, please check

2021-09-17 13:48 UTC, paramsiddharth approved these changes

2021-09-17 13:58 UTC, paramsiddharth commented
@Creatoon @dakshsethi Could you please review the PR, and request any changes if needed?

2021-09-17 14:09 UTC, Creatoon commented
LGTM!

2021-09-17 14:09 UTC, Creatoon approved these changes

2021-09-18 03:24 UTC, dakshsethi approved these changes
Yes it looks good to me.

2021-09-18 09:27 UTC, sushovanb02 commented
@paramsiddharth sir, is this ready to be merged?

2021-09-18 10:01 UTC, paramsiddharth commented
> @paramsiddharth sir, is this ready to be merged?

Yes!

2021-09-18 10:01 UTC, merged

2021-11-01 18:26 UTC, iam-sakshi commented
can I work on this issue?

2021-11-04 11:54 UTC, paramsiddharth commented
@iam-sakshi Yes, please. :) Check out the issue: #70. Note that a documentation has already been merged. You may contribute an extension or an audio/video contribution. Please comment on the issue if you wish to be assigned.