Stock Span Documentation
girlscript/winter-of-contributing pull request #1904
Opened 2021-09-22 08:37 UTC by sinu-02

<hr>

## Description 📜

I have provided a documentation of stock span problem using stack where the problem statement has been explained ,the algorithm followed to solve the problem and the code has been provided in cpp .
Fixes #1059  

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/#CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-09-22 08:42 UTC, sinu-02 commented
@Suvraneel  I have generated new PR (this one #1904  for #1059(Stock Span Problem) ).So that I can merge from C_CPP Directory than main stream.Please review this one.

2021-09-23 07:47 UTC, Suvraneel commented
@kashishahuja2002
Ye wala zara review kar dena

2021-09-23 08:28 UTC, kashishahuja2002 reviewed
As this problem statement is from leetcode, mention the reference website of the problem statement.

2021-09-23 08:33 UTC, sinu-02 commented
@kashishahuja2002 ok! can u pls tell me how should I edit my documentation?

2021-09-23 10:03 UTC, Suvraneel commented
@sinu-02 same branch mein karne seh, it'll reflect in the PR

2021-09-23 17:53 UTC, sinu-02 commented
@Suvraneel  @kashishahuja2002  I have made the required changes please look on to the Documentation #1904

2021-09-24 03:41 UTC, kashishahuja2002 commented
Great. Looks good to me; ready for merge. @Suvraneel

2021-09-24 13:08 UTC, Suvraneel commented
@sinu-02  Add relative link to  Data Structures/readme

2021-09-24 13:25 UTC, sinu-02 commented
@Suvraneel  How should I do that, do I have to create a readme in my forked repository ??

2021-09-25 10:15 UTC, Suvraneel requested changes
@sinu-02  
1.
This really doesn't belong in this place...
We've made changes to the directory structure... Kindly place this somewhere suitable :
either under Data Structure/Stack or under Competitive Prog folder

Review : @kashishahuja2002

2021-09-25 10:17 UTC, Suvraneel requested changes
@sinu-02  
1.
This really doesn't belong in this place...
We've made changes to the directory structure... Kindly place this somewhere suitable :
either under Data Structure/Stack or under Competitive Prog folder

Review : @kashishahuja2002

2021-09-25 10:17 UTC, Suvraneel commented on C_CPP/Data Structures/Stock Span Problem/Description.md
> +10.This the algorithm I foolowed for this problem.
```suggestion
10.This the algorithm I followed for this problem.
```

2021-09-25 10:17 UTC, Suvraneel commented on C_CPP/Data Structures/Stock Span Problem/Description.md
> +}
Add new line at EOF

2021-09-25 10:17 UTC, Suvraneel commented on C_CPP/Data Structures/Stock Span Problem/Description.md
> +#  CODE
Add Time Complexity analysis

2021-09-25 10:17 UTC, Suvraneel commented on C_CPP/Data Structures/Stock Span Problem/Stock Span Problem.cpp
> +
Add sample I/O

2021-09-25 16:07 UTC, kashishahuja2002 reviewed
Yaa, this is more of a CP content.

2021-09-26 06:39 UTC, sinu-02 commented
@Suvraneel  I have made all the required changes please look on to it once.

2021-09-26 17:38 UTC, Suvraneel approved these changes

2021-09-26 17:39 UTC, Suvraneel commented
@sinu-02  Observe the changes & do it from next time

Content-wise, good work ❤️

2021-09-26 17:39 UTC, merged