CSS_Buttons(Animated)-Frontend web development html css js
girlscript/winter-of-contributing pull request #1992
Opened 2021-09-22 13:52 UTC by VAISHNAVI0715

<hr>

## Description 📜
 For issue number#1507
1. Review of creating buttons with HTML
2.  Tutorial of CSS Properties to style buttons and most used button styles.
3. Code tutorial for animated buttons

Fixes # 1507 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-23 03:18 UTC, krupesh87 commented
/assign

2021-09-23 07:08 UTC, VAISHNAVI0715 commented
This was my issue ,my pull request. How did you assigned your name as assigneee? This is wrong

2021-09-23 08:41 UTC, praveenscience commented
@krupesh87 When can I get a report of your review on this PR? Can it be done in an hour? Else I am unassigning you and reviewing it myself.

2021-09-23 09:29 UTC, krupesh87 commented
@praveenscience how can it  be done in an hour? people are creating issues by themselves while issues should have been created by you. we are not getting issues at all. kindly look into it.

2021-09-23 13:15 UTC, praveenscience commented
@krupesh87 I thought you wanted to "review" this **"pull request"**, which took me just 10 mins! Are you kidding? 😅

2021-09-23 13:21 UTC, praveenscience requested changes
Please check out your review comments. Thanks for contributing. 😊

2021-09-23 13:21 UTC, praveenscience commented on Web_Development/FrontEnd/CSS_Buttons/readme.md
> +
Have only one line space.

2021-09-23 13:21 UTC, praveenscience commented on Web_Development/FrontEnd/CSS_Buttons/readme.md
> +
Space on top and make it link like this: [CSS Button Generator](https://css3buttongenerator.com/)

2021-09-23 14:18 UTC, 2024-SANDHYA requested changes
So very congested here!! 

1. Let the content breathe (Give proper space, heading , sub-heading, and so on).
2. Write code properly the way it's written in md , not  the simple text.

2021-09-23 17:24 UTC, praveenscience requested changes
Small changes. But very important ones.

2021-09-23 17:24 UTC, praveenscience commented on Web_Development/FrontEnd/CSS_Buttons/readme.md
> +  <h2>CSS BUTTONS</h2>
Use markdown headings.
```suggestion
## CSS BUTTONS
```

2021-09-23 17:24 UTC, praveenscience commented on Web_Development/FrontEnd/CSS_Buttons/readme.md
> +  The `<button>` HTML element represents a clickable button, used to submit forms or anywhere in a document for accessible, standard button functionality. By default, HTML buttons  are presented in a
Don't use spaces in front, this will be considered as a code.

2021-09-23 17:24 UTC, praveenscience commented on Web_Development/FrontEnd/CSS_Buttons/readme.md
> +
Don't use spaces in front, this will be considered as a code.

2021-09-23 17:24 UTC, praveenscience commented on Web_Development/FrontEnd/CSS_Buttons/readme.md
> +   The `<button>` element is used to create an HTML button. Any text appearing between the opening and closing tags will appear as text on the button. No action takes place by   default when a button
Don't use spaces in front, this will be considered as a code.

2021-09-23 17:24 UTC, praveenscience commented on Web_Development/FrontEnd/CSS_Buttons/readme.md
> +  <br>Syntax:
Erm... Messed up.

2021-09-23 17:24 UTC, praveenscience commented on Web_Development/FrontEnd/CSS_Buttons/readme.md
> +
Get rid of HTML tags. See this for a good example of Markdown: [The Ultimate Guide to Writing & Publishing with Markdown](https://ghost.org/changelog/markdown/)

2021-09-23 18:19 UTC, VAISHNAVI0715 commented on Web_Development/FrontEnd/CSS_Buttons/readme.md
> +  <br>Syntax:
What spaces?

2021-09-24 18:58 UTC, VAISHNAVI0715 commented
> So very congested here!!
> 
> 1. Let the content breathe (Give proper space, heading , sub-heading, and so on).
> 2. Write code properly the way it's written in md , not  the simple text.

2021-09-25 09:32 UTC, 2024-SANDHYA requested changes
Looks Okayish !! Add reference links too

2021-09-25 18:06 UTC, praveenscience requested changes
Please do the changes on each of the code block.
Please indent all the code, use prettier or something to help you with this.

2021-09-25 18:06 UTC, praveenscience commented on Web_Development/FrontEnd/CSS_Buttons/readme.md
> +   ```
Need CSS.

2021-09-25 18:06 UTC, praveenscience commented on Web_Development/FrontEnd/CSS_Buttons/readme.md
> +
No need of spaces.

2021-10-05 10:58 UTC, kashishahuja2002 requested changes
Add proper indentation in all the code snippets.

2021-10-05 10:58 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/CSS_Buttons/readme.md
> +    ```
Backticks are visible in code snippet also. Check that.

2021-10-05 10:58 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/CSS_Buttons/readme.md
> +    ```
Backticks are visible in code snippet also. Check that.

2021-11-12 10:14 UTC, kashishahuja2002 commented
> @VAISHNAVI0715 No updates or changes done.

No updates for a long time. 
Close this PR, @praveenscience

2021-11-12 10:15 UTC, closed without merging