Datascience with python: Getting started with Linear Algebra
girlscript/winter-of-contributing pull request #2010
Opened 2021-09-22 14:44 UTC by Sera001

<hr>

## Description 📜

A short introduction to get started with Linear Algebra for datascience along with simple python codes for quick mathematical calculation using numpy library.
Issue no: #438

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [x] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-09-23 05:40 UTC, prathimacode-hub requested changes
Changes to be done :

Keep your project title as "Getting Started with Linear Algebra"
Your README.md file and .ipynb file needs more elaboration
Follow the project structure given
The project file name should be in snake case : getting started with linear algebra.ipynb
If you had referred any resources add them up in "DS Resources" folder

Kindly work on it. @Sera001

2021-09-23 14:01 UTC, prathimacode-hub requested changes
Changes to be done :

The file name of .ipynb file should be in snake case : getting_started_with_linear_algebra.ipynb
Your main README.md needs more detailing.

Kindly work on it. @Sera001

2021-09-27 04:53 UTC, prathimacode-hub commented
Have you done the changes? @Sera001

2021-09-27 05:20 UTC, Sera001 commented
Yes, I did......
![image](https://user-images.githubusercontent.com/66793093/134849242-c8a1019a-8c21-49c5-bf9e-5c2ef2749023.png)

2021-09-27 14:46 UTC, DhruvBajaj01 reviewed
Please go through the reviews by other mentors and also add libraries that are being used in the readme.

2021-09-27 14:46 UTC, DhruvBajaj01 commented on Datascience_With_Python/Linear Algebra/Getting started with Linear Algebra/README.md
> +
Add python libraries that are being used for the demonstration of Linear Algebra.

2021-09-27 19:42 UTC, DhruvBajaj01 reviewed
Great work! Reviewed.

2021-09-27 19:45 UTC, DhruvBajaj01 commented
@prathimacode-hub  please give it a final review and merge the file.

2021-09-27 19:50 UTC, Sera001 commented
Thanks a lot!! @DhruvBajaj01

2021-09-29 06:39 UTC, prathimacode-hub approved these changes
PR approved. 👍@Sera001

2021-09-29 06:40 UTC, merged

2021-09-29 08:31 UTC, DhruvBajaj01 reviewed
GREAT WORK @Sera001! keep contributing.

2021-09-29 08:39 UTC, Sera001 commented
Thanks a lot for the suggestions and support! @DhruvBajaj01 and @prathimacode-hub