[Frontend_Web_Development_HTML_CSS_JS] : CSS Classes and IDs
girlscript/winter-of-contributing pull request #2037
Opened 2021-09-22 16:16 UTC by subhendudash02

<hr>

## Description 📜

1. Added the documentation of CSS classes and IDs in the form of markdown file.
2. Added the separate sub-folder for screenshots, HTML and CSS files.

Fixes #951 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-09-22 16:18 UTC, Baalamurgan commented
/assign

2021-09-22 16:19 UTC, Baalamurgan commented
/unassign

2021-09-22 16:28 UTC, code-reaper08 requested changes
I've left a review, look into it and do the needful.

2021-09-22 16:28 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_Classes_And_IDs/README.md
> + The output is
Make alignment of the output images as 

Output is
`<picture here below>`

2021-09-22 16:28 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_Classes_And_IDs/README.md
> +The output is
Make alignment of the output images as 

Output is
`<picture here below>`

2021-09-22 16:28 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_Classes_And_IDs/README.md
> +The output is
Make alignment of the output images as 

Output is
`<picture here below>`

2021-09-22 16:28 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_Classes_And_IDs/README.md
> +The output is
Make alignment of the output images as 

Output is
`<picture here below>`

2021-09-22 16:28 UTC, code-reaper08 commented on .vscode/settings.json
> +}
You don't need this file `.vscode/settings.json`

2021-09-22 16:42 UTC, subhendudash02 commented
@code-reaper08 I have modified the file as suggested.
Thank you!

2021-09-22 16:53 UTC, code-reaper08 requested changes
Hey I was meaning about the alignment of the output image.

**What you have now:**

![Output_alignment](https://user-images.githubusercontent.com/64256342/134386996-3c3b87d3-a379-4297-b0f8-1d73773d3677.png)

**What would be better**

It would be better if the screenshot is below the word "Output is".

Output is

![Expected](https://github.com/girlscript/winter-of-contributing/raw/cdfbe4c6b92c033f26e9b618364419bc8ddb5f38/Web_Development/FrontEnd/CSS_Classes_And_IDs/Images/CSS_Classes.png)

2021-09-22 16:55 UTC, code-reaper08 reviewed
Do change these :-)

2021-09-22 16:55 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_Classes_And_IDs/README.md
> +<hr><br><hr>
You can remove this too.

2021-09-22 16:55 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_Classes_And_IDs/README.md
> +<br><hr><br>
And this one too.

2021-09-22 17:10 UTC, subhendudash02 commented on Web_Development/FrontEnd/CSS_Classes_And_IDs/README.md
> +<br><hr><br>
Oh you mean br and hr tag?

2021-09-22 17:11 UTC, subhendudash02 commented
![image](https://user-images.githubusercontent.com/71781104/134390007-26bf9a50-cc27-43f9-b19e-fbece3c517f7.png)
I don't know, but the image is showing below the content in my text-editor (VS-Code).

2021-09-22 19:35 UTC, code-reaper08 commented
@2024-SANDHYA have a look here.

2021-09-23 07:30 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_Classes_And_IDs/README.md
> +<br><hr><br>
Yes

2021-09-23 12:25 UTC, 2024-SANDHYA requested changes
Sure @code-reaper08 . @subhendudash02  Everything looks fine, just work a bit on content alignment. Like here you can see the note thing should be in one line only and so on..

![image](https://user-images.githubusercontent.com/75671152/134506269-a7274e91-240e-4fd7-b570-8c4814d7df60.png)

2021-09-23 12:33 UTC, subhendudash02 commented
Okay, noted @2024-SANDHYA and @code-reaper08 , the alignment is the big issue here, I will work on this problem tonight.
Thank you so much for the review.🙌

2021-09-24 06:51 UTC, subhendudash02 commented
I have worked on the alignment of the document @code-reaper08, @2024-SANDHYA. Kindly check.

2021-09-24 08:19 UTC, 2024-SANDHYA approved these changes
Looks okayish! @code-reaper08 have a look

2021-09-27 16:58 UTC, Alankrita9 commented
html class and id selectors has already been merged

2021-09-27 17:06 UTC, subhendudash02 commented
> html class and id selectors has already been merged

I know that, I am not demanding to merge this PR, I was demanding to just look for the mistakes..... I am aware of the fact it is already merged.

2021-09-28 15:57 UTC, code-reaper08 reviewed
Looks nice @subhendudash02 🆒

2021-09-30 16:06 UTC, closed without merging