Complete Overview of Regression
girlscript/winter-of-contributing pull request #2049
Opened 2021-09-22 17:40 UTC by yashh18

<hr>

## Description 📜

Documentation contribution for Overview of Regression
Fixes # 735 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-22 17:44 UTC, yashh18 commented
@kareem-negm @Yash621 @prathimacode-hub Please review my PR!

2021-09-22 18:07 UTC, Yash621 reviewed
Firstly make the readme file title bold ,after that make a separate folder for regression analysis under the folder of algorithms ,and place your regression overview file there.
secondly in your explanation you have only talked about linear regression and I can't find enough explanation on polynomial regression ,if you are mentioning a algorithm ,try to give a code example also for them.
and lastly try to include a brief overview of other types of regression like logistics ,lasso,ridge etc under the heading "some other imp types of regression algorithms".No need to give a code example for them just definition and formula.

2021-09-22 18:10 UTC, yashh18 commented
@Yash621 okay cool
So do i have to delete the whole folder and re-upload it or what's the process of editing it?

2021-09-23 04:52 UTC, prathimacode-hub commented
That's upto you. You can do it afresh or do it it in your existing PR. @yashh18

2021-09-23 13:52 UTC, prathimacode-hub requested changes
Changes to be done 👍 

There is no sub repo of Documentation in Machine Learning. It should go in "Tutorials" folder
All images should be in "Images" folder
The project folder should be titled as "Overview of Regression"
The README.md file should be elaborate, it's not sufficient. It only has outline of it. You can add features, why its used, application, advantages, conclusion.
The readme file should be titled as "README.md"
In .ipynb file, you can add few more code snippets to represent the topics given. Also at end, overall summary of the topic.

Kindly work on it. @yashh18

2021-09-24 08:48 UTC, Kareem-negm commented on Datascience_With_Python/Machine Learning/Overview_of_Regression/Documentation/overview_of_regression.ipynb
> +        "![image](images\\regression-analysis-in-machine-learning.png)\r\n",
please fix this image URL too

2021-09-24 08:48 UTC, Kareem-negm commented on Datascience_With_Python/Machine Learning/Overview_of_Regression/Documentation/overview_of_regression.ipynb
> +        "![linreg](images\\linear.jpeg)\r\n",
this too

2021-09-24 08:48 UTC, Kareem-negm commented on Datascience_With_Python/Machine Learning/Overview_of_Regression/Documentation/overview_of_regression.ipynb
> +        "![pol](images\\pr7.png)"
this too

2021-09-24 14:53 UTC, yashh18 commented
@prathimacode-hub Please review it once again !

2021-09-27 04:51 UTC, prathimacode-hub requested changes
Changes to be done :

Your README needs more detailing. This is a vast topic atleast a fair introduction related to this topic is needed. 
You don't have to add all your files in Documentation folder. Instead it can be uploaded in "Overview of Regression" as we have separate folders of Audio and Video
The project file name should be in snake case : overview_of_regression.ipynb
All the images should be in "Images" folder.

Kindly work on it. @yashh18

2021-09-27 13:33 UTC, yashh18 commented
@prathimacode-hub I have deleted the documentation folder and added the files in Overview of regression, changed the .ipynb file to snakecase, added all the images in the required folder and covered most of the information in both readme and jupyter file. 
So please review it once again !

2021-09-29 07:18 UTC, prathimacode-hub approved these changes
PR approved. 👍@yashh18

2021-09-29 07:19 UTC, merged

2021-09-29 07:21 UTC, yashh18 commented
@prathimacode-hub thank you ✨