Added a folder for Responsive_Design_and_Media_Queries
girlscript/winter-of-contributing pull request #2066
Opened 2021-09-22 19:18 UTC by chaudharydivya199

I have added content for Responsive design and Media Queries #1029

2021-09-27 20:33 UTC, praveenscience requested changes
Please go through all the changes and make it.

2021-09-27 20:33 UTC, praveenscience commented on Web_Development/FrontEnd/Responsive_Design_and_Media_Queries/Responsive_Design_and_Media_Queries.md
> +<p>&nbsp;</p>
Please get rid of all the HTML. Use only Markdown.

2021-09-27 20:33 UTC, praveenscience commented on Web_Development/FrontEnd/Responsive_Design_and_Media_Queries/Responsive_Design_and_Media_Queries.md
> +# **What is responsive design?**
No need to bold already bold H1.

2021-10-02 15:58 UTC, chaudharydivya199 commented
@praveenscience  please review my PR

2021-10-03 11:28 UTC, praveenscience commented
@chaudharydivya199 Can you please use the right PR template?

2021-10-03 12:00 UTC, chaudharydivya199 commented
Hello sir but sir I made all the changes .I removed html syntax

On Sun, 3 Oct, 2021, 4:58 pm Praveen Kumar Purushothaman, <
***@***.***> wrote:

> @chaudharydivya199 <https://github.com/chaudharydivya199> Can you please
> use the right PR template?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/girlscript/winter-of-contributing/pull/2066#issuecomment-932931817>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AO5KZX5TWUIO56NLB3BIMU3UFA46FANCNFSM5ESBIUDA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-03 13:00 UTC, chaudharydivya199 commented
@praveenscience  Sir can you please tell me how to use right template PR After that I will make changes. Sir i am confused how to make

2021-10-03 13:06 UTC, closed without merging