Input and Output Operators in C (Issue Number : #923)
girlscript/winter-of-contributing pull request #2075
Opened 2021-09-22 20:07 UTC by Kanishk0412

<hr>

## Description 📜

In the Documentation form, I have demonstrated how to receive user input and produce output using the C programming language. (Issue Number : #923)

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-23 02:18 UTC, geetika005 commented
/assign

2021-09-23 04:14 UTC, vasu-1 commented
@geetika005  and @Kanishk0412 are you same guy ??

- if no then why you(@geetika005 ) have assigned it yourself because the code has been edited by @Kanishk0412 !!!!
  
- if you are same than i can see some corrections like..
    - for input you can add more functions like gets() , getchar() , 
    - and for output you can add putchar() , puts()
    - you can add more informations about their properties .
   
I hope it will make sense ! 
Thanks

2021-09-23 05:30 UTC, Kanishk0412 commented
We are not the same I have made this issue first assign it to me you can check it out.

I'll make the changes thanks for reviewing.

2021-09-23 05:58 UTC, vasu-1 commented
Change the code as suggested and again reopen pr .. You will be assigned to this issue :+1:

2021-09-23 19:38 UTC, Kanishk0412 commented
Updated Necessary Changes

2021-09-23 19:39 UTC, Kanishk0412 commented
/assign

2021-09-25 03:45 UTC, vasu-1 requested changes
### why you have deleted this readme.md ?? 
### don't delete this readme.

- kindly create readme.md file again and also add this line into this readme
     ` * [Input & Output Operation in C](./input-&-ouput-operation.md) `

2021-09-25 03:45 UTC, vasu-1 commented on C_CPP/Input & Output Operations/input-&-ouput-operation.md
> +Output:
```suggestion
**Output**
```

2021-09-25 03:45 UTC, vasu-1 commented on C_CPP/Input & Output Operations/input-&-ouput-operation.md
> +}
```suggestion
int main()  
{
    printf("Hello, World!");
    return 0;   
}
```

- remove this type of unnecessary white spaces from this file.

2021-09-25 06:38 UTC, Kanishk0412 commented
I have made changes as you have suggested.
Please review it and merge it.

Thanks and Regards,
Kanishk Tyagi

2021-09-25 06:38 UTC, Kanishk0412 commented
@vasu-1

2021-09-25 06:45 UTC, vasu-1 commented
Great @Kanishk0412 !
Good to go for merge !!!!
@Suvraneel

2021-09-25 08:16 UTC, Saviour1001 commented
Great work @Kanishk0412

2021-09-25 08:21 UTC, merged

2021-09-25 08:49 UTC, vasu-1 commented
@Kanishk0412 close the Respective issue #923

2021-09-25 14:08 UTC, Kanishk0412 commented
Okay I'll close it. Thanks for merging my branch.

Regards,
Kanishk Tyagi