Created Range Sum and product Queries cpp
girlscript/winter-of-contributing pull request #2087
Opened 2021-09-23 02:48 UTC by kamleshjoshi8102

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #403  

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-23 07:47 UTC, akratikushwah commented
/assign

2021-09-23 18:29 UTC, nimisha-yadav commented
Please review @sneha-nitdgp @harshsri28

2021-09-23 19:36 UTC, harshsri28 requested changes

2021-09-23 19:36 UTC, harshsri28 commented on DSA/1.1 Arrays/3. Range Queries/1.1.3.1_Arrays: Range_Queries_(Sum_and_Product).cpp
> +// Solution to Pre-Compute the sum for every query
instead of commenting , use simple text with highlighter and add theory at starting.

2021-09-30 03:49 UTC, kamleshjoshi8102 commented
@harshsri28 sir, please Review

2021-09-30 14:34 UTC, sneha-nitdgp requested changes
Discuss time and space complexities

2021-09-30 15:32 UTC, harshsri28 requested changes
discuss about time complexity and space complexity, rest is looking fine

2021-10-05 05:34 UTC, nimisha-yadav commented
@kamleshjoshi8102 please make the changes as soon as possible, this is a Week1 topic and we'd like to finish it now.

2021-10-05 05:47 UTC, kamleshjoshi8102 commented
@nimisha-yadav Updated ✅

2021-10-05 05:51 UTC, nimisha-yadav reviewed
Just rename your file 1.1.3.1_Sum_Product_Range_Queries.md

2021-10-05 09:09 UTC, nimisha-yadav approved these changes
LGTM. Congrats on getting your PR merged.

2021-10-05 09:09 UTC, merged

2021-10-05 09:37 UTC, kamleshjoshi8102 commented
> LGTM. Congrats on getting your PR merged.

Thanks! learned a lot! : )