[JS] Topic: Added topics Iterables, Sets and Maps
girlscript/winter-of-contributing pull request #2119
Opened 2021-09-23 05:39 UTC by daminimehra

<hr>

## Description 📜

In this, I have discuss Iterables, Sets, and Maps in JavaScript Objects
Fixes #1833 Issue

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-23 05:42 UTC, daminimehra commented
@paramsiddharth sir pls review it!

2021-09-23 05:56 UTC, paramsiddharth commented
@Creatoon @dakshsethi @s4-2 Please review.

2021-09-23 05:58 UTC, paramsiddharth requested changes

2021-09-23 05:58 UTC, paramsiddharth commented on JavaScript/Topics/Data_Structures/README.md
> +
Please add a title.
```suggestion
# Data Structures in JavaScript

```

2021-09-23 06:10 UTC, s4-2 approved these changes
Looks good to me:)

2021-09-23 06:37 UTC, paramsiddharth approved these changes

2021-09-23 07:04 UTC, daminimehra commented
I have modified this README.md file again, @paramsiddharth sir with some new content. Hope you like it!

2021-09-24 08:14 UTC, paramsiddharth commented
@Creatoon @dakshsethi Please review.

2021-09-24 20:18 UTC, dakshsethi approved these changes
Looks good to me!! 🔥🔥

2021-09-25 01:42 UTC, Creatoon requested changes

2021-09-25 01:42 UTC, Creatoon commented on JavaScript/Topics/Data_Structures/README.md
> +
```suggestion
```
remove 1st empty line

2021-09-25 01:42 UTC, Creatoon commented on JavaScript/Topics/Data_Structures/README.md
> +  // code block to be executed
```suggestion
  // code block to be executed
  console.log(x);
```

2021-09-25 01:42 UTC, Creatoon commented on JavaScript/Topics/Data_Structures/README.md
> +}
```suggestion
}
```
Also write output for this, just for this example, rest is understandable

2021-09-25 01:42 UTC, Creatoon commented on JavaScript/Topics/Data_Structures/README.md
> +for (const x of [1,2,3,4,5] {
```suggestion
for (const x of [1,2,3,4,5]) {
```

2021-09-25 03:55 UTC, daminimehra commented
Done sir @creatoon :)

2021-09-26 10:09 UTC, paramsiddharth commented
@Creatoon Please review further.

2021-09-27 18:01 UTC, merged