Added Switch Expressions in JAVA
girlscript/winter-of-contributing pull request #2158
Opened 2021-09-23 08:25 UTC by eshan1925

<hr>

## Description 📜

I have included the detailed info about the switch case statements (both according to new and old versions of Java)
With this I also added a feature of giving User the choice to copy the code if he/she wants.
Fixes #1899 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
![image](https://user-images.githubusercontent.com/78701779/134369861-7ce5f9e0-4a8f-40e5-9d9d-772db6d3d262.png)

<hr>

2021-09-23 11:53 UTC, prachigarg19 commented
/assign

2021-09-23 17:03 UTC, AkMo3 requested changes
@eshan1925 Examples are good. Please include more examples where a single case evaluates for more than 1 match. Eg:

```java
switch (someObject) {
   case ClassOne first, ClassTwo second ->  System.out.println("Type of Class One or Two");
   case ClassThird thr, ClassFour frh ->  System.out.println("Type of Class Third or Fourth");
}

2021-09-23 17:04 UTC, AkMo3 commented
Also, show that if switch is inside any iteration statement, you cannot use `continue, break ...`

2021-09-23 17:28 UTC, eshan1925 commented
Done @AkMo3

2021-09-23 18:05 UTC, AkMo3 requested changes
Minor:

2021-09-23 18:05 UTC, AkMo3 commented on Java/Control Statements/Switch Expressions/6.3 Switch Expressions.md
> +Now here we can see that a single obk=ject i.e. someObject can two times give the same output.
`obk=ject` -> `object`

2021-09-23 19:28 UTC, eshan1925 commented
Please merge it now @AkMo3

2021-09-23 19:28 UTC, AkMo3 approved these changes

2021-09-23 19:29 UTC, AkMo3 commented
@eshan1925 A PR would be merged after approval of one mentor and one supervisor or two supervisors.

2021-09-23 19:33 UTC, eshan1925 commented
So will this Happen tomorrow @AkMo3

2021-09-23 19:37 UTC, AkMo3 commented
Yes.

On Fri, 24 Sep, 2021, 1:03 am Eshan Gupta, ***@***.***> wrote:

> So will this Happen tomorrow @AkMo3 <https://github.com/AkMo3>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/girlscript/winter-of-contributing/pull/2158#issuecomment-926096712>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQRHA5WL3QS67PIJEF6BM6TUDN6J3ANCNFSM5ETDTBJQ>
> .
>

2021-09-24 09:42 UTC, AkMo3 commented
@garvitraj Please look at it and merge it in higher preference than others.

2021-09-24 10:09 UTC, garvitraj approved these changes
@eshan1925 just complete the changes asap and do let me know

2021-09-24 10:09 UTC, garvitraj commented on Java/Control Statements/Switch Expressions/6.3 Switch Expressions.md
> +Now if we will use the above syntax of switch case statements then JRE(Java Runtime Environment) will match the labels to the left side of the arrow, it will run the code to the right of the arrow an
`through;` to `through,`

2021-09-24 10:09 UTC, garvitraj commented on Java/Control Statements/Switch Expressions/6.3 Switch Expressions.md
> +Now it must be difficult writing all those break statements again and again so with the new versions of Java they introduced a new method/syntax of writing switch-case statements. The arrow pointer v
`because if we forget to use them` to `because if we forget to use them,` 
`then the code will keep running`  to `then the code keeps on running`

2021-09-24 10:14 UTC, eshan1925 commented
@garvitraj I have done all the changes.

2021-09-24 10:17 UTC, garvitraj approved these changes

2021-09-24 10:17 UTC, merged