#1013
girlscript/winter-of-contributing pull request #2192
Opened 2021-09-23 11:07 UTC by Durva15

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # 1013

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev React/Angular/Vue

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-23 12:56 UTC, heet-kumar requested changes
Add References in the file from where you have referred and prepared this documentation . As it is necessary to to add mentioned by the GWOC Team members in server-announcement channel in discord server.

2021-09-23 15:15 UTC, Durva15 commented
@heet-kumar I added the references, you can check it out.

2021-09-25 15:17 UTC, the-pro approved these changes

2021-09-25 15:17 UTC, merged

2021-09-26 04:25 UTC, Durva15 commented
Thank you @the-pro @anandhu720 for the successful merge.✨