DSA:1.1.3.3 Arrays: Range Queries
girlscript/winter-of-contributing pull request #2202
Opened 2021-09-23 11:26 UTC by Ayushi2811

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #409 

<hr>

## Type of change 📝:Added the required Documentation

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-23 11:29 UTC, Ayushi2811 commented
@nimisha-yadav Completed the documentation and commited the the PR for issue#409.
Kindly review it.

2021-09-23 13:14 UTC, Sin-Sumit approved these changes

2021-09-23 17:48 UTC, nimisha-yadav commented
Please review @sneha-nitdgp @harshsri28

2021-09-23 19:58 UTC, harshsri28 requested changes

2021-09-23 19:58 UTC, harshsri28 commented on DSA/1.1 Arrays/3. Range Queries/DSA 1.1.3.3 Arrays: Range Queries.md
> +The answer to this is that it consist the difference of the adjacent element present in the original array.So difference array is the array which contains the difference of the adjacentelements of th
fix typo i.e adjacentelements

2021-09-24 06:19 UTC, Ayushi2811 reviewed
done changes @harshsri28

2021-09-24 06:19 UTC, Ayushi2811 commented on DSA/1.1 Arrays/3. Range Queries/DSA 1.1.3.3 Arrays: Range Queries.md
> +The answer to this is that it consist the difference of the adjacent element present in the original array.So difference array is the array which contains the difference of the adjacentelements of th
Done these changes @harshsri28

2021-09-24 08:48 UTC, harshsri28 approved these changes
LGTM

2021-09-25 04:14 UTC, Ayushi2811 commented
when will this issue get closed so that i can get other to be assigned?
@harshsri28

2021-09-25 06:59 UTC, harshsri28 commented
supervisor has a right to merge.

2021-09-25 13:36 UTC, sneha-nitdgp approved these changes

2021-09-25 20:51 UTC, nimisha-yadav reviewed
LGTM. Just rename your file 1.1.3.3_Difference_Array.md

2021-09-27 04:45 UTC, Ayushi2811 commented
@nimisha-yadav  changes done

2021-09-27 10:54 UTC, nimisha-yadav commented
> @nimisha-yadav changes done

You changed the name of the PR and not the file. Rename your file @Ayushi2811

2021-09-29 07:10 UTC, merged

2021-09-29 07:11 UTC, Muskan-creator commented
Congrats on getting your pr merged🎉.Thanks for contributing