Documentation on Closures in JavaScript
girlscript/winter-of-contributing pull request #2256
Opened 2021-09-23 14:20 UTC by Ananyagupta43

<hr>

## Description 📜
Created a documentation on Closures in JavaScript .The Documentation explains the concepts of execution context,lexical environment and working of closures.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #1265
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-24 08:12 UTC, paramsiddharth approved these changes

2021-09-24 08:13 UTC, paramsiddharth commented
@Creatoon @dakshsethi @s4-2 Please review.

2021-09-24 20:22 UTC, dakshsethi requested changes

2021-09-24 20:22 UTC, dakshsethi commented on JavaScript/Topics/12.Closures_In_JavaScript/Readme.md
> +### Contributor : [Ananya Gupta](https://github.com/Ananyagupta43)
Doesn't need to be a heading
Just write this 
`Contributor : [Ananya Gupta](https://github.com/Ananyagupta43)`

2021-09-25 01:59 UTC, Creatoon approved these changes

2021-09-25 01:59 UTC, Creatoon commented on JavaScript/Topics/12.Closures_In_JavaScript/Readme.md
> +Execution context is an abstract space where the JavaScript code is  evaluated and executed.
```suggestion
Execution context is an abstract space where the JavaScript code is evaluated and executed.
```

2021-09-25 01:59 UTC, Creatoon commented on JavaScript/Topics/12.Closures_In_JavaScript/Readme.md
> +We have two functions c and a:=
```suggestion
We have two functions c and a :=
```

2021-09-25 02:00 UTC, Creatoon commented
@Ananyagupta43 Just make above few changes , rest i approved the pr as other things looks good to me and these are just minor mistakes

2021-09-25 03:25 UTC, Ananyagupta43 commented
@Creatoon Ok sir I'll make these changes.

2021-09-25 04:52 UTC, Ananyagupta43 commented
@Creatoon Sir I made the changes .Please review it.

2021-09-25 12:36 UTC, dakshsethi approved these changes
Looks good to me!! 🔥🔥🔥

2021-09-25 13:22 UTC, Ananyagupta43 commented
@dakshsethi Thanks Sir.

2021-09-25 14:33 UTC, Ananyagupta43 commented
@paramsiddharth Sir I have made all the necessary changes please review it.

2021-09-26 10:36 UTC, merged