Operator Overloading in C++
girlscript/winter-of-contributing pull request #2315
Opened 2021-09-23 17:37 UTC by Akriti-Choudhary

<hr>

## Description 📜

The documentation provides details about Operator Overloading in C++ along with some codes.

Fixes # <issue_number_here> #1754 

<hr>

## Type of change 📝

- [ x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x ] C/CPP

<hr>

## Checklist ✅

- [ x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented on my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [x ] I'm GWOC'21 contributor

<hr>

2021-09-23 19:03 UTC, vasu-1 requested changes
Please do this changes !

2021-09-23 19:03 UTC, vasu-1 commented on C_CPP/Operator Overloading/operator_overloading_in_c++.md
> +#include <iostream>
```suggestion

**Code for operator overloading implemented using non-member function**

```c
/*Add two arrays using operator overloading implemented through non-member (friend) function*/

#include <iostream>
```

2021-09-23 19:03 UTC, vasu-1 commented on C_CPP/Operator Overloading/operator_overloading_in_c++.md
> +    {
```suggestion
public:
    AddArray();                     //default constructor
    AddArray(int);                  //parameterized constructor
    void display();                 //function for displaying the elements of an array
    friend AddArray operator+(AddArray ,AddArray ); //non-member function to overload +operator
};

AddArray::AddArray()
{
    for (int i = 0; i < 5; ++i)
    {
```

2021-09-23 19:11 UTC, vasu-1 requested changes

2021-09-23 19:11 UTC, vasu-1 commented on C_CPP/Operator Overloading/operator_overloading_in_c++.md
```suggestion
# Operator Overloading

```

add this space

2021-09-23 19:19 UTC, Akriti-Choudhary commented
@vasu-1  I have done all the required changes. Please, review the project again.

2021-09-23 20:25 UTC, Suvraneel reviewed
Also, add a line at Operator Overloading/readme.md

2021-09-23 20:28 UTC, Suvraneel commented
@vasu-1 Nice review btw 💯

2021-09-24 04:38 UTC, Akriti-Choudhary commented
@Suvraneel I have updated the readme via PR https://github.com/girlscript/winter-of-contributing/pull/2367
Kindly, Review this.

2021-09-24 06:20 UTC, vasu-1 approved these changes
Done

2021-09-24 08:22 UTC, Suvraneel commented
@Akriti-Chaudhary Also, add a line at Operator Overloading/readme.md in this patch-2 branch itself

2021-09-24 08:53 UTC, Akriti-Choudhary commented
@Suvraneel  alright, done.

2021-09-24 13:32 UTC, merged

2021-09-24 13:33 UTC, Suvraneel commented
Way to go @Akriti-Choudhary ... ❤️  Great :octocat:

2021-09-24 13:46 UTC, Akriti-Choudhary commented
Thank you @Suvraneel and @vasu-1 for correcting me constantly.