[JS] Topic: Events in JavaScript
girlscript/winter-of-contributing pull request #2408
Opened 2021-09-24 07:52 UTC by sushovanb02

<hr>

## Description 📜

Created a document on Events in JavaScript
Fixes #2319 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-24 07:54 UTC, sushovanb02 commented
@paramsiddharth @s4-2 @Creatoon @dakshsethi please review this PR

2021-09-24 08:26 UTC, paramsiddharth approved these changes

2021-09-24 11:07 UTC, dakshsethi requested changes

2021-09-24 11:07 UTC, dakshsethi commented on JavaScript/Topics/15.Events/README.md
> +| onblur             | script | Triggers when the window loses focus                                                                         |
Link all of these attributes to their W3Schools demo page.
For Example
`[onblur](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onblur)`

2021-09-24 20:17 UTC, dakshsethi requested changes
Add all events with their links.

2021-09-25 01:20 UTC, Creatoon commented
@dakshsethi Write a generalized example, and show, who is event listener, who is event handler and what's the event, also briefly describe event listener and handler

2021-09-25 01:26 UTC, Creatoon requested changes

2021-09-25 01:26 UTC, Creatoon commented on JavaScript/Topics/15.Events/README.md
> +// Execute a JavaScript when a form is submitted:
```suggestion
// Execute `myFunction()` when the form is submitted:
```

2021-09-25 03:14 UTC, sushovanb02 commented
> @sushovanb02
> Write a generalized example, and show, who is event listener, who is event handler and what's the event, also briefly describe event listener and handler

ok

2021-09-25 03:43 UTC, sushovanb02 commented on JavaScript/Topics/15.Events/README.md
> +// Execute a JavaScript when a form is submitted:
@Creatoon check now

2021-09-25 06:52 UTC, Creatoon approved these changes

2021-09-25 12:05 UTC, sushovanb02 commented
> Add all events with their links.

@dakshsethi done, now you may check

2021-09-25 12:34 UTC, dakshsethi approved these changes
Looks good to me!! 🔥🔥🔥

2021-09-25 12:40 UTC, sushovanb02 commented
@paramsiddharth all reviews done i guess you can merge this now

2021-09-26 10:31 UTC, merged