Dsa
girlscript/winter-of-contributing pull request #2515
Opened 2021-09-24 16:50 UTC by AnkitaGupta454

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <2454> 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] DSA

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-24 18:43 UTC, nimisha-yadav commented
@AnkitaGupta454 remove the brackets and do not add space between # and digits then your issue will be attached.

2021-09-24 18:43 UTC, nimisha-yadav commented
Please review @harshsri28 @sneha-nitdgp

2021-09-24 19:03 UTC, harshsri28 requested changes
Add problem statement heading , intuition , algorithm and discuss about TC and SC

2021-09-24 19:03 UTC, harshsri28 commented on DSA/Readme.md
> +Given an array arr[ ] of size N having distinct elements, the task is to find the next greater element for each element of the array in order of their appearance in the array.
Add Problem statement  heading

2021-09-24 19:03 UTC, harshsri28 commented on DSA/Readme.md
> +
Discuss intuition and your approach and Time complexity and Space complexity

2021-09-25 07:00 UTC, harshsri28 approved these changes
LGTM

2021-09-25 09:29 UTC, sneha-nitdgp approved these changes
Good

2021-09-25 21:46 UTC, nimisha-yadav requested changes
@AnkitaGupta454 I'm sorry to say but 92% of your file content has been found plagiarized from online resources like GFG and Ideserve. I'm closing this PR. Kindly take up a new issue and from next time, research the topic and try to write in your own words. Also, do not forget to provide references for pictures used in your content.

2021-09-25 21:47 UTC, closed without merging