added break and continue documentation
girlscript/winter-of-contributing pull request #2520
Opened 2021-09-24 17:01 UTC by rajmadhu0406

<hr>

## Description 📜

I have added documentation about break and continue statement. The documentation contains syntax and examples along with written programs. I have also included a .gif file for better understandability.
Fixes #1995   

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [x] Java_Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-25 01:58 UTC, vishnu95075 commented
/assign

2021-09-26 15:02 UTC, garvitraj commented
@AkMo3 pls have a final look

2021-09-27 16:02 UTC, AkMo3 requested changes

2021-09-27 16:02 UTC, AkMo3 commented on Java/Jump Statements/Break and continue/Break and Continue.md
> +-Wherever the __"break"__ keyword is used, the loop is instantly terminated. <br>
Hi, just a minor change. Please change it to the bulletin. Like `1,` or circle

2021-09-27 19:30 UTC, garvitraj approved these changes

2021-09-28 09:27 UTC, AkMo3 approved these changes

2021-09-28 09:29 UTC, merged

2021-09-28 09:29 UTC, AkMo3 commented on Java/Jump Statements/Break and continue/Break and Continue.md
> +-Wherever the __"break"__ keyword is used, the loop is instantly terminated. <br>
> Hi, just a minor change. Please change it to the bulletin. Like 1, or circle and all other similar places.
> indicates you are referring to something said in the past.

Done by me