Add files via upload
girlscript/winter-of-contributing pull request #2529
Opened 2021-09-24 17:45 UTC by newbiens

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <#2121> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [x ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-26 09:43 UTC, sneha-nitdgp requested changes
Some typos are present, fix them.

2021-09-26 12:14 UTC, newbiens commented
Fixed

2021-09-26 17:21 UTC, harshsri28 requested changes

2021-09-26 17:30 UTC, harshsri28 commented on DSA/AnalysisOfSearchingAlgorithms/Searching Algorithm.txt
> +Comparision between Binary Search and Linear Search
Remove unnecessary space also

2021-09-27 04:00 UTC, newbiens commented
I have made the required changes.

2021-09-27 06:59 UTC, harshsri28 approved these changes
LGTM

2021-09-27 09:24 UTC, sneha-nitdgp approved these changes
LGTM

2021-09-28 02:20 UTC, nimisha-yadav commented
Hey @newbiens, your PR is good but the issue you've created looks repetitive, I'd try to add your content too to the file and will let you know about the same.

Meanwhile, feel free to comment on the new issues I've created, you may work on them without any hassle.

2021-09-28 03:09 UTC, newbiens commented
only a certain topic might be similar but the whole issue and its contents are completely new as far as I've seen, Please merge this one.

2021-09-28 15:43 UTC, nimisha-yadav reviewed
Looks great. Just rename your folder as 2.2 Searching & Sorting Algorithms and your file as 2.2_Overview_and_Standard_Problem_On_Binary_Search.md

2021-09-28 16:50 UTC, newbiens commented
Done

2021-09-28 17:06 UTC, nimisha-yadav approved these changes
Congrats on getting your PR merged :star:

2021-09-28 17:06 UTC, merged

2021-09-28 17:13 UTC, newbiens commented
Thanks⭐