FrontEnd : CSS : Transition and transformation (D) - Part 2 (only contains Transitions)
girlscript/winter-of-contributing pull request #2606
Opened 2021-09-25 06:46 UTC by RC2208

<hr>

## Description 📜

CSS transitions documentation and code. This my 2nd PR on the issue. 
Fixes # #1061
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-27 13:56 UTC, RC2208 commented
https://github.com/girlscript/winter-of-contributing/pull/2295

Here's the 2nd PR please merge both

2021-09-29 14:16 UTC, code-reaper08 requested changes
I've left a review, please look into it, add syntax specific codeblocks to all code examples.

2021-09-29 14:16 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_Transition_And_Transformation/Transitions.md
> +css
You need to have the codes in code blocks like 

```css
div {
  transition: width 2s, height 4s;
}
```

2021-09-29 14:16 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_Transition_And_Transformation/Transitions.md
> +div {
Codeblocks here too

2021-09-29 14:16 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_Transition_And_Transformation/Transitions.md
> +div:hover {
Codeblocks here

2021-09-29 14:27 UTC, RC2208 commented
> I've left a review, please look into it, add syntax specific codeblocks to all code examples.

Thank you , I forgot to add them.  Added them now!

2021-09-30 16:41 UTC, code-reaper08 reviewed
@2024-SANDHYA have a look here, this is the second part of https://github.com/girlscript/winter-of-contributing/pull/2295/

2021-09-30 16:47 UTC, 2024-SANDHYA commented
> 
> 
> @2024-SANDHYA have a look here, this is the second part of #2295

Why two parts @RC2208  ? You can include it in one file itself, just divide it into two parts that's it. What do you say @code-reaper08  ?

2021-09-30 16:49 UTC, RC2208 commented
> > @2024-SANDHYA have a look here, this is the second part of #2295
> 
> Why two parts @RC2208 ? You can include it in one file itself, just divide it into two parts that's it. What do you say @code-reaper08 ?

Hey!I asked 3-4 supervisors and the program manager if I could make 2 seperate PR's since the documentation for both were very long. They allowed it so it can count as 2 PR's for contribution @2024-SANDHYA

2021-09-30 17:03 UTC, 2024-SANDHYA commented
> 
> 
> > > @2024-SANDHYA have a look here, this is the second part of #2295
> > 
> > 
> > Why two parts @RC2208 ? You can include it in one file itself, just divide it into two parts that's it. What do you say @code-reaper08 ?
> 
> Hey!I asked 3-4 supervisors and the program manager if I could make 2 seperate PR's since the documentation for both were very long. They allowed it so it can count as 2 PR's for contribution @2024-SANDHYA

Ya that too is accepted but ,okay as you feel you can do that after all, it's open-source, can't restrict you & your creativity ☺️

2021-09-30 17:44 UTC, RC2208 commented
> > > > @2024-SANDHYA have a look here, this is the second part of #2295
> > > 
> > > 
> > > Why two parts @RC2208 ? You can include it in one file itself, just divide it into two parts that's it. What do you say @code-reaper08 ?
> > 
> > 
> > Hey!I asked 3-4 supervisors and the program manager if I could make 2 seperate PR's since the documentation for both were very long. They allowed it so it can count as 2 PR's for contribution @2024-SANDHYA
> 
> Ya that too is accepted but ,okay as you feel you can do that after all, it's open-source, can't restrict you & your creativity ☺️

Okay 😁

2021-09-30 19:28 UTC, code-reaper08 approved these changes

2021-09-30 19:29 UTC, merged