Pairs in c++
girlscript/winter-of-contributing pull request #2666
Opened 2021-09-25 13:12 UTC by geetika005

<hr>

## Description 📜

Pairs in C++ standard template library #2257
There is basic introduction to pair.

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x ] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [x ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-25 13:43 UTC, vasu-1 requested changes
- please put your content inside C/CPP's respective subdirectories.
- for this move your pair.md file inside ` /C_CPP/Data Structures/Standard Template Library/ `

2021-09-25 13:44 UTC, geetika005 commented
ok i will do that

2021-09-25 13:44 UTC, vasu-1 commented
Note : You can only put your content in C/CPP's Subdirectories.

2021-09-25 13:58 UTC, geetika005 commented
Is it ok now

2021-09-25 14:57 UTC, vasu-1 requested changes
Hey @geetika005 i have done some markdown formatting.
kindly see , learn & make those changes.
[link](https://github.com/vasu-1/vasu-1/blob/main/pair.txt)
see this link...

2021-09-25 15:01 UTC, vasu-1 commented
Also, add a link of your code in ` Standard Template Library/readme.md `.

- add this line in `Standard Template Library/readme.md`
` - [Pair](./pair.md) `

2021-09-25 17:14 UTC, geetika005 commented
Done with the changes ,please check it now.

2021-09-25 18:04 UTC, vasu-1 approved these changes
Great @geetika005 ~!!!!!

Good to go for Merge @Suvraneel

2021-09-25 20:20 UTC, Suvraneel commented
@vasu-1  Excellent reviewing ❤️ 

@geetika005  Perfect & neat explanation... Would love if it was atleast a 2 minute read
Try adding make_pair & tie() etc...

2021-09-25 20:21 UTC, Suvraneel requested changes

2021-09-25 20:21 UTC, Suvraneel commented on C_CPP/Data Structures/Standard Template Library/pair.md
> +
make pair
tie () etc....

Amplify & Enhance doc

2021-09-26 06:23 UTC, geetika005 commented
Made the changes sir.

2021-09-26 06:30 UTC, geetika005 commented on C_CPP/Data Structures/Standard Template Library/pair.md
> +
added

2021-09-26 16:12 UTC, Suvraneel approved these changes
Awesome ❤️ documentation :octocat: 
Looking forwad to more great contribs from you 💯

2021-09-26 16:12 UTC, merged