JS: Functions
girlscript/winter-of-contributing pull request #270
Opened 2021-09-16 15:21 UTC by siddhi-244

<hr>

## Description 📜

Added brief into about functions in javascript. 
Fixes #247 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ]
-[x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ 

- [x] JavaScript

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-16 17:01 UTC, Creatoon requested changes

2021-09-16 17:02 UTC, Creatoon commented
@siddhi-244 Also check for grammatical errors.

2021-09-16 17:03 UTC, siddhi-244 commented
> @siddhi-244 Also check for grammatical errors.

Sure

2021-09-16 17:06 UTC, siddhi-244 commented
Done !

2021-09-16 17:09 UTC, Creatoon requested changes

2021-09-16 17:09 UTC, Creatoon commented on Web_Development/Javascript/Topics/5.Syntax/6.Functions/README.md
>  Functions can also return values.
```suggestion
Functions can also return values.

```

2021-09-16 17:10 UTC, Creatoon commented on Web_Development/Javascript/Topics/5.Syntax/6.Functions/README.md
>  Functions can also return values.
I said leave one line, just commit it

2021-09-16 17:15 UTC, siddhi-244 commented
Done

2021-09-17 08:03 UTC, siddhi-244 commented
> @siddhi-244 Also check for grammatical errors.

Sorry I have done all the changes

2021-09-17 13:11 UTC, paramsiddharth commented
@siddhi-244 You seem to have pulled updates from `girlscript:main` to the branch for this PR, whereas you should have pulled from `girlscript:Javascript` to this branch. :) Although that doesn't cause any errors here, be careful as this may introduce inconsistensies.

Since your PR is the first one for #247, you are at priority. Only one mentor is active so I'll not wait for further reviews. I'll review it and merge it as soon as possible.

2021-09-17 13:13 UTC, siddhi-244 commented
> @siddhi-244 You seem to have pulled updates from `girlscript:main` to the branch for this PR, whereas you should have pulled from `girlscript:Javascript` to this branch. :) Although that doesn't cause any errors here, be careful as this may introduce inconsistensies.
> 
> Since your PR is the first one for #247, you are at priority. Only one mentor is active so I'll not wait for further reviews. I'll review it and merge it as soon as possible.

I am really srry. I will see to it next time.

2021-09-17 13:13 UTC, paramsiddharth requested changes

2021-09-17 13:13 UTC, paramsiddharth commented on Web_Development/Javascript/Topics/5.Syntax/6.Functions/README.md
> +
You might want to mention your name here as a contributor.
```
Contributor: Siddhi
```
Please update the PR.

2021-09-17 13:17 UTC, siddhi-244 commented
Done @paramsiddharth sir

2021-09-17 13:43 UTC, paramsiddharth approved these changes

2021-09-17 13:55 UTC, Creatoon approved these changes

2021-09-17 13:57 UTC, Creatoon approved these changes

2021-09-17 13:58 UTC, paramsiddharth commented
@dakshsethi Could you please review the PR, and request any changes if needed?

2021-09-18 03:21 UTC, dakshsethi requested changes

2021-09-18 03:21 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/6.Functions/README.md
> +console.log(a); //ReferenceError
Mention the error message exactly as it shows in the console window `ReferenceError: a is undefined`

2021-09-18 03:40 UTC, siddhi-244 commented
Done Sir @dakshsethi

2021-09-18 03:54 UTC, paramsiddharth commented
@dakshsethi Please review further. :)

2021-09-18 04:56 UTC, dakshsethi approved these changes
Looks good to me!!

2021-09-18 09:19 UTC, merged