Cyclic Sort
girlscript/winter-of-contributing pull request #2707
Opened 2021-09-25 15:46 UTC by aniket-24

<hr>

## Description 📜

In this, we will get a brief idea about the Cyclic Sort in C++
Fixes # 2443

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/#CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-25 20:30 UTC, Suvraneel commented
@aniket-24  Directory organisation wise perfect & technicaly sound

But since this is supposed to be a documentation, elaborate/explain cycle sort (with a picture if need be) before writing the code

2021-09-26 15:41 UTC, deeqakkk approved these changes

2021-09-26 16:07 UTC, Suvraneel requested changes
Explain your approach properly... Embed an image if needed

2021-09-26 16:07 UTC, Suvraneel commented on C_CPP/Algorithmic Approaches/Sorting/Cyclic_Sort.md
> +
Add more documentation

2021-09-27 06:37 UTC, aniket-24 commented
added more documentation!
Please review this @deeqakkk  @Suvraneel

2021-09-27 14:42 UTC, merged