Data Science with Python : Random Forest Algorithm
girlscript/winter-of-contributing pull request #2736
Opened 2021-09-25 18:31 UTC by Akshat2019VITB

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ x] Datascience with Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-26 02:05 UTC, manthan89-py commented
Interested for this work

2021-09-26 10:10 UTC, prathimacode-hub commented
Add up your issue number? @Akshat2019VITB

2021-09-26 10:16 UTC, Akshat2019VITB commented
Issue Number - 1038

2021-09-27 05:54 UTC, prathimacode-hub requested changes
Changes to be done :
 
The readme file should be titled as README.md and project file name in snake case : random_forest_algorithm.ipynb
In README.md, add workflow, its usage, advantages, applications, why its preferred, final outcomes and conclusion.
Instead of getting directly into code implementation. start with introduction of the issue topic and then into coding and present overall summary of your work done at the end.

Kindly work on it. @Akshat2019VITB

2021-09-27 14:37 UTC, DhruvBajaj01 reviewed
I will go through the code, once you make you changes in your readme. Thank you for your contribution.

2021-09-27 14:37 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +![](https://github.com/Akshat2019VITB/winter-of-contributing/blob/Datascience_With_Python/Datascience_With_Python/Machine%20Learning/Algorithms/Random%20Forest%20Algorithm/Images/5.PNG)
You need not add a screenshot is read me. Just an overview will work.

2021-09-27 14:37 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +
You need not explain your code here its, already in your notebook.

2021-09-27 14:37 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +
Add libraries that you used while constructing the project.

2021-09-27 14:56 UTC, Akshat2019VITB commented
@DhruvBajaj01 I have made the changes in the README.md file as requested.

2021-09-27 15:08 UTC, DhruvBajaj01 commented
Have you removed code images from the readme file? Also, have you added libraries used?

2021-09-27 15:54 UTC, Akshat2019VITB commented
I have added the libraries used and removed the code images. @DhruvBajaj01

2021-09-27 16:30 UTC, DhruvBajaj01 reviewed
I added plag in front of the line that was plagiarised. Your plagiarism counts to around 51% try to reduce it to at least 20 %. 
Go through https://www.duplichecker.com/ before submitting your file.
Make the changes and you are ready to merge PR

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +- A random forest is a machine learning technique that’s used to solve regression and classification problems. It utilizes ensemble learning, which is a technique that combines many classifiers to pr
Plagiarised Line

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +The (random forest) algorithm establishes the outcome based on the predictions of the decision trees. It predicts by taking the average or mean of the output from various trees. Increasing the number
plagiarised line

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +A decision tree consists of three components: decision nodes, leaf nodes, and a root node. A decision tree algorithm divides a training dataset into branches, which further segregate into other branc
plag

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +- It’s more accurate than the decision tree algorithm.
plag

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +- It can produce a reasonable prediction without hyper-parameter tuning.
plag

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +- It solves the issue of overfitting in decision trees.
plag

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +- Random forests is considered as a highly accurate and robust method because of the number of decision trees participating in the process.
plag

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +- It does not suffer from the overfitting problem. The main reason is that it takes the average of all the predictions, which cancels out the biases.
plag

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +- The algorithm can be used in both classification and regression problems.
plag

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +- Random forests can also handle missing values. There are two ways to handle these: using median values to replace continuous variables, and computing the proximity-weighted average of missing value
plag

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +- You can get the relative feature importance, which helps in selecting the most contributing features for the classifier.
plag

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +- Random forests is a set of multiple decision trees.
plag

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +- Deep decision trees may suffer from overfitting, but random forests prevents overfitting by creating trees on random subsets.
plag

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +- The Random Forest Algorithm is a machine learning algorithm that is easy to use and flexible. It uses ensemble learning, which enables organizations to solve regression and classification problems.
plag

2021-09-27 16:30 UTC, DhruvBajaj01 commented on Datascience_With_Python/Machine Learning/Algorithms/Random Forest Algorithm/README.md
> +- This is an ideal algorithm for developers because it solves the problem of overfitting of datasets. It’s a very resourceful tool for making accurate predictions needed in strategic decision making
plag

2021-09-28 07:35 UTC, Akshat2019VITB commented
@DhruvBajaj01 I have the required changes in README.md.

2021-09-28 08:35 UTC, DhruvBajaj01 reviewed
Nice work @Akshat2019VITB, @prathimacode-hub please make a final review and merge the contribution.

2021-10-03 06:36 UTC, prathimacode-hub approved these changes
@Akshat2019VITB Well done. You had done a amazing work. 🎉👌

2021-10-03 06:37 UTC, merged