Stack_Using_STL
girlscript/winter-of-contributing pull request #2737
Opened 2021-09-25 18:43 UTC by aman12207

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #2221 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-26 15:26 UTC, deeqakkk requested changes
also  update link to the directory folder

2021-09-26 15:26 UTC, deeqakkk commented on C_CPP/Stack_Using_STL.MD
> +In stack, the order in which the data arrives is important. The Stack allows elements to be added and removed from one end only. Stacks are ideal for enforcing sequential rules of access ie, LIFO.
do add "last in first out" after LIFO

2021-09-26 15:56 UTC, aman12207 commented
> also update link to the directory folder

Please explain how can i do this

2021-09-27 16:10 UTC, aman12207 commented
@deeqakkk @Suvraneel  I have done the changes

2021-09-27 20:28 UTC, Suvraneel commented
@aman12207  Wrong directory 
Correct directory :
C_CPP/Data Structures/Standard Template Library/Stack/

Shift doc there & update corresponding readme

2021-09-27 20:29 UTC, Suvraneel requested changes
@aman12207 Wrong directory
Correct directory :
C_CPP/Data Structures/Standard Template Library/Stack/

Shift doc there & update corresponding readme

2021-09-28 15:05 UTC, Suvraneel requested changes

2021-09-28 15:05 UTC, Suvraneel commented on C_CPP/Data Structures/Stack/readme.md
> -- [Stacks](./Stacks.md)
Restore this file

2021-09-29 12:22 UTC, aman12207 commented
@Suvraneel Sir Please review this . I made changes as directed

2021-09-30 14:02 UTC, merged

2021-09-30 14:02 UTC, Suvraneel commented
@aman12207  Good Work ❤️