C cpp
girlscript/winter-of-contributing pull request #2747
Opened 2021-09-25 20:11 UTC by Shikhar253

<hr>

## Description 📜
Added the documentation on File Handling in C 

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #914

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-26 05:24 UTC, vasu-1 requested changes
Really Great !!!!! @Shikhar253 
One of the best PR !!!!

@Suvraneel  please review and merge !!!

2021-09-26 17:02 UTC, Suvraneel commented
@Shikhar253  No cap, this is one of the very best PRs I've read yet (I love the fact that you've exploited every feature md has to offer)

So since this is a perfect PR, as a review I want to ponder over your statement in Types of File in C:
`Text file has .txt extension`
whereas afaik it also supports various other extensions : eg, `.csv` ... which cllassifies under ASCII file

So, if you feel you need to add something there, you may... Otherwise I'll just come back later & merge this directly :octocat: 🌊

2021-09-26 20:15 UTC, Shikhar253 commented
Thanks @Suvraneel and @vasu-1 ! I have made the required changes .

2021-09-27 04:07 UTC, vasu-1 approved these changes
Great @Shikhar253 

@Suvraneel

2021-09-27 15:03 UTC, merged

2021-09-27 15:05 UTC, Suvraneel commented
@Shikhar253  Awesome :heart: