Data Science with Python : ID3 Classification Algorithm #1822
girlscript/winter-of-contributing pull request #2770
Opened 2021-09-26 05:06 UTC by surjyaneeh

<hr>

## Description 📜

Fixes # <1822> 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Datascience with #Python

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

2021-09-26 05:10 UTC, surjyaneeh commented
Please review @prathimacode-hub

2021-09-26 06:49 UTC, Kareem-negm commented
Hello @surjyaneeh ,I don't see any contributions (Docs , Code) to review
please add all require files

2021-09-26 08:54 UTC, surjyaneeh commented
> Hello @surjyaneeh ,I don't see any contributions (Docs , Code) to review
> please add all require files

But sir, It's clearly visible in dswp > ml > Algorithms

https://github.com/surjyaneeh/winter-of-contributing/tree/Datascience_With_Python/Datascience_With_Python/Machine%20Learning/Algorithms/ID3%20Classification%20Algorithm

2021-09-26 12:45 UTC, Kareem-negm commented
it's showing now, your work seems good 
I appreciate your effort @surjyaneeh  
I will take a look and when I notice anything I will review it

2021-09-26 12:49 UTC, Kareem-negm reviewed
it will be better if you made these links as more professional, it showing that you are organized 
just make a markdown  like [ID3 Decision Tree Classifier from scratch in Python](https://towardsdatascience.com/id3-decision-tree-classifier-from-scratch-in-python-b38ef145fd90#:~:text=%20ID3%20Decision%20Tree%20Classifier%20from%20scratch%20in,wind%20blows%20from%20the%20South.%20If...%20More%20)

2021-09-26 12:50 UTC, Kareem-negm commented on Datascience_With_Python/Machine Learning/Algorithms/ID3 Classification Algorithm/README.md
> +1. https://towardsdatascience.com/id3-decision-tree-classifier-from-scratch-in-python-b38ef145fd90#:~:text=%20ID3%20Decision%20Tree%20Classifier%20from%20scratch%20in,wind%20blows%20from%20the%20Sout
This is what I'm talking about

2021-09-26 13:29 UTC, surjyaneeh commented
> it will be better if you made these links as more professional, it showing that you are organized
> just make a markdown like [ID3 Decision Tree Classifier from scratch in Python](https://towardsdatascience.com/id3-decision-tree-classifier-from-scratch-in-python-b38ef145fd90#:~:text=%20ID3%20Decision%20Tree%20Classifier%20from%20scratch%20in,wind%20blows%20from%20the%20South.%20If...%20More%20)

I have done the changes.

2021-09-27 05:44 UTC, prathimacode-hub requested changes
Changes to be done 👍 

In README.md, instead of getting directly into topic start from how this term is derived. 
In .ipynb, at the end provide a overall summary and final outcomes of the work you had done.

Kindly work on it. @surjyaneeh

2021-09-27 08:11 UTC, surjyaneeh commented
> Changes to be done 👍
> 
> In README.md, instead of getting directly into topic start from how this term is derived.
> In .ipynb, at the end provide a overall summary and final outcomes of the work you had done.
> 
> Kindly work on it. @surjyaneeh

I have done the changes.

2021-09-29 07:20 UTC, prathimacode-hub approved these changes
PR approved. 👍@surjyaneeh

2021-09-29 07:42 UTC, merged