Added OpenSource: 6.4 Process to submit a patch to linux kernel
girlscript/winter-of-contributing pull request #2858
Opened 2021-09-26 09:32 UTC by amitrakshar01

<hr>

## Description 📜

OpenSource: 6.4 Process to submit a patch to linux kernel #2271 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Open #Source

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

2021-09-26 09:34 UTC, amitrakshar01 commented
@ashish-patwal @Aryamanz29 @adityabisoi

2021-09-26 10:15 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +## Submitting First Patch
heading size should be consistent . Add ### here

2021-09-26 10:21 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +touch ~/.esmtprc<br>
Add all code/commands between console tags eg ```console <code> ```

2021-09-26 10:22 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +identity "my.email@gmail.com"<br>
add between console tags

2021-09-26 10:22 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +set sendmail="/usr/bin/esmtp"<br>
add between console tags

2021-09-26 10:24 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +[user]<br>
use console tag here too

2021-09-26 10:25 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +    cd git/kernels/staging/</i>
console tag and remove italics

2021-09-26 10:25 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +    git fetch origin<br>
remove italics and add code between console tags

2021-09-26 10:27 UTC, ashish-patwal requested changes
Please enclose code/console/commands between ```console    ``` tags and remove the italics tag added before the code

2021-09-26 12:25 UTC, amitrakshar01 commented
> Please enclose code/console/commands between `console ` tags and remove the italics tag added before the code

done

2021-09-26 12:26 UTC, amitrakshar01 commented
> > Please enclose code/console/commands between `console ` tags and remove the italics tag added before the code
> 
> done

Check merge

2021-09-26 14:00 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +Code<br><br>
I don't think there is need for this line here .

2021-09-26 14:01 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +Code<br><br>
I don't think there is a need for this line .

2021-09-26 14:01 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +Code<br><br>
remove this line also please

2021-09-26 14:02 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +Code<br><br>
remove this too

2021-09-26 14:03 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +Code<br><br>
no need for this line here

2021-09-26 14:06 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +starttls required```
triple backticks should be in the next line , otherwise the console window is not being rendered for this markdown

2021-09-26 14:07 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +    set edit_headers=yes```
please adjust the indent and make sure the console space is being rendered .

2021-09-26 14:09 UTC, ashish-patwal commented on Open_Source/OpenSource꞉  6.4 Process to submit a patch to linux kernel.md
> +    cd git/kernels/staging/```
do proper indent and make sure the console is being rendered .

2021-09-26 14:16 UTC, ashish-patwal requested changes
I think there are a lot of mistakes in your md file . many backticks have been misplaced which spills the console space over other lines . Please take a look at your md file after editing it . Make sure no code bleeding is taking place . Also please add the word console after the starting 3 backticks , which enables syntax highlighting for your code . Moreover you can remove the code\<br>\<br> lines as they are not particularly needed there .

2021-09-26 16:21 UTC, Aryamanz29 requested changes
@amitrakshar01 
- Update your fork repo
-  Put your `doc` inside `3.Share_Things_With_Community` directory
-  **Rename your doc** `3.8_Submit_Patch_To_Linux_kernel.md`

2021-09-27 05:49 UTC, amitrakshar01 commented
> @amitrakshar01
> 
> * Update your fork repo
> * Put your `doc` inside `3.Share_Things_With_Community` directory
> * **Rename your doc** `3.8_Submit_Patch_To_Linux_kernel.md`

Done check

2021-09-27 06:51 UTC, ashish-patwal commented
@amitrakshar01 can you please enable editing file permissions for the pr .

2021-09-27 07:15 UTC, amitrakshar01 commented
> @amitrakshar01 can you please enable editing file permissions for the pr .

It's already allowed editing

2021-09-27 08:39 UTC, ashish-patwal commented
No i can't see the option to edit file . Just for reference have you ticked the 'allow edits by maintainers' option .

2021-09-27 12:48 UTC, amitrakshar01 commented
> No i can't see the option to edit file . Just for reference have you ticked the 'allow edits by maintainers' option .
![edit1](https://user-images.githubusercontent.com/57900221/134910942-1a134f1b-294c-4bda-800b-ee435e1f88c8.png)
I have

2021-09-27 12:56 UTC, ashish-patwal commented
@Aryamanz29 i need to do some edits to the file . Is there any way that's possible since i am not a maintainer?

2021-09-27 17:20 UTC, Aryamanz29 commented
> @Aryamanz29 i need to do some edits to the file . Is there any way that's possible since i am not a maintainer?

@ashish-patwal  Just clone @amitrakshar01 forked repo into your local machine, Do changes, commit and push his `Opensource` branch then it will reflect in this PR :)

2021-09-28 13:36 UTC, amitrakshar01 commented
can anyone tell me when it will be merged?

2021-09-28 13:44 UTC, ashish-patwal commented
@amitrakshar01 i have made a PR to your fork of Gwoc correcting some changes . Please merge that fork . Then commit those changes to the PR you made for submitting linux kernel patch doc . We will then merge your PR .

2021-09-28 13:51 UTC, amitrakshar01 commented
> @amitrakshar01 i have made a PR to your fork of Gwoc correcting some changes . Please merge that fork . Then commit those changes to the PR you made for submitting linux kernel patch doc . We will then merge your PR .

done plz check

2021-09-28 15:19 UTC, ashish-patwal approved these changes
LGTM @Aryamanz29 .

2021-09-29 06:06 UTC, amitrakshar01 commented
> LGTM @Aryamanz29 .

@Aryamanz29

2021-09-29 16:36 UTC, Aryamanz29 approved these changes
Awesome work @amitrakshar01 
Thanks for contributing 🎉🎉

2021-09-29 16:37 UTC, merged