Android development with kotlin
girlscript/winter-of-contributing pull request #2864
Opened 2021-09-26 09:56 UTC by Parth-001-git

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [x] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-26 10:37 UTC, rahulsain commented
Attach some screenshots, make the code separate from the texts. Rename your file and its folder structure.

Check merged PR's for some example.

2021-09-26 15:01 UTC, Parth-001-git commented
@rahulsain Please review .

2021-09-26 15:36 UTC, rahulsain requested changes

2021-09-26 15:36 UTC, rahulsain commented on Chronometer in Android.md
> +'import android.os.Bundle;
enclose it in the code format

2021-09-26 15:36 UTC, rahulsain commented on Chronometer in Android.md
> +} '
till here

2021-09-26 15:36 UTC, rahulsain commented on Chronometer in Android.md
> +'<?xml version="1.0" encoding="utf-8"?>
code format start from here

2021-09-26 15:36 UTC, rahulsain commented on Chronometer in Android.md
> +</manifest>'
end here

2021-09-26 15:36 UTC, rahulsain commented on Chronometer in Android.md
> +'<?xml version="1.0" encoding="utf-8"?>
code format start here

2021-09-26 15:36 UTC, rahulsain commented on Chronometer in Android.md
> +</android.support.constraint.ConstraintLayout>'
end here

2021-09-27 14:13 UTC, Parth-001-git commented
@rahulsain  Please review.

2021-09-27 14:43 UTC, rahulsain commented
> Attach some screenshots, make the code separate from the texts. Rename your file and its folder structure.
> 
> Check merged PR's for some example.

Please do this before asking for review

2021-09-28 06:15 UTC, sitamadex11 commented
@Parth-001-git your documentation is not structured. Please try to give some spaces between codes and use proper heading and subheadings with bullets and numbering. please give some screenshots of your XML file and final output. Also, you can add a gif of your final output.

Also your change your file structure as supervisor mentioned.

2021-09-30 03:29 UTC, closed without merging