Frontend : HTML Style Attribute
girlscript/winter-of-contributing pull request #2871
Opened 2021-09-26 10:11 UTC by Ravinayak07

<hr>

## Description 📜

I have created a  documentation on HTML Style Attribute with coded examples and output for the syntax.
Fixes #844 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-26 15:21 UTC, iamsunil25 commented
/assign

2021-09-26 17:32 UTC, sifa123 requested changes
Explain inline style, internal stylesheet, and external stylesheet with examples.

2021-09-26 17:32 UTC, sifa123 commented on Web_Development/FrontEnd/HTML Style Attribute/HTML_Style_Attribute.md
> +### 2. ***Text-align*** : - This property sets the horizontal alignment fo the text of an HTML Element.
Fix the typo

2021-09-26 17:44 UTC, Ravinayak07 commented on Web_Development/FrontEnd/HTML Style Attribute/HTML_Style_Attribute.md
> +### 2. ***Text-align*** : - This property sets the horizontal alignment fo the text of an HTML Element.
Okay mam

2021-09-27 05:58 UTC, Ravinayak07 commented
> Explain inline style, internal stylesheet, and external stylesheet with examples.

@sifa123 I have pushed the required changes mentioned by you. Kindly please review it.

2021-09-28 05:15 UTC, sifa123 approved these changes

2021-09-28 05:16 UTC, merged

2021-09-28 06:57 UTC, Ravinayak07 commented
@sifa123 ma'am, since the PR is merged, should I close the issue now?

2021-09-28 07:17 UTC, sifa123 commented
> @sifa123 ma'am, since the PR is merged, should I close the issue now?

yeah close the issue

2021-09-28 08:01 UTC, Ravinayak07 commented
> > @sifa123 ma'am, since the PR is merged, should I close the issue now?
> 
> yeah close the issue
okay Ma'am. Thank you for your guidance.