C_CPP: Default Constructor
girlscript/winter-of-contributing pull request #2881
Opened 2021-09-26 10:51 UTC by 124015001

<hr>

## Description 📜

Explained about Default Constructor and also performed a program on the same.
Fixes #2577 
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-09-26 15:20 UTC, deeqakkk approved these changes

2021-09-27 07:54 UTC, joy-i commented
/assign

2021-09-27 08:02 UTC, 124015001 commented
@joy-i this is a pull request my friend. You can create a new issue and then assign it to yourself.

2021-09-27 10:02 UTC, apeksha235 requested changes
@124015001
- Please check your file path as it should be inside the OOPs in C++ directory 
- remove the html tags 
Amazing work though!

2021-09-27 11:57 UTC, closed without merging