Java 11.3: Varargs and Ambiguity #2219
girlscript/winter-of-contributing pull request #2914
Opened 2021-09-26 14:02 UTC by ishivamgupta9

<hr>

## Description 📜

I have created documentation on  Java 11.3: Varargs and Ambiguity.
Fixes #2219  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
![Screenshot (598)](https://user-images.githubusercontent.com/78858930/134811001-10cc4c5f-b601-4751-abf2-8fd313e2739f.png)

<hr>

2021-09-26 14:54 UTC, sumitaccess007 requested changes
@ishivamgupta9,

Please help to know below points -
1. Under Issue #2219, with PR #2914, Why are you submitting changes made on content related to Issue - #1106 
Here in this PR, you have also modified file 'Impact_of_Java_on_Internet.md', which is not part of this issue - 'Varargs and Ambiguity'.
Please clarify.

Please make sure that you only submit content related to particular topic on which Issue is created.

2021-09-26 14:57 UTC, sumitaccess007 requested changes

2021-09-26 14:57 UTC, sumitaccess007 commented on Java/Varargs/Varargs_And_Ambiguity/Varargs_And_Ambiguity.md
> +Now if the interface variable is us the class implementing the interfaces are confused which . This is the ambiguity problem in java.
@ishivamgupta9 

Also in next commit, improve this line as well.

2021-09-26 15:07 UTC, ishivamgupta9 commented
@sumitaccess007 I had not changed that other issue, only for looking for the reference I had opened that file but not changed anything you can check it with original content.

2021-09-26 15:20 UTC, closed without merging

2021-09-27 03:45 UTC, sumitaccess007 commented
@ishivamgupta9 - Verified it with original content. Below are the changes which are also part of this PR.

1. Number of files changed are two.
![image](https://user-images.githubusercontent.com/14336951/134841935-6287ee57-c9ec-4cfa-8e7e-e9efe6461d03.png)

2. Original Content -
![image](https://user-images.githubusercontent.com/14336951/134842156-53ba5bf5-0575-4ed3-843b-de2e7b62c38b.png)

3. Content in Your Repo - 
It is fine now, the lines are deleted.

You can submit the PR now.