[DSA Array 1.1.2 Task 1]: Reverse an Array
girlscript/winter-of-contributing pull request #2916
Opened 2021-09-26 14:12 UTC by NiharikaSngh

<hr>

## Description 📜
I have made a documentation for the Task 1 of this issue.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #110  

<hr>
## Type of change 📝

- [x] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [x] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] Android Dev #(Flutter)
- [x] Android Dev #(Java)
- [x] Android Dev #(Kotlin)
- [x] Backend Dev #(Java)
- [x] Backend Dev #(.NET)
- [x] Backend Dev #(PHP)
- [x] Backend Dev #(Python)
- [x] C/#CPP
- [x] Competitive #Programming
- [x] Cyber #Security
- [ ] DSA
- [x] Data#base
- [x] Datascience with #Python
- [x] Datascience with #R
- [x] Frontend Dev #HTML/CSS/JS
- [x] Frontend Dev #React/Angular/Vue
- [x] Go#lang
- [x] Interview #Prep
- [x] Java_#Domain
- [x] Java#Script
- [x] ME#RN
- [x] Machine #Learning
- [x] Open #Source
- [x] Python_#Domain
- [x] Ru#st
- [x] Statis#tics
- [x] UI/#UX

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-26 14:50 UTC, NiharikaSngh reviewed
The mentor is requested to merge only the latest commit named Create 1.1.2 Task 1 into the GWOC DSA directory.

2021-09-27 04:11 UTC, Muskan-creator requested changes
Use markdown to add code snippets ,organise the code Write problem statement first.
refer this to add:https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

2021-09-27 06:26 UTC, NiharikaSngh commented
@Muskan-creator How to convert to draft? Yes, this is still in progress and 2 more tasks to be completed. I know markdown and have used it. Besides, the problem statement is specified in the heading itself. I have given code output as a hyperlink as the image is bigger. Code is already organised. Plz merge my PR !

2021-09-27 07:43 UTC, get-satyam commented on DSA/1.1 Arrays/1.1.2 Task 1 #110.md
> +   //cout << endl;
Pls resolve this error at line 42

2021-09-28 11:24 UTC, merged