Java 11.3: Varargs and Ambiguity #2219
girlscript/winter-of-contributing pull request #2953
Opened 2021-09-26 15:58 UTC by ishivamgupta9

<hr>

## Description 📜

I have created documentation on  Java 11.3: Varargs and Ambiguity.
Fixes #2219  

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
![Screenshot (599)](https://user-images.githubusercontent.com/78858930/134815104-24a09008-ff25-42e0-8f09-e272e8b11d34.png)

<hr>

2021-09-27 04:11 UTC, sumitaccess007 requested changes
@ishivamgupta9 

The changes in this PR are fine now. Please check with below points -
1. Below line is not delivering any meaningful message, please try reading the sentence again and make corrections to this.
"Now if the interface variable uses the class implementing the interface it may confuse. This is the ambiguity problem in java."

2. Code Indentation is missing.
For the code snippet which you have provided as examples in Doc, make sure you indent them properly, for maximum code readability and quick understanding.

Feel free to ping in case of any confusions.

Thanks

2021-09-27 13:42 UTC, ishivamgupta9 commented
@sumitaccess007 

I have done the required changes could you please check it once.

2021-09-27 13:44 UTC, sumitaccess007 reviewed
@garvitraj 

Level-1 Review is fine for me.
I would request you to please have a final look for this PR.

Thanks

2021-09-27 16:29 UTC, AkMo3 requested changes
Also, add a small paragraph about the places where varargs can be added like constructor and give individual examples for them

2021-09-27 16:31 UTC, AkMo3 commented
> 
> 
> Also, add a small paragraph about the places where varargs can be added like constructor and give individual examples for them

My bad, it is not required here!

2021-09-27 16:40 UTC, AkMo3 requested changes

2021-09-27 16:40 UTC, AkMo3 commented on Java/Varargs/Varargs_And_Ambiguity/Varargs_And_Ambiguity.md
> +Now when we call the variable of interface(i.e carModelName in the below code) then the compiler will give us an error because it will get confused between the similar variables of the interface. Thi
This is not the ambiguity. Ambiguity arises in cases like
```java
void foo(int num1, int... num2) {}

void foo(int.... num1) {}
```

Also in cases like:
```java
class SomeClass {
    void foo(int... num) {}

    void foo(boolean... isTrue) {} 
}

public static void main(String[] args) {
    foo(); // ambiguous
}

2021-09-28 14:36 UTC, ishivamgupta9 commented
@AkMo3 

I have done some changes. Please have a look and let me know if something more is needed.

2021-09-28 15:30 UTC, merged