Issue: Leftmost Repeating Character
girlscript/winter-of-contributing pull request #2959
Opened 2021-09-26 16:11 UTC by AastikSharma05

<hr>

## Description 📜
Given a string, find the repeated character present first in the string.
Fixes # 2952

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Competitive Programming

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-09-26 16:12 UTC, AastikSharma05 commented
Please review my PR and let me know if any change is required.
Thanks for assigning me this issue :)

2021-09-26 18:00 UTC, diksha137 commented
/assign

2021-09-27 04:28 UTC, ravireddy07 requested changes
Please make suggested changes and make sure you preview the file and verify it from your side. @AastikSharma05

2021-09-27 04:28 UTC, ravireddy07 commented on Competitive_Programming/C++/String/Leftmost_Repeating_Character.md
> +Given a string, find the repeated character present first in the string.
Add a title as problem Statement

2021-09-27 04:28 UTC, ravireddy07 commented on Competitive_Programming/C++/String/Leftmost_Repeating_Character.md
> +Repeated Character Whose First Appearance is Leftmost
Add a title

2021-09-27 04:28 UTC, ravireddy07 commented on Competitive_Programming/C++/String/Leftmost_Repeating_Character.md
> +(mind that it will be g, not e.)
You can point it out in more better way

2021-09-27 04:28 UTC, ravireddy07 commented on Competitive_Programming/C++/String/Leftmost_Repeating_Character.md
> +}
seems like not everything is inserted into code. Always preview the `.md`.

2021-09-27 04:28 UTC, ravireddy07 commented on Competitive_Programming/C++/String/Leftmost_Repeating_Character.md
> +First Repeating character is g
highlight this

2021-09-27 04:28 UTC, ravireddy07 commented on Competitive_Programming/C++/String/Leftmost_Repeating_Character.md
> +Time Complexity : O(n). It does only one traversal of input string.
`It does only one traversal of input string.`
Add this sentance as a commit.

2021-09-27 07:42 UTC, AastikSharma05 commented
@ravireddy07 I have made the changes please check if anything else needs to be done.

2021-09-27 12:59 UTC, ravireddy07 requested changes
Refer this below images of you doc:

Image1: The header file is out of scope, use correct syntax of how to insert code in markdown.

![image1](https://user-images.githubusercontent.com/26524467/134912334-213451cc-5734-4631-9d1f-39db4d7a9194.png)

Image2: don't put everyting in one line.

![image2](https://user-images.githubusercontent.com/26524467/134912345-381666fc-2a5e-43dd-afe2-d74413d9f24a.png)

2021-09-27 12:59 UTC, ravireddy07 commented on Competitive_Programming/C++/String/Leftmost_Repeating_Character.md
> +### Repeated Character Whose First Appearance is Leftmost (Strings)
Keep title with `##` or `#`

2021-09-27 13:00 UTC, ravireddy07 commented
@AastikSharma05  Please preview the `markdown` before you make a push.

2021-09-27 14:43 UTC, AastikSharma05 commented
@ravireddy07 I have modified as advised by you. Please check if it is as per your expectations.

2021-09-27 14:50 UTC, ravireddy07 reviewed
Great work @AastikSharma05 ,
update this tiny change and we're good to merge.

2021-09-27 14:50 UTC, ravireddy07 commented on Competitive_Programming/C++/String/Leftmost_Repeating_Character.md
> +It does only one traversal of input string.
Add this line as comment, as it refering.

like:

```
Time Complexity : O(n).   #It does only one traversal of input string.
Auxiliary Space : O(1)
```

2021-09-27 14:50 UTC, ravireddy07 commented on Competitive_Programming/C++/String/Leftmost_Repeating_Character.md
> +It does only one traversal of input string.
here as well

2021-09-27 15:13 UTC, ravireddy07 approved these changes

2021-09-30 16:23 UTC, merged