FrontEnd: Basics of Internet - Hosting and Name Servers
girlscript/winter-of-contributing pull request #2963
Opened 2021-09-26 16:36 UTC by Yashesvinee

<hr>

## Description 📜

Added documentation on Hosting and Name Servers
Fixes #2357 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-26 16:39 UTC, Yashesvinee commented
@2024-SANDHYA please review this PR

2021-09-27 08:12 UTC, praveenscience requested changes
Please repeat all the changes over the whole content. Use a program like Typora to do this.

2021-09-27 08:12 UTC, praveenscience commented on Web_Development/FrontEnd/Hosting_name_servers/documentation.md
> +----
No need of so many HRs.

2021-09-27 08:12 UTC, praveenscience commented on Web_Development/FrontEnd/Hosting_name_servers/documentation.md
> +
Remove Blank Lines.

2021-09-27 08:12 UTC, praveenscience commented on Web_Development/FrontEnd/Hosting_name_servers/documentation.md
> +
Remove Blank Lines.

2021-09-27 08:12 UTC, praveenscience commented on Web_Development/FrontEnd/Hosting_name_servers/documentation.md
> +   Hosting, in simple words, is a service through which resources are provided to an individual or organization for the maintenance and storage of websites or other related services. Hosting is somet
Add space after heading.

2021-09-27 08:12 UTC, praveenscience commented on Web_Development/FrontEnd/Hosting_name_servers/documentation.md
> +   Hosting, in simple words, is a service through which resources are provided to an individual or organization for the maintenance and storage of websites or other related services. Hosting is somet
Do not have more spaces in front of text.

2021-09-27 08:12 UTC, praveenscience commented on Web_Development/FrontEnd/Hosting_name_servers/documentation.md
> +   A Name Server is a server component of the DNS that returns the IP Address of a given Domain name. It handles queries regarding the location of the domain name’s various services.
Do not have more spaces in front of text.

2021-09-27 08:12 UTC, praveenscience commented on Web_Development/FrontEnd/Hosting_name_servers/documentation.md
> + ----
No need of so many HRs.

2021-09-27 08:12 UTC, praveenscience commented on Web_Development/FrontEnd/Hosting_name_servers/documentation.md
> + ## Web Hosting
Add space after heading.

2021-09-27 08:12 UTC, praveenscience commented on Web_Development/FrontEnd/Hosting_name_servers/documentation.md
> + - Decide the type of website you want to build, it could be static or dynamic. Static websites show the same content to all users while dynamic websites show contents that involve the user's activit
Add space before list.

2021-09-27 08:39 UTC, Yashesvinee commented
@praveenscience sir I made the necessary changes
Is it okay now?

2021-09-27 10:22 UTC, 2024-SANDHYA commented
> 
> 
> @2024-SANDHYA please review this PR

There already exists a PR for this, so you either change this to audio or video as a doc for the same topic will not be accepted, as informed in the discord itself.

2021-09-27 10:32 UTC, Yashesvinee commented
@2024-SANDHYA there is a PR for domain name basics and DNS
Could you please tell me PR number for Hosting and name servers
I am sorry for asking but I just want to confirm

2021-09-30 08:21 UTC, Yashesvinee commented
@2024-SANDHYA Please let me know if this is a valid PR 
I took up this issue after checking if there were similar ones and there weren't any

2021-09-30 12:45 UTC, 2024-SANDHYA commented
> 
> 
> @2024-SANDHYA Please let me know if this is a valid PR I took up this issue after checking if there were similar ones and there weren't any

Check it for yourself !

2021-10-31 06:11 UTC, closed without merging