Branch2
girlscript/winter-of-contributing pull request #3024
Opened 2021-09-26 20:05 UTC by ritika728

<hr>

## Description 📜

I have added information about exit() and _Exit() function in C++ with proper examples and explanation in document form  # <2548> 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-09-26 20:22 UTC, ritika728 commented
@Shivani0701 please review my PR.

2021-09-27 05:40 UTC, vasu-1 requested changes
Good Content !!! @ritika728 
Just Require Some Markdown Formatting !!!
Do this changes And also some others are required then do them also !

2021-09-27 05:40 UTC, vasu-1 commented on C_CPP/Fundamentals/Functions & Recursion and its types/exit()&_Exit()Functions.md
> +***
```suggestion
## SYNTAX:  
    exit(exit_code);  
- where exit code is defining exit status.  
For example:
```c++
exit(0)
```
***
```

2021-09-27 05:40 UTC, vasu-1 commented on C_CPP/Fundamentals/Functions & Recursion and its types/exit()&_Exit()Functions.md
> +exit(1) indicates an error and that's why the program is terminating.
```suggestion
- _Exit(0) indicates a clean exit without any error.  
- _Exit(1) indicates an error and that's why the program is terminating.  
```

2021-09-27 05:40 UTC, vasu-1 commented on C_CPP/Fundamentals/Functions & Recursion and its types/exit()&_Exit()Functions.md
> +#include<iostream>
```suggestion
```c++
#include<iostream>
```

2021-09-27 05:40 UTC, vasu-1 commented on C_CPP/Fundamentals/Functions & Recursion and its types/exit()&_Exit()Functions.md
> +#include<iostream>
```suggestion
```c++
#include<iostream>
```

2021-09-27 05:40 UTC, vasu-1 commented on C_CPP/Fundamentals/Functions & Recursion and its types/exit()&_Exit()Functions.md
> +#include <iostream>
```suggestion
```c++
#include <iostream>
```

2021-09-27 05:40 UTC, vasu-1 commented on C_CPP/Fundamentals/Functions & Recursion and its types/exit()&_Exit()Functions.md
> +exit(1) indicates an error and that's why the program is terminating.
```suggestion
- exit(0) indicates a clean exit without any error.  
- exit(1) indicates an error and that's why the program is terminating.  
```

2021-09-27 08:30 UTC, ritika728 commented
@vasu-1 I have made the required changes. Please review!

2021-09-27 09:55 UTC, apeksha235 approved these changes
@Suvraneel please merge this

2021-09-27 15:28 UTC, merged