sorting documentation
girlscript/winter-of-contributing pull request #3103
Opened 2021-09-27 10:15 UTC by VandanaKumari18

<hr>

## detailed description 📜
> in md file 
> 1.what is sorting.
> 2.different kinds of sorting
> 3. need to sorting 
>6.explaination of code .

> in cpp file
> 1.code of bubble sort
> 2.code of insertion sort
> 3.comments explanation 
> i have explained using pictures and gif for making reading enjoyable.
Fixes # <> 
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <1643> 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/#CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-27 15:06 UTC, deeqakkk requested changes

2021-09-27 15:06 UTC, deeqakkk commented on C_CPP/Algorithmic Approaches/Sorting/sorting.md
> +## what is sorting?
Vandana, Some very basic things like sentence starts with a "Capital alphabet".
Update this in all your headings.

2021-09-27 15:06 UTC, deeqakkk commented on C_CPP/Algorithmic Approaches/Sorting/sorting.md
> +sorting basically means to arrange the data items in increasing or decreasing manner according to the relationship  among the data's.
I believe you can write a really nice definition better than this.

2021-09-27 15:06 UTC, deeqakkk commented on C_CPP/Algorithmic Approaches/Sorting/sorting.md
> +> - **Bubble sort** - It is a simple and basic algorithm used for sorting.This is a comparison-based algorithm in which each pair of adjacent elements is compared and the elements are swapped if they
Instead of defining here, add a brief description just above your code.

Also, add relevant comments in your code to make it easily understandable.

2021-10-04 08:26 UTC, apeksha235 requested changes
@VandanaKumari18 .. Please do these changes

2021-10-04 08:26 UTC, apeksha235 commented on C_CPP/Algorithmic Approaches/Sorting/sorting.md
> +> BUBBLE SORT can not be used for large data items.Moreover it is not the fastest sorting method.If we do not optimise the code it will run even after the sorting.This is the reason why insertion sor
Try writing these in points to make it more readable.

2021-10-04 08:26 UTC, apeksha235 commented on C_CPP/Algorithmic Approaches/Sorting/sorting.md
> +## C CODE FOR BUBBLE SORT USING FUNCTION
You need to add comments every time you add a code

2021-10-04 08:36 UTC, apeksha235 commented
@VandanaKumari18 Issues on bubble sort and insertion sort are already present [here](https://github.com/astha2412/winter-of-contributing/blob/C_CPP/C_CPP/Algorithmic%20Approaches/Sorting/BubbleSort.md) and [here](https://github.com/astha2412/winter-of-contributing/blob/C_CPP/C_CPP/Algorithmic%20Approaches/Sorting/InsertionSort.md)
 
Please check the folders before creating an issue. 
@Suvraneel

2021-10-04 20:35 UTC, closed without merging