Java
girlscript/winter-of-contributing pull request #3289
Opened 2021-09-28 05:04 UTC by amitx007

<hr>

## Description 📜
Explained about what is interface and how to implement it .
 # <2626> 

<hr>

## Type of change 📝

- [ ] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ ] Java_Domain

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-28 05:05 UTC, amitx007 commented
@AkMo3 plz see the asset folder so that i can add the relative path to the doc.

2021-09-28 15:45 UTC, AkMo3 commented
@nandini7637 Please do the initial review

2021-09-29 11:58 UTC, nandini7637 requested changes
If you took references from any website please mention them. Else it's good!

2021-09-29 13:02 UTC, amitx007 commented
@nandini7637 no actually i have just seen the which version of java the extra features were added thats it .

2021-09-29 13:14 UTC, amitx007 commented
@nandini7637 now i have added all the relative paths to the documentation . So plz check it !

2021-10-02 03:23 UTC, AkMo3 requested changes

2021-10-02 03:23 UTC, AkMo3 commented on Java/Interfaces/Defining_And_Implementation_Of_Interfaces/Defining_and_implementation_of_interface.md
> +here *smartphone* is the interface's name and *frontcamera*,*rearcamera* etc are the methods without the implemenatation (without body).
`implemenatation` -> `implementation`

2021-10-02 03:23 UTC, AkMo3 commented on Java/Interfaces/Defining_And_Implementation_Of_Interfaces/Defining_and_implementation_of_interface.md
> +# Defining Interface and it's Implementation
`it's` -> `its`

2021-10-02 03:23 UTC, AkMo3 commented on Java/Interfaces/Defining_And_Implementation_Of_Interfaces/Defining_and_implementation_of_interface.md
> +An interface is quite similar to some other class, but it has got some method that have no body or in other words no implementation and some of the constant values. So in general interface is just a
`other class` -> `other classes`
`some method` -> `some methods`
`class which has static constant ` -> `class that has static constants `

2021-10-02 03:23 UTC, AkMo3 commented on Java/Interfaces/Defining_And_Implementation_Of_Interfaces/Defining_and_implementation_of_interface.md
> +- All the **method** that are declared in interface are **public and abstract** by default .
`method` -> `methods`

2021-10-02 03:24 UTC, AkMo3 commented
@amitx007 Please remember to check the spell and grammar of your content through any online tool

2021-10-02 15:19 UTC, amitx007 commented
@AkMo3 checked all the grammar and spelling and writing convention ! plz do the review !

2021-10-03 16:10 UTC, AkMo3 approved these changes

2021-10-03 16:10 UTC, merged