Data Science with Python : Convolution Neural Networks
girlscript/winter-of-contributing pull request #3393
Opened 2021-09-28 16:19 UTC by samridhikapoor

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <362> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [x] Datascience with Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-28 20:08 UTC, Pushpit07 commented on Datascience_With_Python/Deep Learning/Tutorials/Data Science with Python  Convolution Neural Networks.md
> +[![Convolutional neural networks](https://www.dropbox.com/s/wb387q7kil6z0uy/Capture.PNG?dl=0&raw=1)](https://drive.google.com/file/d/10fw-kCYAauCNG20OAA2DUqHk1rUE9GuM/view "Cnvolutional Neural Networ
Please correct the typo in `Convolutional`

2021-09-29 07:30 UTC, prathimacode-hub requested changes
Kindly create a project folder of Convolutional Neural Networks under "/Datascience_with_Python/Deep Learning/Videos/" repo
Add README.md file with more details on the topic

Kindly work on it. @samridhikapoor

2021-09-29 10:17 UTC, samridhikapoor commented
Okay Ma'am I am working on it.

2021-09-29 11:02 UTC, samridhikapoor commented
@prathimacode-hub I have made the desired changes. Kindly review the same
Thanks

2021-09-29 11:17 UTC, prathimacode-hub requested changes
Add advantages, applications and conclusion of the topic at the end.
And also file name, kindly change it to README.md @samridhikapoor

2021-10-03 15:05 UTC, samridhikapoor commented
> Add advantages, applications and conclusion of the topic at the end. And also file name, kindly change it to README.md @samridhikapoor

I have made the desired changes. Kindly review the same
Thanks

2021-10-03 16:26 UTC, prathimacode-hub commented
All changes not done. @samridhikapoor

2021-10-03 16:37 UTC, samridhikapoor commented
> All changes not done. @samridhikapoor

Ma'am, Please check it now.

2021-10-04 05:00 UTC, prathimacode-hub approved these changes
PR approved. Great efforts✨🙌@samridhikapoor

2021-10-04 05:02 UTC, merged