Added 6.5_Ansible.md
girlscript/winter-of-contributing pull request #3397
Opened 2021-09-28 16:29 UTC by anjali-kundliya05

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [x] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-28 16:34 UTC, Aryamanz29 requested changes

2021-09-28 16:34 UTC, Aryamanz29 commented on Open_Source/6.Popular_Projects/6.5_Ansible.md
> +**What is Ansible?**
Make them heading instead of bold , Use this `##  Heading_Here`

2021-09-28 16:34 UTC, Aryamanz29 commented on Open_Source/6.Popular_Projects/6.5_Ansible.md
> +**Why Ansible?**
Same here, Change this with heading

2021-09-28 16:34 UTC, Aryamanz29 commented on Open_Source/6.Popular_Projects/6.5_Ansible.md
> +**What Ansible Does?**
Same here

2021-09-28 16:34 UTC, Aryamanz29 commented on Open_Source/6.Popular_Projects/6.5_Ansible.md
> +**How Ansible works?**
Same

2021-09-28 16:34 UTC, Aryamanz29 commented on Open_Source/6.Popular_Projects/6.5_Ansible.md
> +**What are the Advantages of Ansible?**
Same

2021-09-28 16:34 UTC, Aryamanz29 commented on Open_Source/6.Popular_Projects/6.5_Ansible.md
> +**References-**
Same

2021-09-28 16:41 UTC, anjali-kundliya05 commented
I have done required changes, please have a look!

2021-09-29 16:19 UTC, Aryamanz29 approved these changes
Awesome work @anjali-kundliya05 
Thanks for contributing 🎉🎉

2021-09-29 16:21 UTC, merged

2021-09-29 16:33 UTC, anjali-kundliya05 commented
Thank You for merging my PR :)