Simple ATM Bank in C
girlscript/winter-of-contributing pull request #3399
Opened 2021-09-28 16:34 UTC by ikavyajain

<hr>

## Description 📜

Simple ATM Bank in C
A simple program for beginners to choose at the initial stage to make a project in C! 👍
The program will be a menu driven program which will allow the user to-

- [x] Check the balance
- [x] Money deposited
- [x] Money withdraw

Hope you understand the simple code and code it in you system! 💯
Enjoyyy coding! 👍

Fixes #3159

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

![GAME1](https://user-images.githubusercontent.com/89743157/134963892-93d8c4db-61af-4a3d-9670-0acfd39b97d9.jpeg)
![GAME2](https://user-images.githubusercontent.com/89743157/134963862-09986012-fe6c-42ab-a95e-56bca6b97abd.jpeg)
![GAME3](https://user-images.githubusercontent.com/89743157/134963763-d0debd15-bab3-457b-8d13-56b05b701071.jpeg)
![GAME4](https://user-images.githubusercontent.com/89743157/134963725-f2f53427-a736-44df-86ef-4ba69d27227c.jpeg)

<hr>

2021-09-30 18:48 UTC, vasu-1 requested changes
Good Effort @ikavyajain 

But your code is having some bug !
**when i try to give deposite two time than it is giving me an error**

try to figure it out  !!!

2021-09-30 18:50 UTC, vasu-1 commented
Also Remove all this line ` system("CLS"); ` from your code !!!

2021-09-30 18:51 UTC, ikavyajain commented
Just try to run on turbo!
Because i have coded on it and it was kinda successful!

2021-09-30 18:56 UTC, vasu-1 commented
> Just try to run on turbo! Because i have coded on it and it was kinda successful!

Suggestion : Use Modern Compilers like **ming-gw**

2021-09-30 18:59 UTC, vasu-1 commented
> Just try to run on turbo! Because i have coded on it and it was kinda successful!

I think yes!!
It is working fine

2021-09-30 19:18 UTC, vasu-1 requested changes
Okk please do these changes
- use some markdown
- explain code in the comments
- remove those all spaces from the code and put apropriate spaces.

2021-09-30 19:18 UTC, vasu-1 commented on C_CPP/Competitive Programming/Simple_ATM_Bank_in_C.md
> +                                                      bool again = true;
```suggestion
```c++
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <math.h>

void login();
void mainMenu();
void checkBalance(float balance);
float moneyDeposit(float balance);
float moneyWithdraw(float balance);
void menuExit();
void errorMessage();

int main()
{
   int option;
   float balance = 0.00;
   int choose;
   bool again = true;
```

do this to your all code !

2021-09-30 19:18 UTC, vasu-1 commented on C_CPP/Competitive Programming/Simple_ATM_Bank_in_C.md
> +
```suggestion
{;
   printf("+++!!!You selected invalid number!!!+++\n");
}
```
                                                      
```

2021-10-02 10:07 UTC, ikavyajain commented
Made the required changes! Do check

2021-10-02 11:12 UTC, Suvraneel commented
@vasu-1 Review

@ikavyajain  Btw turbo-C & other DOS based compilers are now obsolete
So, graphics.h & similar headers are deprecated...
Try to use ming-gw64... gcc etc...

2021-10-02 11:13 UTC, ikavyajain commented
Okay i’ll take care of that from now on!

2021-10-02 16:47 UTC, vasu-1 requested changes
@ikavyajain 
do like this !!!

2021-10-02 16:47 UTC, vasu-1 commented on C_CPP/Competitive Programming/Simple_ATM_Bank_in_C.md
> +
```suggestion
```cpp
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <math.h>
void login();
void mainMenu();
void checkBalance(float balance);    // To check balance in the account
float moneyDeposit(float balance);   // To check the amount deposited in the account
float moneyWithdraw(float balance);  // To check the amount withdrawed from the account
void menuExit();                     // To quit the menu
void errorMessage();
int main()
{
  int option;
  float balance = 0.00;
  int choose;
  bool again = true;
  while (again)
  {
    mainMenu();
    printf("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-\n");
    printf("Your Selection:\t");
    scanf("%d", &option);
    switch (option)
    {
      case 1:
      checkBalance(balance);           	                    
      break;
      case 2:
      balance = moneyDeposit(balance);            	                                                                                                                                   break;
      case 3:           	                                       
      balance = moneyWithdraw(balance);
      break;
      case 4:            	                                        
      menuExit();
      return 0;
      default:
      errorMessage();
      break;
    }

    printf("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n");
    printf("Would you like to do another transaction:\n");
    printf("< 1 > Yes\n");
    printf("< 2 > No\n");
    scanf("%d", &choose);

    if (choose == 2)
    {
      again = false;
      menuExit();
    }
  }
  return 0;
}
                                                  
                                                  
void mainMenu()
{
  printf("**********Welcome to ATM Bank***********\n\n");
  printf("****Please choose one of the options below****\n\n");
  printf("< 1 >  Check Balance\n");
  printf("< 2 >  Deposit\n");
  printf("< 3 >  Withdraw\n");
  printf("< 4 >  Exit\n\n");
}
                                                  
                                                  
//Main Menu
void checkBalance(float balance)
{
  printf("You Choose to See your Balance\n");
  printf("\n\n****Your Available Balance is:   $%.2f\n\n", balance);
}
                                                  
                                                  
//Check Balance
float moneyDeposit(float balance) 
{
  float deposit;
  printf("You choose to Deposit a money\n");
  printf("Your Balance is: $%.2f\n\n", balance);
  printf("****Enter your amount to Deposit\n");
  scanf("%f", &deposit);
  balance += deposit;
  printf("\n****Your New Balance is:   $%.2f\n\n", balance);

  return balance;
}
                                                  
                                                  
//money deposit
float moneyWithdraw(float balance) 
{
  float withdraw;
  bool back = true;
  printf("You choose to Withdraw a money\n");
  printf("Your Balance is: $%.2f\n\n", balance);
  while (back) 
  {
    printf("Enter your amount to withdraw:\n");
    scanf("%f", &withdraw);
    if(withdraw < balance)
    {
      back = false;
      balance -= withdraw;
      printf("\nYour withdrawing money is:  $%.2f\n", withdraw);
      printf("****Your New Balance is:   $%.2f\n\n", balance);
    }
    else  
    {
      printf("+++You don't have enough money+++\n");
      printf("Please contact to your Bank Customer Services\n");
      printf("****Your Balance is:   $%.2f\n\n", balance);
    }
  }
  return balance;
}

//money withdraw
void menuExit() 
{
  printf("--------------Take your receipt!!!------------------\n");
  printf("-----Thank you for using ATM Banking Machine!!!-----\n");
}

//exit menu
void errorMessage() 
{
  printf("+++!!!You selected invalid number!!!+++\n");
}

```
```

2021-10-02 16:47 UTC, vasu-1 commented on C_CPP/Competitive Programming/Simple_ATM_Bank_in_C.md
> +
```suggestion
```cpp
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <math.h>
void login();
void mainMenu();
void checkBalance(float balance);    // To check balance in the account
float moneyDeposit(float balance);   // To check the amount deposited in the account
float moneyWithdraw(float balance);  // To check the amount withdrawed from the account
void menuExit();                     // To quit the menu
void errorMessage();
int main()
{
  int option;
  float balance = 0.00;
  int choose;
  bool again = true;
  while (again)
  {
    mainMenu();
    printf("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-\n");
    printf("Your Selection:\t");
    scanf("%d", &option);
    switch (option)
    {
      case 1:
      checkBalance(balance);           	                    
      break;
      case 2:
      balance = moneyDeposit(balance);
      break;
      case 3:           	                                       
      balance = moneyWithdraw(balance);
      break;
      case 4:            	                                        
      menuExit();
      return 0;
      default:
      errorMessage();
      break;
    }

    printf("=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=\n");
    printf("Would you like to do another transaction:\n");
    printf("< 1 > Yes\n");
    printf("< 2 > No\n");
    scanf("%d", &choose);

    if (choose == 2)
    {
      again = false;
      menuExit();
    }
  }
  return 0;
}
                                                  
                                                  
void mainMenu()
{
  printf("**********Welcome to ATM Bank***********\n\n");
  printf("****Please choose one of the options below****\n\n");
  printf("< 1 >  Check Balance\n");
  printf("< 2 >  Deposit\n");
  printf("< 3 >  Withdraw\n");
  printf("< 4 >  Exit\n\n");
}
                                                  
                                                  
//Main Menu
void checkBalance(float balance)
{
  printf("You Choose to See your Balance\n");
  printf("\n\n****Your Available Balance is:   $%.2f\n\n", balance);
}
                                                  
                                                  
//Check Balance
float moneyDeposit(float balance) 
{
  float deposit;
  printf("You choose to Deposit a money\n");
  printf("Your Balance is: $%.2f\n\n", balance);
  printf("****Enter your amount to Deposit\n");
  scanf("%f", &deposit);
  balance += deposit;
  printf("\n****Your New Balance is:   $%.2f\n\n", balance);

  return balance;
}
                                                  
                                                  
//money deposit
float moneyWithdraw(float balance) 
{
  float withdraw;
  bool back = true;
  printf("You choose to Withdraw a money\n");
  printf("Your Balance is: $%.2f\n\n", balance);
  while (back) 
  {
    printf("Enter your amount to withdraw:\n");
    scanf("%f", &withdraw);
    if(withdraw < balance)
    {
      back = false;
      balance -= withdraw;
      printf("\nYour withdrawing money is:  $%.2f\n", withdraw);
      printf("****Your New Balance is:   $%.2f\n\n", balance);
    }
    else  
    {
      printf("+++You don't have enough money+++\n");
      printf("Please contact to your Bank Customer Services\n");
      printf("****Your Balance is:   $%.2f\n\n", balance);
    }
  }
  return balance;
}

//money withdraw
void menuExit() 
{
  printf("--------------Take your receipt!!!------------------\n");
  printf("-----Thank you for using ATM Banking Machine!!!-----\n");
}

//exit menu
void errorMessage() 
{
  printf("+++!!!You selected invalid number!!!+++\n");
}

```
```

2021-10-04 10:13 UTC, ikavyajain commented
Changes are made properly, this time! 
Hope this looks much better now! :)

2021-10-04 10:46 UTC, vasu-1 approved these changes
Approved ⭐✨

Good to go for merge @Suvraneel

2021-10-04 12:14 UTC, Suvraneel commented
@ikavyajain  LGTM

2021-10-04 12:14 UTC, merged