HTML LIST
girlscript/winter-of-contributing pull request #3403
Opened 2021-09-28 16:49 UTC by samipak458

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [X] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-29 05:09 UTC, Anup0099 commented
@samipak458 Please assign this issue to me

2021-09-29 19:20 UTC, praveenscience requested changes
Please fix the changes.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +
No need of blank spaces.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +Question: What is List in HTML ?
Add a heading.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +Question: What is List in HTML ?
Remove space before `?`.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +
No need of extra line space.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +2) Unordered List
Make them proper paragraph and not text.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +
Remove empty space.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +Ordered List:
Make it heading.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +Ordered List:
Leave a space after heading.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +In ordered list orders matter. An ordered list starts with the <ol> tag. Each list item starts with the <li> tag and end with </li>. After all items added in list then we end ordered list with </ol>.
Make all tags inline codes.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +</ol>
Code fence it with syntax highlighting for HTML.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +Syntax:
Make it a heading.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +
Remove empty space.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +In unordered list order doesn't matter. An unordered list starts with the <ul> tag. Each list item starts with the <li> tag and end with </li>. After all items added in list then we end ordered list
Make all tags inline codes.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +Unordered List:
Make it heading.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +Unordered List:
Leave space after heading.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +
Remove blank lines.

2021-09-29 19:20 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +Reference Link: https://www.w3schools.com/html/html_lists.asp
Wrong place to refer. Never go for W3Schools.

2021-09-30 10:58 UTC, praveenscience requested changes
Just two.

2021-09-30 10:58 UTC, praveenscience commented on Web_Development/FrontEnd/HTML_LIST.txt
> +</html>
Code fence it with syntax highlighting for HTML.

2021-09-30 16:32 UTC, praveenscience approved these changes
👍

2021-10-02 14:16 UTC, kashishahuja2002 requested changes
Add output ss for ordered and unordered lists.
Also add content for dl.

2021-10-02 14:16 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML_LIST.txt
> +**Answer:** There are two types of list; ordered List and unordered List.
There is a dl also, don't just add incomplete information, add dl also.

2021-10-03 07:00 UTC, kashishahuja2002 approved these changes

2021-10-03 08:41 UTC, kashishahuja2002 requested changes
Remove the .txt file.

2021-10-03 08:41 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML_LIST.md
> +##HTML LIST AND TYPES OF LIST
The hashtags should not be visible in the preview. Change that.

2021-10-03 08:41 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML_LIST.md
> +**Answer:** A number of items or information noted in order form or in bullet points is called "List".
Add an empty line before this line.

2021-10-03 08:41 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML_LIST.md
> +**Answer:** There are three types of list; ordered list, unordered list and description list.
Add an empty line before this line.

2021-10-03 08:41 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML_LIST.md
> +###Ordered List
The hashtags should not be visible in the preview. Change that.

2021-10-03 08:41 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML_LIST.md
> +![ ](https://drive.google.com/file/d/1_QYCFdOvE4mLsNa8ut4dhqRf1vyVnoi8/view?usp=sharing)
The image is not visible in the preview. Check that.

2021-10-03 08:41 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML_LIST.md
> +###Unordered List
The hashtags should not be visible in the preview. Change that.

2021-10-03 08:41 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML_LIST.md
> +![ ](https://drive.google.com/file/d/1CBDvZN4eWQzI2ClpSC5xs9ETSQwq1axL/view?usp=sharing)
The image is not visible in the preview. Check that.

2021-10-03 08:41 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML_LIST.md
> +###Description List
The hashtags should not be visible in the preview. Change that.

2021-10-03 08:41 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML_LIST.md
> +![ ](https://drive.google.com/file/d/1gdigEJk6sra5B55KGSrvwvYKpfo-jOD9/view)
The image is not visible in the preview. Check that.

2021-10-03 10:16 UTC, kashishahuja2002 requested changes
Don't include tabs and space below in the output image

2021-10-03 13:38 UTC, kashishahuja2002 approved these changes
Good to go. @praveenscience

2021-10-05 16:24 UTC, merged