Function in Javascript
girlscript/winter-of-contributing pull request #3424
Opened 2021-09-28 18:21 UTC by geetika005

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #3228  

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-29 18:44 UTC, geetika005 commented
@praveenscience @code-reaper08  Please review my pr.

2021-09-30 15:54 UTC, RuchikaSuryawanshi7 commented
/assign

2021-09-30 15:58 UTC, geetika005 commented
@RuchikaSuryawanshi7  this is a pr request you can not assign it to yourself 
Unassign yourself please

2021-09-30 18:06 UTC, RuchikaSuryawanshi7 commented
@praveenscience  could you please review my pull request.

2021-09-30 18:15 UTC, geetika005 commented
> @praveenscience could you please review my pull request.



> @praveenscience could you please review my pull request.

Why are you posting it here ?
This pr belongs to me

2021-10-02 12:52 UTC, geetika005 commented
@praveenscience @code-reaper08 please review my pr it's been 4 days .

2021-10-02 16:40 UTC, code-reaper08 requested changes
Looks like this is already in the repository [here](https://github.com/girlscript/winter-of-contributing/tree/Frontend_Web_Development_HTML_CSS_JS/Web_Development/Javascript/1.Functions_And_Scope) @geetika005
And also you need to attribute the sources, I think you are inspired from https://www.hhutzler.de/blog/javascript-tackling-this-object-and-nested-functions-by-samples/

2021-10-02 16:53 UTC, geetika005 commented
@code-reaper08  sir my documentation is quite different from the one in scope and functions ,only the function definition ,syntax of function and parameter part is repeated. If i remove them then is it be okay to get merged.

2021-10-02 17:33 UTC, code-reaper08 commented
> @code-reaper08 sir my documentation is quite different from the one in scope and functions ,only the function definition ,syntax of function and parameter part is repeated. If i remove them then is it be okay to get merged.

Yeah it's quite different, but I would say, if you could make it more interesting, like a audio( Podcast ) contribution. It will be super good!

What you say @2024-SANDHYA?

2021-10-02 17:47 UTC, geetika005 commented
Can i add my documentation as an extention to scopes and function file @code-reaper08

2021-10-02 17:51 UTC, geetika005 commented
Can i add all the extra topics in that file

2021-10-03 07:46 UTC, 2024-SANDHYA requested changes
No need to write this :

![image](https://user-images.githubusercontent.com/75671152/135744907-48d67b90-4e3a-4f08-8051-8decd51ea81b.png)

Add the reference link Please & yes that can be done @code-reaper08

2021-10-03 09:44 UTC, geetika005 commented
Updated the file with reference link @code-reaper08 @2024-SANDHYA

2021-10-03 18:00 UTC, code-reaper08 requested changes
I've left some reviews, please look into it :-)

2021-10-03 18:00 UTC, code-reaper08 commented on Web_Development/Javascript/Javascript_Functions.md
> +```
This part is totally rephrased from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions

Please attribute it too

2021-10-03 18:14 UTC, geetika005 commented
Updated the file with the changes sir @code-reaper08

2021-10-03 18:24 UTC, code-reaper08 approved these changes

2021-10-03 18:24 UTC, merged