[JS] Topic: Regular Expressions
girlscript/winter-of-contributing pull request #3441
Opened 2021-09-28 19:59 UTC by subhendudash02

<hr>

## Description 📜
Added the documentation regarding the regular expressions in JavaScript in the form of a markdown file.
Added the images in a separate sub-folder.

Fixes #2142
<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [x] JavaScript

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-09-29 04:18 UTC, sushovanb02 approved these changes

2021-09-29 07:13 UTC, s4-2 commented
@subhendudash02 Very well formated and detailed information. Well done:)

2021-09-29 07:13 UTC, s4-2 approved these changes

2021-09-29 07:29 UTC, subhendudash02 commented
> @subhendudash02 Very well formated and detailed information. Well done:)

😊Glad to know @s4-2 !! Thank you so much for the review!

2021-10-02 13:50 UTC, paramsiddharth requested changes

2021-10-02 13:50 UTC, paramsiddharth commented on JavaScript/Topics/Regular_Expressions/README.md
> +```
Do this instead of that.

2021-10-02 13:50 UTC, paramsiddharth approved these changes

2021-10-03 18:10 UTC, dakshsethi approved these changes
Looks good to me!! 🔥🔥🔥

2021-10-05 18:39 UTC, paramsiddharth approved these changes

2021-10-05 18:39 UTC, merged