[ Golang ] 8. Introduction to DOC Concurrency
girlscript/winter-of-contributing pull request #3442
Opened 2021-09-28 20:21 UTC by 1anshu-56

<hr>

## Description 📜

Introduction to DOC Concurrency:-
A small description about-
- Goroutines and how to create Goroutine.
- Channels
- Buffered Channels
- Range and Close
- Select
- Default Selection
- What is Mutex?
Fixes #1334 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Go#lang

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-01 14:46 UTC, amino19 requested changes
@1anshu-56: Thanks for your contribution. Some minor changes that need to be fixed here are as follows:-
- In general documentation, we use `:-` to help the reader to read the following statements, pl use `:-` instead of `:`.
- Use `<br />` tag instead of `<br>` somewhere, make sure to not use this HTML tag at topics/subtopics.
- Pl copy the contents in google docs, & use Grammarly to rectify minor mistakes.

Thanks! :slightly_smiling_face: 
I hope you'll make it very soon!

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +### 🎉 Advantages of Goroutines.
```suggestion
### 🎉 Advantages of Goroutines

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +### Example:
```suggestion
### Example 1:-

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +#### 🌈 Output:
```suggestion
#### 🌈 Output:-

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +#### 🌈 Output:<br>
```suggestion
#### 🌈 Output:-


```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +*So, to executes a Goroutine properly, we need to make some changes in our program as shown in the below code*
```suggestion
*So, to executes a Goroutine properly, we need to make some changes in our program as shown in the below code:-*

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +# 🗂 Channels.<br>
```suggestion
# 🗂 Channels


```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +#### 🌈 Output:<br>
```suggestion
#### 🌈 Output:-<br>

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +### Example:
```suggestion
### Example:-

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +#### 🌈 Output:
```suggestion
#### 🌈 Output:-

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +# 🗂 Buffered Channel in Golang.<br>
```suggestion
# 🗂 Buffered Channel in Golang


```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +#### A small code example to create a buffered channel.
```suggestion
#### A small code example to create a buffered channel


```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +### ⚙️ Syntax:
```suggestion
### ⚙️ Syntax:-

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +#### 🌈 Output:
```suggestion
#### 🌈 Output:-

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +# 🗂 Range and Close.<br>
```suggestion
# 🗂 Range and Close


```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +**🔖 Note:**
```suggestion
**🔖 Note:-**

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +### Let's see a example:
```suggestion
### Let's see an example-:

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +#### 🌈 Output:<br>
```suggestion
#### 🌈 Output:-


```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +#### Let's dive right into some code for better understanding.
```suggestion
#### Let's dive right into some code for better understanding:-

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +#### 🌈 Output:<br>
```suggestion
#### 🌈 Output:-<br>

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +# 🗂 Default Selection.<br>
```suggestion
# 🗂 Default Selection


```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +### A small code example:
```suggestion
### A small code example:-

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +In the program above, the `process` function in line no.8 sleeps for 10500 milliseconds and then writes `process successful` to the `ch` channel.
```suggestion
In the program above, the `process` function in line no. 8 sleeps for 10500 milliseconds and then, writes `process successful` to the `ch` channel. 

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +#### 🌈 Output:<br>
```suggestion
#### 🌈 Output:-<br>

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +# 🗂 Go Mutex.<br>
```suggestion
# 🗂 Go Mutex


```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +### Now let's understand how Mutex works:
```suggestion
### Now let's understand how Mutex works:-

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +#### 🌈 Output:<br>
```suggestion
#### 🌈 Output:-<br>

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +# 💫 Some Tips and Tricks:
```suggestion
# 💫 Some Tips and Tricks:-

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +## Alternate Ways to Import Packages:<br>
```suggestion
## Alternate Ways to Import Packages:-

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +### How to see what packages my app imports:
```suggestion
### How to see what packages my app imports:-

```

2021-10-01 14:46 UTC, amino19 commented on Golang/8 Concurrency/README.md
> +#### Here is an example with the clirescue refactoring example:
```suggestion
#### Here is an example with the clirescue refactoring example:-

```

2021-10-02 12:32 UTC, merged

2021-10-02 12:33 UTC, amino19 commented
@1anshu-56: I am already done with changes. Thanks for your contributions! :partying_face:

2021-10-03 07:37 UTC, 1anshu-56 commented
Thank You so much @amino19 ✨ for your guidance and mentoring me.