Ugly Numbers (Using DP Algorithmic Approach)
girlscript/winter-of-contributing pull request #3699
Opened 2021-09-30 13:32 UTC by swatigupta121

<hr>

## Description 📜

I have added a well commented code for solving Ugly Numbers using dynamic approach. I also specified the output, time complexity and space complexity at the end of program. 
Fixes #963

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials) 

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-30 17:54 UTC, vasu-1 requested changes
Good job @swatigupta121 
Please use markdown instead of cpp documentation !!

2021-10-01 11:48 UTC, swatigupta121 commented
@vasu-1 
I have performed the required changes. Please review it once again.

2021-10-01 11:54 UTC, vasu-1 commented
Hey @swatigupta121 
I am not saying like this..
Please see this md file[Link](https://github.com/girlscript/winter-of-contributing/blob/C_CPP/C_CPP/Data%20Structures/Linked%20List/Singly_Linked_List_In_C.md) 

Change the code accordingly..

2021-10-03 16:26 UTC, swatigupta121 commented
Hello @vasu-1 
I tried making the changes. Please check it once. And sorry for the inconvenience caused as I am new to open source and still exploring it.

2021-10-03 18:33 UTC, vasu-1 approved these changes
Nicee @su5

2021-10-03 18:34 UTC, vasu-1 commented
@Suvraneel  review and merge .

2021-10-03 20:57 UTC, Suvraneel requested changes

2021-10-03 20:57 UTC, Suvraneel commented on C_CPP/Algorithmic Approaches/Dynamic/readme.md
> +- Ugly Numbers [https://github.com/swatigupta121/winter-of-contributing/blob/swatigupta121-patch-1/C_CPP/Algorithmic%20Approaches/Dynamic/Ugly_Number.md]
Use relative link...
From gwoc repo...
Not your fork

2021-10-04 10:49 UTC, vasu-1 approved these changes
@Suvraneel  👉👈I think we can merge this !

2021-10-04 12:15 UTC, Suvraneel commented
@swatigupta121  Awesome ❤️  LGTM :octocat:  💯

2021-10-04 12:15 UTC, merged