Java
girlscript/winter-of-contributing pull request #3718
Opened 2021-09-30 15:17 UTC by astharaj300

<hr>

## Description 📜

Here I have explained about Catching Exceptions.
Fixes #2873 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_#Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-30 15:17 UTC, astharaj300 commented
@AkMo3 please review my pr.

2021-10-01 00:03 UTC, AkMo3 requested changes

2021-10-01 00:03 UTC, AkMo3 commented on Java/Exception Handling/Catching_Exceptions/Catching_Exception.md
> +When the exception occurs in a method, the process of creating the exception object and handling it to the runtime environment is said to be **throwing the exception**.
`handling` -> `handing`

2021-10-01 00:03 UTC, AkMo3 commented on Java/Exception Handling/Catching_Exceptions/Catching_Exception.md
> +/ by zero occured, kindly check your code
`occured` -> `occurred`

2021-10-01 00:03 UTC, AkMo3 commented on Java/Exception Handling/Catching_Exceptions/Catching_Exception.md
> +Any code that is thrown out of a method must be specified as such by a *throws* clause. It is used in the signature of method to indicate that this method might throw one of the listed type exception
`thse` -> `these`

2021-10-01 04:19 UTC, astharaj300 commented
@AkMo3 I have made the changes, please check it once

2021-10-01 18:45 UTC, garvitraj commented
@AkMo3 things are resolved.
GTG

2021-10-01 18:45 UTC, merged