Constructors, Destructors and Assignment operators
girlscript/winter-of-contributing pull request #3719
Opened 2021-09-30 15:23 UTC by elixir14082002

<hr>

## Added documentation and video 📜

I have added documentation and video on Constructors, Destructors, and assignment operators.
#3035

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-30 15:24 UTC, elixir14082002 commented
@Suvraneel I have resolved the assigned issue. Please Verify!

2021-09-30 16:18 UTC, kashishahuja2002 requested changes
Add the topic of multiple constructors. 
Add some more content to Assignment operators.

2021-10-01 06:47 UTC, kashishahuja2002 requested changes

2021-10-01 06:47 UTC, kashishahuja2002 commented on C_CPP/C++ 14/Constructor_Destructor.md
> +[Video on Constructor and Destructor by elixir14082002](https://drive.google.com/file/d/15bq7ltmc7QIpRmBUtRmRSo15lXi7e2VX/view?usp=sharing)
Change this line to "Video on Constructor and Destructor".

2021-10-01 14:27 UTC, elixir14082002 commented
@kashishahuja2002 I have made the changes. Kindly review!
@Suvraneel

2021-10-01 17:13 UTC, kashishahuja2002 requested changes
The issue also has a topic of assignment operator. 
Cover that topic also in detail. Don't just add it for sake.

2021-10-01 17:14 UTC, kashishahuja2002 requested changes
The topic of multiple constructors should be before destructor.

2021-10-02 01:39 UTC, closed without merging