Heap Sort
girlscript/winter-of-contributing pull request #3765
Opened 2021-09-30 20:04 UTC by rajraii

<hr>

## Description 📜

This documentation is about Heap sort covering all aspect of  heap sort algorithm # <3690> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [X] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-30 20:17 UTC, apeksha235 commented
@rajraii 
Add a file.
![image](https://user-images.githubusercontent.com/84583787/135524365-5dfcc88a-e2db-4b86-9c10-4175e8625cdb.png)

2021-10-01 06:13 UTC, rajraii commented
> @rajraii 
> Add a file.
> ![image](https://user-images.githubusercontent.com/84583787/135524365-5dfcc88a-e2db-4b86-9c10-4175e8625cdb.png)
> 

@apeksha235 done, can you verify it

2021-10-02 04:05 UTC, vasu-1 commented
> > @rajraii
> > Add a file.
> > ![image](https://user-images.githubusercontent.com/84583787/135524365-5dfcc88a-e2db-4b86-9c10-4175e8625cdb.png)
> 
> @apeksha235 done, can you verify it

No it is not there !

2021-10-02 04:10 UTC, vasu-1 commented
**Add file and do commit !**
I can't see any commit after the suggestion of apeksha !!!

2021-10-02 04:10 UTC, vasu-1 commented
Also don't forget to push

2021-10-02 18:09 UTC, rajraii commented
@vasu-1 okay done please verify it

2021-10-02 19:23 UTC, vasu-1 requested changes
Just add this `c++` in your code..
Then your pr will be good to go for merge

2021-10-02 19:23 UTC, vasu-1 commented on C_CPP/Algorithmic Approaches/Sorting/HeapSort.md
> +using namespace std;
```suggestion
## CODE FOR HEAP SORT 
```c++
#include <iostream>
using namespace std;
```

2021-10-02 19:24 UTC, rajraii commented
@vasu-1 okay ill do that asap

2021-10-02 19:30 UTC, vasu-1 commented
> @vasu-1 okay ill do that asap

Please sorry for this !!!

2021-10-02 19:30 UTC, rajraii commented
@vasu-1 please verify it

2021-10-02 19:33 UTC, vasu-1 commented
#3690 
- see suvraneel sir has closed your Pr

2021-10-03 12:40 UTC, closed without merging