Reverse the Singly Linked List
girlscript/winter-of-contributing pull request #3769
Opened 2021-09-30 23:43 UTC by VARUN-K-BANSAL

<hr>

## Description 📜

I have added documentation for reversal of Singly Linked List along with it's code in C. I have also added appropriate readme's and fixed the directory structure of Singly_Linked_List_In_C.md.
Fixes #3704 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-01 08:54 UTC, VARUN-K-BANSAL commented
@vasu-1 @Suvraneel could you please review my pr.

2021-10-02 15:51 UTC, Suvraneel requested changes

2021-10-02 15:51 UTC, Suvraneel commented on C_CPP/Data Structures/Linked List/Singly Linked List (Normal Linked List)/readme.md
> +- [Reverese the Singly Linked List](Reverse_Singly_Linked_List_In_C.md)
```suggestion
- [Reverse the Singly Linked List](Reverse_Singly_Linked_List_In_C.md)
```

2021-10-02 15:56 UTC, Suvraneel commented
@VARUN-K-BANSAL  LGTM ❤️

2021-10-02 15:56 UTC, merged