Type Casting
girlscript/winter-of-contributing pull request #3788
Opened 2021-10-01 06:29 UTC by ketkikaushik

<hr>

## Description 📜

This documentation contains detailed explanation of  Type Casting in Java and its types with examples.
Fixes # 1533 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Java_Domain

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-01 07:39 UTC, jaigora24 commented
/assign

2021-10-01 07:40 UTC, jaigora24 commented
/assign document

2021-10-01 08:36 UTC, jaigora24 commented
https://github.com/girlscript/winter-of-contributing/pull/3811 Review my PR

2021-10-01 13:55 UTC, ketkikaushik commented
/assign

2021-10-02 02:43 UTC, AkMo3 commented
@jaigora24 It is a PR, not an issue that can be assigned.

2021-10-03 16:14 UTC, sakshamlamba109 requested changes
@garvitraj I've mentioned the changes

2021-10-03 16:14 UTC, sakshamlamba109 commented on Java/Primitive Data Type/Casting/Type_Casting.ipynb
> +        "In the above example, we are assigning 0 (an integer value) to 'a' (an integer variable) and that works fine.\n",
In the example the contributor has int a=`7`, but in this line, the contributor has written "we are assigning  `0`"

2021-10-03 16:14 UTC, sakshamlamba109 commented on Java/Primitive Data Type/Casting/Type_Casting.ipynb
> +        "*   We must *downcast* a variable *manuall*.\n",
spelling error

2021-10-03 16:14 UTC, sakshamlamba109 commented on Java/Primitive Data Type/Casting/Type_Casting.ipynb
> +        "In Implicit type casting/conversion the data type gets automatically converted to another data type by the compiler. It is also known as Widening type casting as it converts lower data type
please mention lower priority data type instead of lower data type

2021-10-03 16:17 UTC, sakshamlamba109 requested changes
@AkMo3 please look into it

2021-10-03 16:25 UTC, AkMo3 requested changes

2021-10-03 16:25 UTC, AkMo3 commented on Java/Primitive Data Type/Casting/Type_Casting.ipynb
> +        "*   We must *downcast* a variable *manuall*.\n",
`manuall` -> `manual`

2021-10-03 16:25 UTC, AkMo3 commented on Java/Primitive Data Type/Casting/Type_Casting.ipynb
> +        "1) Implicict type casting\n",
`Implicict` -> `Implicit`

2021-10-03 16:25 UTC, AkMo3 commented on Java/Primitive Data Type/Casting/Type_Casting.ipynb
> +        "In Explicit casting, the coversion does not happen automatically. It should be coverted by a programmer when converting from a wider to a narrower data type. It is also known as Narrowing ty
`coversion` -> `conversion`
`coverted` -> `converted`

2021-10-03 16:25 UTC, AkMo3 commented on Java/Primitive Data Type/Casting/Type_Casting.ipynb
> +        "Referances: [javatpoint](https://www.javatpoint.com/type-casting-in-java)\n",
`Referances` -> `References`

2021-10-03 16:26 UTC, AkMo3 commented
@ketkikaushik Please do all the changes suggested by Saksham and Me

2021-10-03 16:34 UTC, ketkikaushik commented
> @ketkikaushik Please do all the changes suggested by Saksham and Me

ok I'll work on that.

2021-10-03 17:16 UTC, ketkikaushik commented
@AkMo3 I've made all the changes that you requested. Please review it.

2021-10-05 08:33 UTC, AkMo3 approved these changes

2021-10-05 08:34 UTC, merged