Introduction to Operating System
girlscript/winter-of-contributing pull request #3841
Opened 2021-10-01 13:48 UTC by am-dusky

<hr>

## Description 📜
Toipcs covered:
1. What is operating system?
2. Need of Opearting system
3. Examples and types of Opearting system
4. Functions of Opearting system
5. Do we always need a manager
6. Mulitasking and Multiprogramming

Fixes #2386

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/#CPP
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-10-02 13:19 UTC, Suvraneel commented
@kashishahuja2002 @gunjan-g

2021-10-02 14:05 UTC, kashishahuja2002 approved these changes
Combine both the files in one. 
Great content.

2021-10-02 14:25 UTC, Suvraneel requested changes

2021-10-02 14:25 UTC, Suvraneel commented on C_CPP/Operating System Concepts/Introduction_to_OS.md
> +<li>Network Oprating System</li>
Use 
- Item1
- Item2
`- Item3`

Use as less HTML as you can in md...

2021-10-02 14:26 UTC, Suvraneel commented
@am-dusky Always prrofread you doc before submission

2021-10-02 15:42 UTC, am-dusky commented
@Suvraneel @kashishahuja2002 I have corrected the mistakes.

2021-10-03 07:11 UTC, kashishahuja2002 commented
Ok, @Suvraneel

2021-10-03 10:11 UTC, kashishahuja2002 approved these changes

2021-10-04 06:49 UTC, Suvraneel requested changes
Update readme of OS directory

2021-10-04 12:11 UTC, merged

2021-10-04 12:31 UTC, am-dusky commented
@Suvraneel thanku 🤩🎊💖

2021-10-05 05:12 UTC, kashishahuja2002 commented
Great work @am-dusky ❤️