ML 1.8: A\B Testing (V) #1115
girlscript/winter-of-contributing pull request #3848
Opened 2021-10-01 14:19 UTC by karma659

<hr>

## Description 📜

Added a video of A\B testing  with code
Fixes # <#1115> 

<hr>

## Type of change 📝

- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [ ] Machine #Learning

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-01 14:48 UTC, abhisheks008 requested changes

2021-10-01 14:48 UTC, abhisheks008 commented on Machine_Learning/Statistics_for_Machine_Learning/ML 1.8: A\B Testing (V).md
> +[A/B testing Video](https://drive.google.com/file/d/1g3TtxZc80Qosk0YPz9HUdJ6E9pcRgAgv/view?usp=sharing)
@karma659 Please add the thumbnail like others have done. Please do the needful changes.

2021-10-03 06:36 UTC, karma659 reviewed
added thumbnail

2021-10-03 08:01 UTC, Isha307 approved these changes

2021-10-03 08:01 UTC, merged