Competitive Programming: Python stacks and queues (Documentation) #3683
girlscript/winter-of-contributing pull request #3853
Opened 2021-10-01 15:11 UTC by sangeetasingh17

<hr>

## Description 📜

Added readme.md, stacks and queues implementation in python in separate folders.
Fixes #3683 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Competitive #Programming

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

2021-10-01 17:57 UTC, ravireddy07 requested changes
Hey @sangeetasingh17 ,
seems like you've added multiple files.

1. _only file for each contribution is allowed._
2. In documentation, Either `markdown` or `google colab` an be acceptable. you can choose either of one.
3. You add your supporting snippet of codes in between of your doc.

please make changes which mentioned above.

2021-10-01 18:10 UTC, sangeetasingh17 commented
sure! I'll make the changes

2021-10-01 18:56 UTC, sangeetasingh17 commented
I have done the changes. Could you please review it? @ravireddy07

2021-10-02 08:52 UTC, ravireddy07 commented
I still able to see 13 files @sangeetasingh17 

_only one documentation file is allowed for each contribution_

2021-10-02 10:28 UTC, sangeetasingh17 commented
Done! @ravireddy07 is it ok now?

2021-10-02 14:32 UTC, ravireddy07 requested changes
Great work @sangeetasingh17,

just add those images via link and we're good to go

2021-10-02 14:32 UTC, ravireddy07 commented on Competitive_Programming/Python/Stacks & Queues/README.md
> +<img src="assets/stack.png"  style="max-width: 80%; height: auto; background:white"/>
add images via link instead of attaching. You can upload it to any issue and you'll get the link. And remove image from assets.

2021-10-02 14:32 UTC, ravireddy07 commented on Competitive_Programming/Python/Stacks & Queues/README.md
> +<img src="assets/queue.png"  style="max-width: 80%; height: auto; background:white"/>
add images via link instead of attaching...

2021-10-02 15:31 UTC, sangeetasingh17 commented
Done with the changes @ravireddy07

2021-10-02 15:44 UTC, ravireddy07 approved these changes
Well done @sangeetasingh17

2021-10-02 15:46 UTC, ravireddy07 commented
Please update same in sheet(PR tracksheet). @sangeetasingh17

2021-10-02 16:33 UTC, sangeetasingh17 commented
@ravireddy07 I have updated the PR tracksheet

2021-10-05 07:16 UTC, merged