Constructors, Destructors and Assignment Operators
girlscript/winter-of-contributing pull request #3931
Opened 2021-10-02 02:49 UTC by elixir14082002

<hr>

## Description 📜

Included documentation and video on Constructors, Destructors, and Assignment Operators.
#3035

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-02 02:52 UTC, elixir14082002 commented
@Suvraneel @kashishahuja2002 I have made the requested changes in this PR

2021-10-02 05:58 UTC, gunjan-g requested changes
@elixir14082002 Please move your file Constructor_Destructor in the Constructor-Destructor folder only instead of C++ 14
and add index line along with relative link in readme properly, you haven't added that

2021-10-02 06:17 UTC, gunjan-g commented
@elixir14082002 this topic is already there in repo, you can just make a pr of the video part if you want and that too on a separate issue, if it's not been taken
Ps. Please check the issues and branch C/CPP before working on any topic

2021-10-02 06:21 UTC, elixir14082002 commented
@gunjan-g The topic is a little different and I asked the supervisors before starting my work. I have removed it from C++14.

2021-10-02 07:28 UTC, gunjan-g commented
> @gunjan-g The topic is a little different and I asked the supervisors before starting my work. I have removed it from C++14.

Constructors and destructors are there, we can't repeat the topic. Let me know how this is different from the content present. You can add assignment operators but you have assigned an issue opened by someone else, so you have to open a different issue for that too

2021-10-02 09:33 UTC, elixir14082002 commented
> > @gunjan-g The topic is a little different and I asked the supervisors before starting my work. I have removed it from C++14.
> 
> Constructors and destructors are there, we can't repeat the topic. Let me know how this is different from the content present. You can add assignment operators but you have assigned an issue opened by someone else, so you have to open a different issue for that too

Actually, I was told that I can work on this particular issue, I only need to change the information a little, and also there is the topic of the assignment operators. That's why I created the PR. This was an open issue and no one was working on it. @gunjan-g

2021-10-02 13:13 UTC, kashishahuja2002 requested changes
Why are there 3 files?
Combine the content in one.

2021-10-02 13:13 UTC, kashishahuja2002 commented on C_CPP/Constructor & Destructor/Constructor_Destructor.md
> +    ```
Remove this line.

2021-10-02 13:13 UTC, kashishahuja2002 commented on C_CPP/Constructor & Destructor/readme.md
> +
Remove this file.

2021-10-03 11:48 UTC, anisha-01-phoenix commented
Looks Good!...Can be Merged!

2021-10-03 13:52 UTC, kashishahuja2002 commented
This topic already exists in doc mode
so you either need to change it to video mode or work on a  new issue.

2021-10-03 13:55 UTC, kashishahuja2002 commented
> Looks Good!...Can be Merged!

Ma'am, You're a contributor, not a mentor/supervisor. You're approval is neither required nor appreciated here. I would suggest you to leave it upto mentors and supervisors, and kindly focus on contributing. :)

2021-10-03 14:03 UTC, gunjan-g commented
> Looks Good!...Can be Merged!

So sweet of you, handling the work of a mentor and contributor at the same time. Honestly, we were waiting for your approval only XD

2021-10-04 14:04 UTC, elixir14082002 commented
I am closing this PR due to several issues.

2021-10-04 14:04 UTC, closed without merging