Documentation on bitwise operator
girlscript/winter-of-contributing pull request #3969
Opened 2021-10-02 09:18 UTC by Akshat-2002-coder

<hr>

documentation on bitwise operators and some useful results based on it.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <3359> 

<hr>

## Type of change 📝

- [] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ ] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-10-02 12:08 UTC, ipsitagoel commented
@Akshat-2002-coder This topic has already been covered previously and added to the repository: https://github.com/girlscript/winter-of-contributing/blob/C_CPP/C_CPP/Fundamentals/Operators%20%26%20Expressions/operators-%26-expressions-in-C.md

- You can either explore further on Bitwise operators such as Bitmasking etc.
- Or you can contribute to some other topic.

2021-10-02 13:39 UTC, Akshat-2002-coder commented
@ipsitagoel  mam can u plz tell from where I can choose topics which are not taken up by someone else

2021-10-02 13:46 UTC, ipsitagoel commented
@Akshat-2002-coder You can refer to the C/CPP roadmap and check if content related to that particular topic has already been added to the repo or if an issue/PR has been raised.
Link to the roadmap: https://github.com/girlscript/winter-of-contributing/tree/C_CPP/C_CPP

2021-10-02 14:54 UTC, kashishahuja2002 requested changes
Try adding some code snippets.

2021-10-02 14:54 UTC, kashishahuja2002 commented on C_CPP/Bitwise operators/bitwise.md
> +- **~ (bitwise NOT)** :- It is also a unary operator which is used to complement the bits, means if it is '0' it becomes '1' and vice versa.
It hasn't been bold.

2021-10-03 14:58 UTC, Akshat-2002-coder commented
@Saviour1001  sir can u plz review my pull request now

2021-10-03 17:17 UTC, Saviour1001 commented
As suggested by the discussion above the explanation of bitwise operator exists [here](https://github.com/girlscript/winter-of-contributing/blob/C_CPP/C_CPP/Fundamentals/Operators%20%26%20Expressions/operators-%26-expressions-in-C.md). I liked the extra points you added in the end. So add a file named "Bitwise Operator in detail" in this folder and you can add your content which is already not present. 
Add your content in this [folder](https://github.com/girlscript/winter-of-contributing/tree/C_CPP/C_CPP/Fundamentals/Operators%20%26%20Expressions)

2021-10-03 17:28 UTC, Akshat-2002-coder commented
@Saviour1001  sir can u plz review it now😅.

2021-10-03 17:33 UTC, Saviour1001 commented
![image](https://user-images.githubusercontent.com/71517788/135764905-742ad1bc-4c61-4788-9c0b-5c6dae3b25c2.png)
You added an empty file, remove the previous file as well. Double check your content before pinging.

2021-10-03 17:47 UTC, Akshat-2002-coder commented
@Saviour1001  sorry for inconvenience now I have double checked myself.

2021-10-03 17:50 UTC, merged