Git and Bash
girlscript/winter-of-contributing pull request #4014
Opened 2021-10-02 14:24 UTC by prachi610

<hr>

## Description 📜
I have added the documentation of Git and Bash. In which I have explain about Git and Bash and added some commands .

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ x] I have performed a self-review of my own code or work.
- [ x] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [ x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-02 15:59 UTC, Pooj123-A commented
**/assign**

2021-10-02 18:47 UTC, praveenscience commented
@Pooj123-A Since you asked for it, can you please send me a report by tomorrow afternoon as now it's assigned to you. Please let me know your review comments.

2021-10-02 18:57 UTC, Pooj123-A commented
Praveen I don't understand that what do you mean by report.
Do I need to complete it by tomorrow ?

On Sun, Oct 3, 2021, 00:17 Praveen Kumar Purushothaman <
***@***.***> wrote:

> @Pooj123-A <https://github.com/Pooj123-A> Since you asked for it, can you
> please send me a report by tomorrow afternoon as now it's assigned to you.
> Please let me know your review comments.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/girlscript/winter-of-contributing/pull/4014#issuecomment-932802245>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARN7AVU7MRWJS3FPKAU4SFLUE5HUJANCNFSM5FGOTQYQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-05 10:19 UTC, ipsitagoel reviewed
@prachi610 Good job!
@2024-SANDHYA You can have a look and merge this!

2021-10-05 10:21 UTC, 2024-SANDHYA commented
> 
> 
> @prachi610 Good job! @2024-SANDHYA You can have a look and merge this!

Sure!

2021-10-05 10:23 UTC, 2024-SANDHYA requested changes
Nice! Just one change @prachi610, remove your name from the bottom & remove this too, please. The rest looks great!

![image](https://user-images.githubusercontent.com/75671152/136005694-7780dee3-1eb9-467e-9397-8d7df6a54a04.png)

2021-10-05 10:40 UTC, prachi610 commented
@2024-SANDHYA Done!

2021-10-05 10:41 UTC, kashishahuja2002 requested changes

2021-10-05 10:41 UTC, kashishahuja2002 commented on Web_Development/Javascript/Git and Bash/readme.md
> +### Contributed By [Prachi Singh]("https://github.com/prachi610/)
Remove this line.

2021-10-05 10:42 UTC, kashishahuja2002 commented
Great work @prachi610

2021-10-05 10:44 UTC, prachi610 commented on Web_Development/Javascript/Git and Bash/readme.md
> +### Contributed By [Prachi Singh]("https://github.com/prachi610/)
Check it now.

2021-10-05 10:46 UTC, prachi610 commented
> Great work @prachi610

Thanks!

2021-10-05 10:50 UTC, 2024-SANDHYA approved these changes

2021-10-05 10:50 UTC, merged