Added links to roadmap
girlscript/winter-of-contributing pull request #4049
Opened 2021-10-02 17:17 UTC by rajmadhu0406

<hr>

## Description 📜

Added links to roadmap by editing the readme.md file.
Fixes #4042 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [x] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-02 17:53 UTC, Aayushi-Mittal requested changes
@rajmadhu0406 Please do the requested changes. Rest looks good.

2021-10-02 17:53 UTC, Aayushi-Mittal commented on Web_Development/FrontEnd/ReadMe.md
> +- [DNS & Working of DNS?](./https://github.com/girlscript/winter-of-contributing/blob/Frontend_Web_Development_HTML_CSS_JS/Web_Development/FrontEnd/DNS%20and%20Working%20of%20DNS.md)
Hey, Please add all the links in one format.
For eg: `[DNS & Working of DNS](./DNS%20and%20Working%20of%20%DNS.md)`

Use `%20` for spaces.

2021-10-02 17:53 UTC, Aayushi-Mittal commented on Web_Development/FrontEnd/ReadMe.md
> +- [Classes and Id’s](https://github.com/girlscript/winter-of-contributing/tree/Frontend_Web_Development_HTML_CSS_JS/Web_Development/FrontEnd/HTML_Class%20and%20Id)
Same comments here.

2021-10-02 17:53 UTC, Aayushi-Mittal commented on Web_Development/FrontEnd/ReadMe.md
> +- [Flex properties](https://github.com/girlscript/winter-of-contributing/tree/Frontend_Web_Development_HTML_CSS_JS/Web_Development/FrontEnd/CSS_Flexbox)
Same comments here.

2021-10-02 17:53 UTC, Aayushi-Mittal commented on Web_Development/FrontEnd/ReadMe.md
> +- [CSS buttons styling](./https://github.com/girlscript/winter-of-contributing/tree/Frontend_Web_Development_HTML_CSS_JS/Web_Development/FrontEnd/CSS%20Button%20Styling)
same comments here.

2021-10-02 18:00 UTC, rajmadhu0406 commented on Web_Development/FrontEnd/ReadMe.md
> +- [CSS buttons styling](./https://github.com/girlscript/winter-of-contributing/tree/Frontend_Web_Development_HTML_CSS_JS/Web_Development/FrontEnd/CSS%20Button%20Styling)
okay

2021-10-02 18:11 UTC, rajmadhu0406 commented
@Aayushi-Mittal  please take a look, I have done the required.

2021-10-03 07:36 UTC, Aayushi-Mittal approved these changes
Perfect! Please merge this PR @Ayan-thecodeking.

2021-10-04 16:16 UTC, SauravMukherjee44 approved these changes

2021-10-04 17:26 UTC, heet-kumar approved these changes
LGTM !! perfect 👍 lets wait for the supervisor approval .

2021-10-04 18:01 UTC, merged