Added Shell Sort in C++
girlscript/winter-of-contributing pull request #4067
Opened 2021-10-02 18:44 UTC by aniket-24

<hr>

## Description 📜

Added ShellSort.md in C_CPP\Algorithmic Approaches\Sorting folder
Fixes #4066

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-10-02 18:46 UTC, aniket-24 commented
Please review this...
And merge this PR under Hacktoberfest-accepted Label!

2021-10-02 19:42 UTC, vasu-1 requested changes
- Plagiarisms Detected
- Use your own words don't copy from other resources.
- remove some markdown formatting errors

2021-10-02 19:42 UTC, vasu-1 commented on C_CPP/Algorithmic Approaches/Sorting/ShellSort.md
> +
```suggestion

- SET FLAG = 1, GAP_SIZE = N
- Repeat Steps 3 to 6 while FLAG = 1 OR GAP_SIZE > 1
- SET FLAG = 0
- SET GAP_SIZE = (GAP_SIZE + 1) / 25)
- Repeat Step 6 for I = 0 to I < (N -GAP_SIZE)
- IF Arr[I + GAP_SIZE] > Arr[I]
     SWAP Arr[I + GAP_SIZE], Arr[I]
     SET FLAG = 0
- END

```

2021-10-02 19:42 UTC, vasu-1 commented on C_CPP/Algorithmic Approaches/Sorting/ShellSort.md
> +#include <iostream>
```suggestion

```c++
// Shell Sort in C++ programming

#include <iostream>
```

2021-10-02 19:42 UTC, vasu-1 commented on C_CPP/Algorithmic Approaches/Sorting/ShellSort.md
> +  No
do markdown formatting here !

2021-10-02 20:09 UTC, aniket-24 commented on C_CPP/Algorithmic Approaches/Sorting/ShellSort.md
> +  No
okay!

2021-10-02 20:09 UTC, aniket-24 commented
Now is it okay? @vasu-1

2021-10-03 15:52 UTC, vasu-1 commented
Good @aniket-24 
Good to go for merge @Suvraneel

2021-10-03 15:56 UTC, aniket-24 commented
Can you merge this PR under Hacktoberfest-accepted Label!

2021-10-03 15:57 UTC, Saviour1001 commented
@aniket-24 it gets counted under Hacktoberfest without any labels. Merging this right now. Ping me on Discord if it didn't get counted.

2021-10-03 15:57 UTC, merged