Introduction_to_Html_Audio
girlscript/winter-of-contributing pull request #4076
Opened 2021-10-02 20:23 UTC by I-ArchanaDash

<hr>

## Description 📜
This Audio gives an Introduction to HTML 
Fixes  #225

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-03 06:58 UTC, kashishahuja2002 requested changes
Remove the second file.

2021-10-03 06:58 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/Introduction_to_Html/Audio.md
> +## Introduction to HTML Audio
Enclose "Audio" in parenthesis.

2021-10-03 07:38 UTC, I-ArchanaDash commented on Web_Development/FrontEnd/Introduction_to_Html/Audio.md
> +## Introduction to HTML Audio
Done

2021-10-03 07:39 UTC, I-ArchanaDash commented
> Remove the second file.

Do you mean the image file ?

2021-10-03 10:12 UTC, kashishahuja2002 commented
> Do you mean the image file ?

Yes merge it in the first file only.

2021-10-03 13:42 UTC, kashishahuja2002 requested changes
I can still see 2 files, remove Web_Development/FrontEnd/Introduction_to_Html/Audio/img.png

2021-10-03 14:15 UTC, kashishahuja2002 approved these changes
Good to go. @Saviour1001

2021-10-05 13:05 UTC, praveenscience approved these changes
👍

2021-10-05 13:05 UTC, merged