Frontend web development html css js - Data Attributes in Js
girlscript/winter-of-contributing pull request #4090
Opened 2021-10-03 02:52 UTC by photon149

<hr>
## Description 📜

I have added a summary about Data Attributes in Javascript.Mentioned about their working , procedure as well as provided with a real world example of the same.
Fixes #3287
Name : Shiwansh Raj
Sr. No. 64

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-03 02:53 UTC, photon149 commented
Please review the same :)
@code-reaper08 @praveenscience @moulikagrawal

2021-10-05 17:43 UTC, SauravMukherjee44 approved these changes

2021-10-05 18:15 UTC, photon149 commented
Thanks , please count this as my contribution towards Hacktoberfest as well.

2021-10-06 06:03 UTC, moulikagrawal requested changes
all your content should be in a single readme.md file, don't create separate files

2021-10-06 06:12 UTC, photon149 commented
Done the changes @moulikagrawal .Please check.

2021-10-06 06:14 UTC, moulikagrawal commented on Web_Development/Javascript/4.Programming Fundamentals/Data Attribute/ATTRIBUTES_JS.MD
> +![image](https://user-images.githubusercontent.com/74582422/135737483-6fc2bfd3-cec6-443a-a6bf-841721ee5682.png)
resize this image, it is too big on preview
rename this file as readme.md

2021-10-06 06:15 UTC, moulikagrawal requested changes
rename file as readme.md
and resize the top picture

2021-10-06 06:18 UTC, photon149 commented
Done @moulikagrawal .Please check once again.Also , count this as my contribution to be part of hacktoberfest as well.

2021-10-06 06:19 UTC, moulikagrawal approved these changes

2021-10-06 06:19 UTC, merged