#4073
girlscript/winter-of-contributing pull request #4164
Opened 2021-10-03 08:50 UTC by shrutigrover25

<hr>

## Description 📜

In a given array, The even numbers will appear first and then the odd numbers. Segregated even and odd numbers in an array.
Fixes #4073

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-03 08:50 UTC, shrutigrover25 commented
Please review my first PR.

2021-10-05 03:06 UTC, deeqakkk requested changes
Before making a PR make sure, you yourself find your code/content good.
Your content need a good formatting, don't use ir-relevant emoji's
and plz use nextline tag in required statements.
![image](https://user-images.githubusercontent.com/78724676/135953735-6c3b6304-5f82-4b0a-a707-e5dd2e26c8da.png)

2021-10-05 03:06 UTC, deeqakkk commented on segregate.md
> +void swap(int *a, int *b);
complete this function code.

2021-10-05 03:06 UTC, deeqakkk commented on segregate.md
> +Input  = {12, 34, 45, 9, 8, 90, 3}
use a nextline tag here "<br>"

2021-10-05 03:06 UTC, deeqakkk commented on segregate.md
> +// C++ program to segregate even and odd elements of array
nextline tag here as well

2021-10-05 03:06 UTC, deeqakkk commented on segregate.md
> +/* Function to swap *a and *b */
nextline tag here as well

2021-10-05 12:50 UTC, shrutigrover25 commented
I have committed the changes.
Now kindly review.

On Tue, Oct 5, 2021, 08:36 Deepak Verma ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Before making a PR make sure, you yourself find your code/content good.
> Your content need a good formatting, don't use ir-relevant emoji's
> and plz use nextline tag in required statements.
> [image: image]
> <https://user-images.githubusercontent.com/78724676/135953735-6c3b6304-5f82-4b0a-a707-e5dd2e26c8da.png>
> ------------------------------
>
> In segregate.md
> <https://github.com/girlscript/winter-of-contributing/pull/4164#discussion_r721851810>
> :
>
> > +ALGORITHM💥💥
>
> +
>
> +⭐Initialize two index variables left and right:
>
> +            left = 0,  right = size -1
>
> +⭐Keep incrementing left index until we see an even number.
>
> +⭐Keep decrementing right index until we see an odd number.
>
> +⭐If left < right then swap arr[left] and arr[right]
>
> +
>
> +IMPLEMENTATION💥💥
>
> +
>
> +// C++ program to segregate even and odd elements of array
>
> +#include <iostream>
>
> +using namespace std;
>
> +
>
> +/* Function to swap *a and *b */
>
> +void swap(int *a, int *b);
>
>
> complete this function code.
> ------------------------------
>
> In segregate.md
> <https://github.com/girlscript/winter-of-contributing/pull/4164#discussion_r721852048>
> :
>
> > @@ -0,0 +1,81 @@
>
> +Given an array A[], write a function that segregates even and odd numbers.
>
> +The functions should put all even numbers first, and then odd numbers.
>
> +
>
> +
>
> +EXAMPLE💥💥
>
> +
>
> +Input  = {12, 34, 45, 9, 8, 90, 3}
>
>
> use a nextline tag here "
> "
> ------------------------------
>
> In segregate.md
> <https://github.com/girlscript/winter-of-contributing/pull/4164#discussion_r721852178>
> :
>
> > +
>
> +Input  = {12, 34, 45, 9, 8, 90, 3}
>
> +Output = {12, 34, 8, 90, 45, 9, 3}
>
> +
>
> +
>
> +ALGORITHM💥💥
>
> +
>
> +⭐Initialize two index variables left and right:
>
> +            left = 0,  right = size -1
>
> +⭐Keep incrementing left index until we see an even number.
>
> +⭐Keep decrementing right index until we see an odd number.
>
> +⭐If left < right then swap arr[left] and arr[right]
>
> +
>
> +IMPLEMENTATION💥💥
>
> +
>
> +// C++ program to segregate even and odd elements of array
>
>
> nextline tag here as well
> ------------------------------
>
> In segregate.md
> <https://github.com/girlscript/winter-of-contributing/pull/4164#discussion_r721852400>
> :
>
> > +
>
> +ALGORITHM💥💥
>
> +
>
> +⭐Initialize two index variables left and right:
>
> +            left = 0,  right = size -1
>
> +⭐Keep incrementing left index until we see an even number.
>
> +⭐Keep decrementing right index until we see an odd number.
>
> +⭐If left < right then swap arr[left] and arr[right]
>
> +
>
> +IMPLEMENTATION💥💥
>
> +
>
> +// C++ program to segregate even and odd elements of array
>
> +#include <iostream>
>
> +using namespace std;
>
> +
>
> +/* Function to swap *a and *b */
>
>
> nextline tag here as well
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/girlscript/winter-of-contributing/pull/4164#pullrequestreview-770935008>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUHQTDKGOE63NALZDW3W2ZDUFJTTXANCNFSM5FHLM46Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-11 08:34 UTC, shrutigrover25 commented
Ok

On Mon, Oct 11, 2021, 13:38 Kashish Ahuja ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Add the topic name as the heading.
> Enclose code in proper snippet format.
> Use markdown syntaxes.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/girlscript/winter-of-contributing/pull/4164#pullrequestreview-775924156>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUHQTDJL45ODNBULCG4KN43UGKLOBANCNFSM5FHLM46Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-12 10:35 UTC, kashishahuja2002 commented
No updates for long, make changes or close the PR. @shrutigrover25 
Please close this PR. @Saviour1001

2021-11-12 14:23 UTC, closed without merging