ML_2_2_Contrast between Regression and Classification (V).md
girlscript/winter-of-contributing pull request #4192
Opened 2021-10-03 11:24 UTC by Sumit3301

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #2786 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [x] Machine Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
![image](https://user-images.githubusercontent.com/47640427/135751472-24214621-4daf-4cd2-b39a-f722d86a2c00.png)

 
<hr>

2021-10-03 11:26 UTC, Sumit3301 commented
@geeythree  is this correct? kindly check

2021-10-03 17:29 UTC, Sumit3301 commented
@Isha307  can you please check and let me know if this is correct?

2021-10-04 03:25 UTC, Isha307 requested changes

2021-10-04 03:25 UTC, Isha307 commented on Machine_Learning/Supervised_Machine_Learning/ML_2_2_Contrast between Regression and Classification (V).md
> +4. Implementation of liner regression.
linear

2021-10-04 03:25 UTC, Isha307 commented on Machine_Learning/Supervised_Machine_Learning/ML_2_2_Contrast between Regression and Classification (V).md
> +9. Difference between both
replace both with "classification and regression"

2021-10-04 03:40 UTC, Isha307 commented
@Sumit3301 also change the PR title to this "ML 2.2 : Contrast between Regression and Classification (V)"

2021-10-04 03:48 UTC, Sumit3301 commented
> @Sumit3301 also change the PR title to this "ML 2.2 : Contrast between Regression and Classification (V)"

done

2021-10-04 03:50 UTC, Isha307 approved these changes

2021-10-04 03:50 UTC, merged

2021-10-04 03:51 UTC, Isha307 commented
@Sumit3301 Congratulation🥳, your first PR got merged.