C_CPP : Storage Classes in C++
girlscript/winter-of-contributing pull request #4205
Opened 2021-10-03 12:36 UTC by vartikavr

<hr>

## Description 📜

This documentation contains explanations along with examples of storage classes in C++.
Fixes #3988 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] Java#Script
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-03 14:57 UTC, apeksha235 requested changes
@vartikavr Just make the following changes, excellent work otherwise!

2021-10-03 14:57 UTC, apeksha235 commented on C_CPP/Fundamentals/Storage Classes in C++/Storage_Classes.md
> +The keyword used for this storage class is : <em>`auto`</em>. The lifetime that this storage class offers to a variable or function is : <strong>function block</strong>. </br>
Get rid of the html tags here

2021-10-03 14:57 UTC, apeksha235 commented on C_CPP/Fundamentals/Storage Classes in C++/Storage_Classes.md
> +The keyword used for this storage class is : <em>`extern`</em>. The lifetime that this storage class offers to a variable or function is : <strong>the whole program</strong>. </br>
Here as well

2021-10-03 16:17 UTC, vartikavr commented
@apeksha235 I've done the suggested changes. Please look into it.

2021-10-06 05:26 UTC, deeqakkk approved these changes
Nicely explained👏
@Saviour1001 its good to be merged.

2021-10-06 08:02 UTC, merged