[JS] Topic: JSX
girlscript/winter-of-contributing pull request #4417
Opened 2021-10-04 09:25 UTC by SakshiMishra1

<hr>

## Description 📜

Wrote a tutorial on JSX.
Resolves # <3294> 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-04 09:26 UTC, SakshiMishra1 commented
@paramsiddharth sir please review.

2021-10-04 09:27 UTC, SakshiMishra1 commented
issue #3294

2021-10-04 10:55 UTC, dakshsethi requested changes
Change all of your code blocks into snippets using ```

2021-10-04 10:55 UTC, dakshsethi commented on JavaScript/Topics/Flavours/README.md
> +JSX (JavaScript Syntax Extension and occasionally referred as JavaScript XML) is an extension to the JavaScript language syntax[1] which provides a way to structure component rendering using syntax f
```suggestion
JSX **(JavaScript Syntax Extension and occasionally referred to as JavaScript XML)** is an extension to the JavaScript language syntax which provides a way to structure component rendering using syntax familiar to many developers. It is similar in appearance to HTML.
```

2021-10-04 10:55 UTC, dakshsethi commented on JavaScript/Topics/Flavours/README.md
> +
Write like this:
```jsx
const myelement = <h1>I Love JSX!</h1>;
< ReactDOM.render(myelement, document.getElementById('root'));
```

```
```jsx
const myelement = <h1>I Love JSX!</h1>;
< ReactDOM.render(myelement, document.getElementById('root'));
`` `
```

2021-10-04 10:55 UTC, dakshsethi commented on JavaScript/Topics/Flavours/README.md
> +    <h1>{10+1}</h1>
Write like this for every code block if jsx:
```jsx
<h1> { 10 + 1 } </h1>
```
```suggestion
    ```jsx
    <h1> { 10 + 1 } </h1>```
```

2021-10-04 10:55 UTC, dakshsethi commented on JavaScript/Topics/Flavours/README.md
> +    <h1>11</h1>
```suggestion
    ```html
    <h1>11</h1>```
```

2021-10-04 12:14 UTC, SakshiMishra1 commented
@dakshsethi Made the changes sir

2021-10-04 15:59 UTC, dakshsethi requested changes
Please do all of these changes in a single commit!

2021-10-04 15:59 UTC, dakshsethi commented on JavaScript/Topics/Flavours/README.md
> +```<h1>{10+1}</h1>```
Write like this:
```
```jsx
<h1>{10+1}</h1>```

2021-10-04 15:59 UTC, dakshsethi commented on JavaScript/Topics/Flavours/README.md
> +```<h1>11</h1>```
Write like this here:
```
```html
<h1>11</h1>```

2021-10-04 15:59 UTC, dakshsethi commented on JavaScript/Topics/Flavours/README.md
> +```
Write like this:
```
```jsx
const App = () => {

  const i = 1;

  return (
      <div>
        <h1>{ i === 1 ? 'true' : 'false' }</h1>
      </div>
  );
}```

2021-10-04 15:59 UTC, dakshsethi commented on JavaScript/Topics/Flavours/README.md
> +```
Write like this:
```
```html
<div>
  <h1>true</h1>
</div>```

2021-10-04 15:59 UTC, dakshsethi commented on JavaScript/Topics/Flavours/README.md
> +```
Write like this here:
```
```jsx
const App = () => {

   const sections = [1, 2, 3];

   return (
      <div>
        {sections.map((n,i) => (
          /* 'key' is used by react to keep track of list items and their changes */
          /* Each 'key' must be unique */
          <div key={"section-" + n}>
             Section {n} {i === 0 && <span>(first)</span>}
          </div>
        ))}
       </div>
   );
}```

2021-10-04 15:59 UTC, dakshsethi commented on JavaScript/Topics/Flavours/README.md
> +```
```
```html
<div>
    <div>Section 1<span>(first)</span></div>
    <div>Section 2</div>
    <div>Section 3</div>
</div>
`` `

2021-10-04 15:59 UTC, dakshsethi commented on JavaScript/Topics/Flavours/README.md
> +```**JSX:**
Dont make it bold!!
```
```jsx 
```
Write that...

2021-10-04 15:59 UTC, dakshsethi commented on JavaScript/Topics/Flavours/README.md
> +```**Without JSX:**
Make this jsx only
```
```jsx
```
Don't use bold
Mention in a comment that this is without jsx

2021-10-04 17:59 UTC, s4-2 commented
@SakshiMishra1  Please write Fix issue #3294 in the documentation section and do check  the required checkbox block:)

2021-10-04 18:03 UTC, s4-2 commented on JavaScript/Topics/Flavours/README.md
> +**The merits of JSX in four bullet points:**
@SakshiMishra1  Just write **Merits of JSX :**

2021-10-05 05:40 UTC, SakshiMishra1 commented
Made the changes.
Please review @dakshsethi @s4-2 @paramsiddharth

2021-10-05 05:43 UTC, s4-2 approved these changes
Looks good to me. 
@SakshiMishra1 well done:)

2021-10-05 11:06 UTC, dakshsethi approved these changes
Looks good to me!! 🔥🔥🔥

2021-10-05 13:16 UTC, SakshiMishra1 commented
Is the PR ready to get merged??
@dakshsethi @paramsiddharth @s4-2

2021-10-05 18:09 UTC, paramsiddharth commented
@SakshiMishra1 I'll be relocating the README to Flavours/JSX/README.md after the merge. 😊 Rest looks amazing! The explanation is fantastic. 💕 Good job!

2021-10-05 18:09 UTC, merged

2021-10-05 18:10 UTC, paramsiddharth approved these changes

2021-10-06 02:06 UTC, SakshiMishra1 commented
> @SakshiMishra1 I'll be relocating the README to Flavours/JSX/README.md after the merge. 😊 Rest looks amazing! The explanation is fantastic. 💕 Good job!

Thank you sir❤