[JS] Topic : Data Types in JavaScript
girlscript/winter-of-contributing pull request #457
Opened 2021-09-17 11:04 UTC by AbhinandanAdhikari

<hr>

## Description 📜

Created a tutorial for JavaScript Data types.
Fixes #73 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [x] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-17 14:25 UTC, AbhinandanAdhikari commented
@paramsiddharth  Sir please review this.

2021-09-17 16:10 UTC, dakshsethi requested changes

2021-09-17 17:12 UTC, AbhinandanAdhikari commented on Web_Development/Javascript/Topics/5.Syntax/1.Data_Types/README.md
> +```
@dakshsethi  @paramsiddharth Sir, Made the changes, Please review it.

2021-09-18 03:45 UTC, paramsiddharth approved these changes

2021-09-18 03:45 UTC, paramsiddharth commented
@Creatoon @dakshsethi Please review.

2021-09-18 09:17 UTC, AbhinandanAdhikari commented
@Creatoon @dakshsethi  Sir, please review

2021-09-18 10:22 UTC, paramsiddharth commented
@AbhinandanAdhikari Another PR with a document-based contribution to the same topic has been merged. I'm closing this PR.

Your documentation contains additional content with respect to the contribution by Aniket, so I encourage you to pull the changes, add content to the README file for Data Types, add your name to the contributors' list at the end of the file, and make a fresh PR. Best of luck!

2021-09-18 10:22 UTC, closed without merging