string methods
girlscript/winter-of-contributing pull request #4794
Opened 2021-10-06 13:18 UTC by itsajay1029

<hr>

## Description 📜

Useful Methods that can be used in String objects in Javascript while front-end development.

Methods:

1.length
2.slice()
3.substring()
4.replace()
5.toUpperCase()
6.toLowerCase()
7.concat()
8.trim()
9.charAt()
10.charCodeAt()
11.split()
Fixes #4136 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-06 13:28 UTC, kashishahuja2002 requested changes
Add output also for every method.

2021-10-06 15:44 UTC, itsajay1029 commented on Web_Development/Javascript/String Methods/String_method.md
> +
Done.

2021-10-06 16:18 UTC, kashishahuja2002 approved these changes
Simple yet sorted work, good. 😃

2021-11-12 10:39 UTC, kashishahuja2002 commented
> Good to go. @praveenscience

Please further review and merge the PR. @praveenscience

2021-11-18 01:34 UTC, praveenscience approved these changes
👍

2021-11-18 01:34 UTC, merged