[JS] Topic: Tutorial for JavaScript Operators
girlscript/winter-of-contributing pull request #536
Opened 2021-09-17 20:38 UTC by rwiteshbera

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # <issue_number_here> 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [X ] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>
 
## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-17 21:44 UTC, dakshsethi requested changes

2021-09-17 21:44 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/ArithmeticOperator.md
> +#### 1. Addition (+)
First of all Make ArithmeticOperator.md in it's folder named `1.Arithmetic_Operators` and rename the file to *README.md*

2021-09-17 21:44 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/ArithmeticOperator.md
> +#### 5. Remainder (%)
Remainder Operator is called as *Modulus* operator

2021-09-17 22:13 UTC, dakshsethi requested changes

2021-09-17 22:13 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/ComparisonOperator.md
> +
Add `Strict Not Equal To Operator (!==)` and write about it also.
Also talk about how this should be the mainstream practice as in this example `0 !== '0'` results in **false** while **not equal to operator (!=)** results in **true** in the same expression.

2021-09-17 22:13 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/ComparisonOperator.md
> +#### 5. Greater Than or Equal Operator (>=)
Change this to `#### 5. Greater Than or Equal To Operator (>=)`

2021-09-17 22:13 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/ComparisonOperator.md
> +#### 7. Less Than or Equal Operator (<=)
Change this to `#### 7. Less Than or Equal To Operator (<=)`

2021-09-17 22:13 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/ComparisonOperator.md
> +console.log(4!=3); // true
Talk about how `0 != '0'` still results in **true** in this case.
This is the problem and the programmer must be very careful not mixing between data types.

2021-09-17 22:13 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/ComparisonOperator.md
> +```
Explain by an example that with == operator, JavaScript does not check for data types but only checks for values.
Example `5 == '5'` results in **true**.

2021-09-17 22:13 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/README.md
> +| Equal (=)                 | `console.log(1 == 2);`                                       | `false`       |
`Equal to (==)`
Please change this.

2021-09-17 22:13 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/README.md
> +
It should be `Strict Equal To (===)`, change this.
Also add `Strict Not Equal To (!==)` after this with an example.

2021-09-19 06:44 UTC, rwiteshbera commented
@dakshsethi Sir, I have made all those suggested changes.

2021-09-19 13:47 UTC, dakshsethi requested changes

2021-09-19 13:47 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/3.Comparison_Operators/README.md
> +```
Give example of `5=='5' as true`

2021-09-19 13:47 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/3.Comparison_Operators/README.md
> +It will return true if both values are equal, otherwise false.
Mention here that == does not check for data types but only value.

2021-09-19 13:47 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/3.Comparison_Operators/README.md
> +console.log(0!='0'); // return true because left value is a number and right value is a string.
`// return true even if the data types are different but the values are same on the left hand side and right hand side`

2021-09-19 13:47 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/README.md
> +| Equal (==)                | `console.log(1 == 2);`                                       | `false`       |
Change this to `Equal To (==)`

2021-09-19 13:47 UTC, dakshsethi commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/README.md
>  | Not Equal (!=)            | `console.log(1 != 2);`                                       | `true`        |
Change this to `Not Equal To (!=)`

2021-09-19 14:15 UTC, rwiteshbera commented
Please review my changes.

2021-09-19 15:51 UTC, dakshsethi approved these changes
It's perfect now @rwiteshbera !! Great job. 🔥🔥🔥

2021-09-20 09:14 UTC, s4-2 commented
Look good for me:)

2021-09-20 09:14 UTC, s4-2 approved these changes

2021-09-20 16:24 UTC, s4-2 approved these changes

2021-09-20 16:26 UTC, s4-2 commented
@rwiteshbera Please complete the description part as it is important to keep track of which issue is solved.

2021-09-20 16:42 UTC, dakshsethi commented
@paramsiddharth @Creatoon please review his work.

2021-09-21 04:59 UTC, paramsiddharth commented
@rwiteshbera Please ALWAYS add the issue number to the PR description.

2021-09-21 05:02 UTC, paramsiddharth commented
@rwiteshbera Despite being perfect, I can't merge the PR now because of too many diffs and conflict. You should have branched out of the `Javascript` branch and not the `main` branch. Merging it means crowding up contributions from other branches into the `Javascript` branch.

I'll have to close this. Please create a new PR.

2021-09-21 05:02 UTC, closed without merging