Added Spiral Matrix
girlscript/winter-of-contributing pull request #5360
Opened 2021-10-10 06:58 UTC by yellowberard

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #1921

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Competitive #Programming

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-10 07:05 UTC, yellowberard commented
@Rishabh510 Please review my PR. I submitted late because I had some issues with my github so I was not able to clone.

2021-10-30 01:50 UTC, yellowberard commented
Hi @ravireddy07 I can you tell how to format it correctly.

2021-10-30 06:47 UTC, ravireddy07 commented
> Hi @ravireddy07 I can you tell how to format it correctly.

Hey, It's simple. Just preview your readme file, It's gives output of your documenatation. then you can see what's wrong.
Whatever the editor that you using, you can preview it. Just google, how to preview a readme file with your fav editor.

you can refer other merged doc.

maintain few points like:
* Intro
* problem_Statement
* algorithm/approach
* code_snippets with explanation
* input/output examples
* complexity
* conclusion(discuss this approach and compare other approaches....etc)

2021-11-02 15:41 UTC, yellowberard commented
I have added time complexity, example, input, output, space complexity and whole code.

2021-11-02 16:55 UTC, ravireddy07 requested changes
Please follow below points @yellowberard 

* Avoid using `<br>` tags. Just an Empty line would be enough.
* Highlight the keywords by adding some headers, bold...etc

2021-11-02 16:55 UTC, ravireddy07 commented on Competitive_Programming/C++/Matrix/Spiral_Matrix.md
> +</h4>
avoid using `<br>` tags, Just an empty line would be enough

2021-11-02 16:55 UTC, ravireddy07 commented on Competitive_Programming/C++/Matrix/Spiral_Matrix.md
> +Example <br> Input:<br> r = 4, c = 4<br> matrix[][] = {{1, 2, 3, 4}, {5,
Highlight the required words like: input, output...etc

2021-11-02 16:55 UTC, ravireddy07 commented on Competitive_Programming/C++/Matrix/Spiral_Matrix.md
> +Time Complexity:O(r*c); Space Complexity:O(r*c);<br>
Add this at bottom with a title

2021-11-02 16:55 UTC, ravireddy07 commented on Competitive_Programming/C++/Matrix/Spiral_Matrix.md
> +```
Add formatted code(use 4-space indentation)

2021-11-02 17:00 UTC, ravireddy07 requested changes

2021-11-02 22:22 UTC, yellowberard commented
Can I Make a new PR

2021-11-03 03:54 UTC, ravireddy07 commented
> Can I Make a new PR

You can update same file, no need of making new PR.

2021-11-03 10:58 UTC, yellowberard commented
I have to refork the repository because I was facing some issue with github so I can't push more commits in this PR.

2021-11-03 13:18 UTC, ravireddy07 commented
close this and raise a new PR. @yellowberard

2021-11-03 18:33 UTC, yellowberard commented
I have created a new PR #7257.

2021-11-03 18:33 UTC, closed without merging