Reverse word in a String
girlscript/winter-of-contributing pull request #5665
Opened 2021-10-12 08:28 UTC by yellowberard

<hr>

## Description 📜

I have added a solution for reversing word in a string 
Fixes #1921

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/#CPP
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-03 11:01 UTC, yellowberard commented
@2024-SANDHYA  please review my PR

2021-11-04 15:40 UTC, apeksha235 requested changes
@yellowberard please make these changes

2021-11-04 15:40 UTC, apeksha235 commented on C_CPP/Strings and their functions/reverse_string.md
> +<h1 text align="center"> Reversing words in a String</h1>
please use [markdown](https://www.markdownguide.org/basic-syntax/)  formatting and not html

2021-11-04 15:40 UTC, apeksha235 commented on C_CPP/Strings and their functions/reverse_string.md
> +<p>This a answer for leetcode  <a href"https://leetcode.com/problems/reverse-words-in-a-string/">question</a> https://leetcode.com/problems/reverse-words-in-a-string/ <br>
write down the problem statement, don't provide a link  for it

2021-11-04 15:40 UTC, apeksha235 commented on C_CPP/Strings and their functions/reverse_string.md
> +Example<br>  Input: s = "a good   example" <br>
add the input output inside ```

2021-11-04 15:40 UTC, apeksha235 commented on C_CPP/Strings and their functions/reverse_string.md
> +```
use ```c++ syntax highlighting

2021-11-08 04:48 UTC, kashishahuja2002 requested changes
Also, add your approach to solving the problem.

2021-11-08 04:48 UTC, kashishahuja2002 commented on C_CPP/Strings and their functions/reverse_string.md
> +<p>This a answer for leetcode  <a href"https://leetcode.com/problems/reverse-words-in-a-string/">question</a> https://leetcode.com/problems/reverse-words-in-a-string/ <br>
Embed the link in the name of the problem question and also write the whole problem here.

2021-11-08 04:48 UTC, kashishahuja2002 commented on C_CPP/Strings and their functions/reverse_string.md
> +```
Add proper indentation and comments to the code.

2021-11-08 12:33 UTC, yellowberard commented
Can I make a new PR because of some issue with github I had to refork the repository ??

2021-11-09 10:39 UTC, yellowberard commented
@kashishahuja2002

2021-11-09 13:50 UTC, kashishahuja2002 commented
> Can I make a new PR because of some issue with github I had to refork the repository ??

Refork, don't know why you needed to do that. Try solving issues in the same PR. If not then you can close this and make a new one.

2021-11-22 12:42 UTC, closed without merging