Number System Conversion Programs in C++
girlscript/winter-of-contributing pull request #6672
Opened 2021-10-25 06:21 UTC by Nandani-koli

<hr>

## Description 📜

Program to convert from any base to Decimal in cpp.
Program to convert from decimal to any other base in cpp.
Fixes #2188

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

2021-10-30 05:20 UTC, deeqakkk commented
> @deeqakkk Sir, actually someone already created the theory description of types of number system and their conversion in the same folder [here](https://github.com/girlscript/winter-of-contributing/blob/C_CPP/C_CPP/Number%20System/num_sys.md) That's why I created issue for practical programs. Is this the changes you want ? or I misunderstood ? if so, i am sorry, please clarify

Thank you for pinging me on discord, and sorry for the delay.
The change I want you to do is, just add a single line descripton with an e.g so that if someone is reading your content then he/she need not switch between files to see the code and theory separately.

2021-10-30 05:22 UTC, deeqakkk commented
> > @deeqakkk Sir, actually someone already created the theory description of types of number system and their conversion in the same folder [here](https://github.com/girlscript/winter-of-contributing/blob/C_CPP/C_CPP/Number%20System/num_sys.md) That's why I created issue for practical programs. Is this the changes you want ? or I misunderstood ? if so, i am sorry, please clarify
> 
> Thank you for pinging me on discord, and sorry for the delay. The change I want you to do is, just add a single line descripton with an e.g so that if someone is reading your content then he/she need not switch between files to see the code and theory separately.

or instead of all these just add a link to theory files in your code.

2021-10-30 07:57 UTC, Nandani-koli commented
@deeqakkk ok sir  I got it, I will try to do the best possible changes...

2021-10-31 17:13 UTC, deeqakkk requested changes
just make this one change.
@Suvraneel it's good to be merged after the change.

2021-10-31 17:13 UTC, deeqakkk commented on C_CPP/Number System/Conversion-Programs/Decimal-to-other-base-conversion.md
> +*(Note:- if remainder is 10, 11, 12, 13, 14, 15 then in hexadecimal it will be A,B,C,D,E,F respectively.*
Nandani, close this bracket which started at Note:-.

2021-10-31 18:57 UTC, Suvraneel requested changes

2021-10-31 18:57 UTC, Suvraneel commented on C_CPP/Number System/Conversion-Programs/Decimal-to-other-base-conversion.md
> +}
```suggestion
    return ans ;
}
```

2021-10-31 18:57 UTC, Suvraneel commented on C_CPP/Number System/Conversion-Programs/Decimal-to-other-base-conversion.md
> +## OUTPUT:-
```suggestion
## OUTPUT  
```

2021-10-31 18:57 UTC, Suvraneel commented on C_CPP/Number System/Conversion-Programs/Decimal-to-other-base-conversion.md
> +## OUTPUT:-
```suggestion
## OUTPUT  
```

2021-10-31 18:57 UTC, Suvraneel commented on C_CPP/Number System/Conversion-Programs/Decimal-to-other-base-conversion.md
> +## OUTPUT:-
```suggestion
## OUTPUT  
```

2021-10-31 18:57 UTC, Suvraneel commented on C_CPP/Number System/Conversion-Programs/Other-base-to-Decimal-Conversion.md
> +int main()
```suggestion
}

int main()
```

2021-10-31 18:57 UTC, Suvraneel commented on C_CPP/Number System/Conversion-Programs/Other-base-to-Decimal-Conversion.md
> +# OUTPUT:-
```suggestion
## OUTPUT  
```
Wrong level of heading

2021-10-31 18:57 UTC, Suvraneel commented on C_CPP/Number System/Conversion-Programs/Other-base-to-Decimal-Conversion.md
> +int main()
```suggestion
}

int main()
```

2021-10-31 18:57 UTC, Suvraneel commented on C_CPP/Number System/Conversion-Programs/Other-base-to-Decimal-Conversion.md
> +# OUTPUT:-
```suggestion
## OUTPUT  
```

2021-11-01 05:17 UTC, Nandani-koli commented
@deeqakkk @Suvraneel Thank you so much sir.

2021-11-01 07:58 UTC, Suvraneel commented
@Nandani-koli  LGTM  :octocat:  ❤️  Nice work 🚀

2021-11-01 07:59 UTC, merged