Structured Binding
girlscript/winter-of-contributing pull request #6728
Opened 2021-10-26 16:49 UTC by Megha0606

<hr>

##  Description 📜

Added the file, Please Review.
Fixes #6724

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [X] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-31 05:10 UTC, apeksha235 requested changes
@Megha0606 also add a relative link of your file in the readme of the respective folder

2021-10-31 05:10 UTC, apeksha235 commented on C_CPP/Structured Binding/README.md
> +```
use ```cpp syntax highlighting for every code

2021-10-31 06:31 UTC, Suvraneel requested changes
- Syntax Highlighting -> Add `CPP` to each codeblock
- Readme relative link
- Remove unnecessary new line characters...
To add new line you just add two spaces at the end of the previous line

2021-10-31 06:31 UTC, Suvraneel commented on C_CPP/Structured Binding/README.md
> +    char a = 'a';
```suggestion
std::tuple<char, int, bool> mytuple()  
{  
    char a = 'a';
```

Remove extra lines

2021-10-31 06:31 UTC, Suvraneel commented on C_CPP/Structured Binding/README.md
> +    std::tie(a, i, b) = mytuple();
```suggestion
    ```cpp
    char a;
    int i;
    bool b;
    std::tie(a, i, b) = mytuple();
    ```
```

2021-10-31 06:31 UTC, Suvraneel commented on C_CPP/Structured Binding/README.md
> +identifier-list is a comma-separated list of variables.
```suggestion
    **auto ref-operator** can be any attribute.
**attr** can be any attribute.  
**cv-auto** is cv-qualified type specifier auto.  
ref-operator is & or &&.  
**identifier-list** is a comma-separated list of variables.
```

Embolden wherever necessary to make text more legible

2021-11-02 20:04 UTC, Suvraneel commented
@Megha0606  Awesome, Everything else is okay but its not in correct path...
You can NOT create a new folder under our main CPP directory...

Put this under any pre-existing appropriate directory (maybe `C++17` )

2021-11-02 20:04 UTC, Suvraneel requested changes
New directory not allowed

2021-11-03 13:18 UTC, merged

2021-11-03 13:18 UTC, Suvraneel commented
@Megha0606  LGTM ❤️ :octocat:  🚀  Awesome 💯