Frontend web development html css js
girlscript/winter-of-contributing pull request #6845
Opened 2021-10-28 13:52 UTC by darshan4903

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #issue_number_here 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-30 04:42 UTC, kashishahuja2002 requested changes

2021-10-30 04:42 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/CSS Hover Effect/CSS Hover Effect .md
> +</body>
```
<body>
<p>GWOC : <a href="https://gwoc.girlscript.tech/">girlscript.com</a></p>
<br>
<p>Link: Blue</p>
<p>Visited: Green</p>
<p>Hover: Red</p>
<p>Active: Yellow</p>
</body>
```

2021-10-30 04:42 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/CSS Hover Effect/CSS Hover Effect .md
> +</body>
Show blue in blue color, green in green and so on...

2021-10-30 05:01 UTC, darshan4903 commented
updated as per suggestion @kashishahuja2002

2021-10-30 07:11 UTC, kashishahuja2002 approved these changes
LGTM.

2021-10-30 09:39 UTC, 2024-SANDHYA requested changes
The content is really very short & not structured. Start with what, why Hover effects & then the syntax, also avoid using excessive emojis, keep it a bit professional, please. The rest is all good.

2021-10-30 10:07 UTC, darshan4903 commented
Ok I will structure it and remove the emojis but what else content should I add?
Should I add more examples showing hover effect?

2021-10-30 10:19 UTC, 2024-SANDHYA commented
> 
> 
> Ok I will structure it and remove the emojis but what else content should I add? Should I add more examples showing hover effect?

No, don't add more examples, add a bit theory, that what are hover effects, how they help and you know stuff like that not much just 5-6 lines will work.

2021-10-30 12:20 UTC, code-reaper08 requested changes
Need a bit more explanation on the topic.
Other things LGTM ✨

2021-10-30 12:20 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS Hover Effect/CSS Hover Effect .md
> +```
Code blocks should have syntax.

2021-10-30 12:20 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS Hover Effect/CSS Hover Effect .md
> +```
Code blocks should have syntax.

2021-10-30 12:20 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS Hover Effect/CSS Hover Effect .md
> +```
Code blocks should have syntax.

2021-10-30 12:20 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS Hover Effect/CSS Hover Effect .md
> +```
Code blocks should have syntax.

2021-10-31 09:41 UTC, darshan4903 commented
Updated @2024-SANDHYA @code-reaper08

2021-10-31 09:45 UTC, 2024-SANDHYA requested changes
Reference links missing.

2021-10-31 10:21 UTC, darshan4903 commented
updated @2024-SANDHYA

2021-10-31 10:26 UTC, 2024-SANDHYA approved these changes

2021-10-31 12:23 UTC, code-reaper08 approved these changes

2021-10-31 12:23 UTC, merged