Static and Dynamic scoping
girlscript/winter-of-contributing pull request #6855
Opened 2021-10-28 15:35 UTC by vishnu95075

<hr>

## Description 📜

Static scoping & Dynamic Scoping 
Fixes #6854

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

2021-11-05 23:54 UTC, vishnu95075 commented
@gunjan-g  please give example of Add index line in readme along with relative link of folder created

2021-11-06 07:09 UTC, gunjan-g requested changes
@vishnu95075 Do the required changes

2021-11-06 07:09 UTC, gunjan-g commented on C_CPP/Fundamentals/Static scoping & Dynamic Scoping/Static scoping & Dynamic Scoping.md
> +
```suggestion
<br>
```

2021-11-06 07:09 UTC, gunjan-g commented on C_CPP/Fundamentals/Static scoping & Dynamic Scoping/readme.md
> +- Static and Dynamic scoping
```suggestion
- Static and Dynamic scoping (./Static scoping & Dynamic Scoping.md)
```

2021-11-08 05:28 UTC, gunjan-g commented on C_CPP/Fundamentals/Static scoping & Dynamic Scoping/readme.md
> +- Static and Dynamic scoping
@vishnu95075 Just copy and paste the above suggested index line, you have to add this relative link

2021-11-11 05:37 UTC, vishnu95075 commented
@Saviour1001 thanks for suggestion. I am resolve that please review.

2021-11-11 09:29 UTC, Saviour1001 commented
Looks perfect !

2021-11-11 09:29 UTC, merged