Dijkstra's Algorithm
girlscript/winter-of-contributing pull request #6856
Opened 2021-10-28 16:01 UTC by prishit55

<hr>

## Description 📜

This is a brief documentation on Dijkstra's Algorithm. I've tried to explain the algorithm in simple language through pseudo code and also the actual cpp code.  #6785

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸
![Screenshot (22)](https://user-images.githubusercontent.com/77775000/139292838-1cd7d062-9617-41eb-a593-675ced96d923.png)

<hr>

2021-11-01 04:53 UTC, kashishahuja2002 requested changes
Add some explaining comments to code.

2021-11-01 04:53 UTC, kashishahuja2002 commented on C_CPP/Data Structures/Graph/Dijkstra's Algorithm/Dijkstra's.md
> +# <p style="text-align: center;">🌟 Dijkstra's algorithm 🌟<p>
Remove 🌟 please.

2021-11-01 04:53 UTC, kashishahuja2002 commented on C_CPP/Data Structures/Graph/Dijkstra's Algorithm/Dijkstra's.md
> +Dijkstra's Algorithm is used to find shortest path between nodes in a given graph. For a given  source node **Dijkstra's algorithm** finds the shortest path from source node to all other nodes of the
Can you explain it a bit more.

2021-11-01 04:53 UTC, kashishahuja2002 commented on C_CPP/Data Structures/Graph/Dijkstra's Algorithm/Dijkstra's.md
> +```
Add syntax highlight. ```cpp

2021-11-01 04:53 UTC, kashishahuja2002 commented on C_CPP/Data Structures/Graph/Dijkstra's Algorithm/Dijkstra's.md
> +![example](https://s3.amazonaws.com/vasir-assets/archive/shortest_path1.png)
Add reference source of image just below it.

2021-11-01 13:05 UTC, prishit55 commented
@kashishahuja2002  I've updated the file as suggested , pls check .

2021-11-01 14:47 UTC, kashishahuja2002 commented on C_CPP/Data Structures/Graph/Dijkstra's Algorithm/Dijkstra's.md
> +>image credit: s3.amazonaws.com
Add link embeded in text.

2021-11-01 16:12 UTC, prishit55 commented
@kashishahuja2002 Done!

2021-11-02 05:46 UTC, kashishahuja2002 approved these changes
LGTM

2021-11-02 12:51 UTC, prishit55 commented
Then, kindly merge it.

2021-11-02 15:07 UTC, kashishahuja2002 commented
> Then, kindly merge it.

For that you need to tag the supervisor of your batch, mentors don't have that access.

2021-11-03 06:36 UTC, prishit55 commented
@Suvraneel pls merge this PR.

2021-11-03 07:02 UTC, Suvraneel requested changes
Also, try to follow PR template...
It was clearly directed to remove hashtags from domain & type of contrib...

Otherwise, this is NOT labelled as **C/CPP** & will never appear in our feed...

2021-11-03 07:02 UTC, Suvraneel commented on C_CPP/Data Structures/Graph/Dijkstra's Algorithm/Dijkstra's.md
> +Dijkstra's Algorithm is used to find shortest path between nodes in a given graph. For a given  source node Dijkstra's algorithm finds the shortest path from source node to all other nodes of the gra
If you can, format it better...
Instead of stuffing all in a paragraph use line breaks... Makes text more legible to readers

2021-11-03 14:35 UTC, prishit55 commented on C_CPP/Data Structures/Graph/Dijkstra's Algorithm/Dijkstra's.md
> +Dijkstra's Algorithm is used to find shortest path between nodes in a given graph. For a given  source node Dijkstra's algorithm finds the shortest path from source node to all other nodes of the gra
Done! pls check

2021-11-03 14:35 UTC, prishit55 commented on C_CPP/Data Structures/Graph/Dijkstra's Algorithm/Dijkstra's.md
> +
done!

2021-11-03 14:36 UTC, prishit55 commented on C_CPP/Data Structures/Graph/Dijkstra's Algorithm/Dijkstra's.md
> +                pq.push(make_pair(currdist,currnode));
Done!

2021-11-03 14:40 UTC, prishit55 commented
I haven't added any reference links as this code is from my personal notes and my personal understanding.

2021-11-03 15:18 UTC, Suvraneel commented
@prishit55  Awesomeeeee ! ❤️ :octocat:   LGTM 💯  🚀

2021-11-03 15:18 UTC, merged