Added Flood Fill Problem
girlscript/winter-of-contributing pull request #6938
Opened 2021-10-30 06:59 UTC by aman12207

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #6879
<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-30 07:01 UTC, Suvraneel commented
@vasu-1

2021-10-30 12:47 UTC, apeksha235 requested changes
@aman12207

2021-10-30 12:47 UTC, apeksha235 commented on C_CPP/Algorithmic Approaches/Backtracking/Flood_Fill_Problem.md
> +```c
cpp* not c

2021-10-30 12:47 UTC, apeksha235 commented on C_CPP/Algorithmic Approaches/Backtracking/Flood_Fill_Problem.md
> +void floodfill(vector<vector<int>> maze,int rows,int columns,string ans,bool visited[][col]) {
please add relevant comments to your code

2021-10-30 13:21 UTC, aman12207 commented
I made the changes as directed..

2021-10-31 07:08 UTC, Suvraneel commented
@aman12207  Do these & tag me

2021-10-31 09:16 UTC, aman12207 commented
@Suvraneel Please tell me what is need to do..

2021-10-31 13:42 UTC, Suvraneel requested changes

2021-10-31 17:07 UTC, aman12207 commented on C_CPP/Algorithmic Approaches/Backtracking/Flood_Fill_Problem.md
> +This array is filled with either 0 or 1. You can only move to cells which have 0 value in them. You can't move out of the boundaries or in the cells which have value 1 in them (1 means obstacle)
Ohh.. Thanks a lot i don't know that before 
previously I am using br tags to do  the same

2021-10-31 18:52 UTC, Suvraneel commented
@aman12207  LGTM

2021-10-31 18:52 UTC, merged

2021-11-01 05:19 UTC, aman12207 commented
> @aman12207 LGTM

Thanks..