Added Audio for Introductioon of structure in C
girlscript/winter-of-contributing pull request #6981
Opened 2021-10-30 17:20 UTC by Harsh652-cpu

<hr>

## Description 📜

In C langauge we come across some cases when we need to use multiple datatypes and its variables simultaneously.Structure is used for such cases.In this audio a brief overview of an Introduction to structure is given.I hope it will add some values in your coding journey. 
Fixes #6979 

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-30 17:21 UTC, Harsh652-cpu commented
@Suvraneel Have a look at this pr.

2021-11-02 10:19 UTC, apeksha235 requested changes
@Harsh652-cpu Amazing!!! Just make this change and you're good to go

2021-11-02 10:19 UTC, apeksha235 commented on C_CPP/Structure padding, Union, Enum, & typedef/Audio_Introduction_to_structure.md
> +<br>
remove this br tag

2021-11-02 15:41 UTC, Harsh652-cpu commented on C_CPP/Structure padding, Union, Enum, & typedef/Audio_Introduction_to_structure.md
> +<br>
Done @apeksha235 please check now.

2021-11-02 15:41 UTC, Harsh652-cpu commented
Done @apeksha235 Please review it now.

2021-11-02 17:12 UTC, Saviour1001 commented
Looks great 🥳

2021-11-02 17:12 UTC, merged