[CP]: Tower of Hanoi
girlscript/winter-of-contributing pull request #7076
Opened 2021-10-31 18:48 UTC by areenoverclouds

<hr>

## Description 📜

This is the documentation explaining the recursive stack approach on the Tower of Hanoi problem.
Fixes #6301

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [x] Competitive Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-10-31 18:51 UTC, areenoverclouds commented
Please review this PR, I closed the previous one because I was unable to make changes to it. I'm sorry and I won't mess it up next time.

2021-11-06 16:37 UTC, ravireddy07 requested changes
Great work @areenoverclouds , Please make the requested changes

2021-11-06 16:37 UTC, ravireddy07 commented on Competitive_Programming/C++/Stacks & Queues/TowerOfHanoi.md
> +You can read the mathematics and history behind Tower of Hanoi [here](https://www.hackerearth.com/blog/developers/tower-hanoi-recursion-game-algorithm-explained/).
References are not allowed, You can remove it.

2021-11-07 10:07 UTC, ravireddy07 approved these changes

2021-11-08 14:58 UTC, 55ritesh commented
/assign

2021-11-08 14:58 UTC, 55ritesh commented
/assign

2021-11-08 14:58 UTC, 55ritesh commented
/assign

2021-11-08 14:58 UTC, 55ritesh commented
/assign

2021-11-08 14:58 UTC, 55ritesh commented
/assign

2021-11-08 15:08 UTC, areenoverclouds commented
> /assign

why are you spam commenting assign here? this is a pull request and as far as I know, issues have to be assigned and not PRs?

2021-11-09 15:58 UTC, merged