Functionalandclasscomponents
girlscript/winter-of-contributing pull request #7078
Opened 2021-11-01 04:51 UTC by Drontitan

<hr>

## Description 📜

I have created the md file containing information about Functional and class based components
Fixes #1256 

<hr>

## Type of change 📝

- [ ] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [ ] Frontend Dev React/Angular/Vue

<hr>

## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [x ] My changes generates no new warnings.
- [ x] I'm GWOC'21 contributor

<hr>

2021-11-01 18:17 UTC, heet-kumar requested changes
add this section at the bottom

2021-11-01 18:17 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/React/Week 2/Functionalandclasscomponents.md
> +
Try to add reference link at the bottom from where you have referred and created this PR.

2021-11-01 18:21 UTC, heet-kumar commented
@Drontitan this issue is from MERN Domain so you need to send this in MERN channel in Discord you have posted this issue in Frontend with Framework.

2021-11-01 18:26 UTC, heet-kumar commented
@anandhu720 this issue #1256 come under MERN Domain this PR is generated for the MERN domain.
already in our Domain one PR is already merged on this particular topic.

2021-11-02 04:18 UTC, Drontitan commented
@anandhu720 pls check the pr now i have made the changes what @heet-kumar have said

2021-11-02 04:22 UTC, anandhu720 commented
@Drontitan bro this issue was created for MERN branch i think so.Because this issue is already been created and merged in our branch can you please cross check it

2021-11-02 04:23 UTC, Drontitan commented
@anandhu720  means now this pr is wasted so i have to take new 😶

2021-11-02 04:23 UTC, Drontitan commented
can i close this pr

2021-11-02 04:26 UTC, closed without merging

2021-11-02 04:26 UTC, anandhu720 commented
sure.please check milestone 3 for our issues