Create Sort_two_array_without_extra_space.md
girlscript/winter-of-contributing pull request #7087
Opened 2021-11-01 07:17 UTC by vineetsingh0809

<hr>

## Description 📜
Added a problem in which given two sorted arrays, we need to merge them in O((n+m)*log(n+m)) time with O(1) extra space into a sorted array, when n is the size of the first array, and m is the size of the second array. 
Fixes #7069 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-01 10:49 UTC, deeqakkk requested changes
![image](https://user-images.githubusercontent.com/78724676/139660354-d05a6f80-131c-407a-a58a-21f4f9135783.png)
If you have used content from other websites do add their link as a referance.

2021-11-01 10:49 UTC, deeqakkk commented on C_CPP/Competitive Programming/Sort_two_array_without_extra_space.md
> +### EXAMPLE
use a borderless table to align them properly.

2021-11-01 10:49 UTC, deeqakkk commented on C_CPP/Competitive Programming/Sort_two_array_without_extra_space.md
> +### C++ Programm code of the Problem
fix this typo as well "Programm"

2021-11-01 10:50 UTC, apeksha235 requested changes
@vineetsingh0809 make these changes, also explain the algorithm in points for better clarity

2021-11-01 10:50 UTC, apeksha235 commented on C_CPP/Competitive Programming/Sort_two_array_without_extra_space.md
> +We start comparing elements that are far from each other rather than adjacent.
This is a shell sort algorithm, please mention it

2021-11-01 10:50 UTC, apeksha235 commented on C_CPP/Competitive Programming/Sort_two_array_without_extra_space.md
> +Time Complexity - O(n log n)
explain the time complexity in your own words

2021-11-01 15:32 UTC, vineetsingh0809 commented
Hey @deeqakkk and @apeksha235, changes are done, now review it again.

2021-11-03 08:57 UTC, apeksha235 reviewed
@vineetsingh0809 it seems like you've taken the code entirely from [here](https://www.geeksforgeeks.org/efficiently-merging-two-sorted-arrays-with-o1-extra-space/) 
you can definitely refer from different websites but taking the code entirely is not permitted. 
@Suvraneel

2021-11-03 08:57 UTC, apeksha235 commented on C_CPP/Competitive Programming/Sort_two_array_without_extra_space.md
> +Input: ar1[] = {25};
add the input and output inside ``` for better presentation

2021-11-03 11:51 UTC, Suvraneel commented
@vineetsingh0809  On second thought.... I'll let this be open... Use your own words... remove plagiarism

2021-11-03 14:40 UTC, closed without merging