C_CPP: Overloading Unary Operators Using 'friend' Functions
girlscript/winter-of-contributing pull request #7127
Opened 2021-11-01 18:17 UTC by 124015001

<hr>

## Description 📜

Explained about how to Overload Unary Operator with 'friend' functions. Also, performed a program as an example explaining the same.
Fixes #6547

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-11-01 18:20 UTC, 124015001 reviewed
corrected typos

2021-11-01 18:20 UTC, iam-sakshi commented
can I work on this issue?

2021-11-01 18:23 UTC, 124015001 commented
@iam-sakshi This is a pull request my friend. You can create an issue and assign it to yourself by writing '/assign' the same way.

2021-11-01 18:50 UTC, iam-sakshi commented
okay , sorry and thank you

2021-11-03 16:46 UTC, vasu-1 commented
> okay , sorry and thank you

you can create your own unique issue !!!

2021-11-03 16:54 UTC, vasu-1 requested changes
Changes Required

2021-11-03 16:54 UTC, vasu-1 commented on C_CPP/OOPs in C++/Operator Overloading/overloading-unary-operator.md
> +Here, the operator functions is not the member function of any class. Hence, in this scenario if an operator has to be overloaded to make it work on a class object, the operator function has to be de
```suggestion
Here, the operator function is not the member function of any class. Hence, in this scenario if an operator has to be overloaded to make it work on a class object, the operator function has to be declared as a **friend** to that class.  
```

2021-11-03 16:54 UTC, vasu-1 commented on C_CPP/OOPs in C++/Operator Overloading/overloading-unary-operator.md
> +The synatx for defining a friend operator function to overload an unary operator is as follows:
```suggestion
The syntax for defining a friend operator function to overload a unary operator is as follows:  
```

2021-11-03 16:54 UTC, vasu-1 commented on C_CPP/OOPs in C++/Operator Overloading/overloading-unary-operator.md
> +
```suggestion
*argument* -> is the formal argument referring to the class object on which the operator overloading is being done.  

Here's a program to overload a unary minus '-' operator using friend functions.  

```

2021-11-03 16:54 UTC, vasu-1 commented on C_CPP/OOPs in C++/Operator Overloading/overloading-unary-operator.md
> +*argument* -> is the formal argument referring to class object on which the operator overloading is being done.
```suggestion
- *friend* -> keyword to make a non-member function as a friend to a class  
- *return_type* -> type of the value returned by the friend operator function  
- *operator* -> keyword to create an operator function  
- *opr* -> unary operator that is to be overloaded  
- *argument* -> is the formal argument referring to class object on which the operator overloading is being done.  
```

do some markdown formatting like this.

2021-11-03 17:09 UTC, 124015001 reviewed
updated suggestions

2021-11-03 17:09 UTC, 124015001 commented
@vasu-1

2021-11-04 04:36 UTC, vasu-1 approved these changes
@Saviour1001

2021-11-04 08:12 UTC, merged