CSS Margin added
girlscript/winter-of-contributing pull request #7130
Opened 2021-11-01 19:15 UTC by darshan4903

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #issue_number_here 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-02 06:06 UTC, kashishahuja2002 requested changes

2021-11-02 06:06 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/CSS Margin/CSS Margin.md
> +### 👉🏽Syntax
Remove 👉🏽

2021-11-02 06:06 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/CSS Margin/CSS Margin.md
> +* https://developer.mozilla.org/en-US/docs/Web/CSS/margin
Embed the link in the name of website.

2021-11-02 07:52 UTC, darshan4903 commented
Updated @kashishahuja2002

2021-11-02 08:09 UTC, kashishahuja2002 approved these changes
LGTM.
Tag the supervisor of your batch to review and merge the PR.

2021-11-02 08:18 UTC, darshan4903 commented
@2024-SANDHYA please merge this PR

2021-11-02 08:39 UTC, 2024-SANDHYA commented on Web_Development/FrontEnd/CSS Margin/CSS Margin.md
> +There are properties for setting the margin for each side of an element (top, right, bottom, and left).
The sentence is not clear & understandable. Rephrase it. Also, don't use words like "you" "we".

2021-11-02 08:40 UTC, 2024-SANDHYA requested changes
Try to write clearly what you want to convey. Rest all is good !!

2021-11-02 16:05 UTC, darshan4903 commented
Updated @2024-SANDHYA

2021-11-07 12:49 UTC, 2024-SANDHYA approved these changes

2021-11-07 12:49 UTC, merged