Reversing a queue
girlscript/winter-of-contributing pull request #7169
Opened 2021-11-02 06:47 UTC by stutimohta20

<hr>

## Description 📜

Reversing a queue using cpp language.

Fixes #6722 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [X] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-02 06:56 UTC, stutimohta20 commented
@Suvraneel .Please review.

2021-11-02 07:51 UTC, Suvraneel requested changes
After you're done ...
Tag **apeksha235** or **vasu-1**

2021-11-02 07:51 UTC, Suvraneel commented on C_CPP/Data Structures/Queue/readme.md
> +- [Reversing a queue](https://github.com/stutimohta20/winter-of-contributing/blob/C_CPP/C_CPP/Data%20Structures/Queue/Reversingqueue.md)
Dont you get any hint from the lines above yours?!

Relative link ONLY

2021-11-02 07:51 UTC, Suvraneel commented on C_CPP/Data Structures/Queue/Reversingqueue.md
> +```
- You've given absolutely NO documentation
- Use syntax highlighting
- Use comments

2021-11-07 17:57 UTC, stutimohta20 commented
@vasu-1 Please review.

2021-11-08 03:54 UTC, vasu-1 requested changes
Do Require Changes

2021-11-08 03:54 UTC, vasu-1 commented on C_CPP/Data Structures/Queue/readme.md
> +- [Reversing a queue](C_CPP/Data Structures/Queue/Reversingqueue.md)
```suggestion
- [Reversing a queue](./Reversingqueue.md)
```

2021-11-08 03:54 UTC, vasu-1 commented on C_CPP/Data Structures/Queue/Reversingqueue.md
> +
```suggestion
```

Remove unwanted empty lines

2021-11-08 03:54 UTC, vasu-1 commented on C_CPP/Data Structures/Queue/Reversingqueue.md
> +// Main Function
```suggestion
// Main Function
```

2021-11-08 03:54 UTC, vasu-1 commented on C_CPP/Data Structures/Queue/Reversingqueue.md
> +// Printing the Queue
```suggestion
// Printing the Queue
```

2021-11-08 03:54 UTC, vasu-1 commented on C_CPP/Data Structures/Queue/Reversingqueue.md
> +```
```suggestion
```cpp
```
For syntax highlighting

2021-11-08 03:54 UTC, vasu-1 commented on C_CPP/Data Structures/Queue/Reversingqueue.md
> +
```suggestion
        
```

2021-11-08 06:07 UTC, stutimohta20 commented
@vasu-1 .Made the suggested changes please review once.

2021-11-08 10:31 UTC, vasu-1 approved these changes
LGMT @stutimohta20 

@Suvraneel

2021-11-09 05:12 UTC, stutimohta20 commented
Thank you :)

2021-11-09 11:23 UTC, Suvraneel requested changes

2021-11-09 11:23 UTC, Suvraneel commented on C_CPP/Data Structures/Queue/Reversingqueue.md
> +#include<bits/stdc++.h>
```suggestion

// Header Files
#include<bits/stdc++.h>
```

Function comments just on line above fx

2021-11-09 11:23 UTC, Suvraneel commented on C_CPP/Data Structures/Queue/Reversingqueue.md
> +void reverseQueue(queue<int>& q)
```suggestion
// Function for reversing the Queue
void reverseQueue(queue<int>& q)
```
Remove extra newlines

2021-11-09 11:23 UTC, Suvraneel commented on C_CPP/Data Structures/Queue/Reversingqueue.md
> +void printQueue(queue<int>& q)
```suggestion
}

// Printing the Queue
void printQueue(queue<int>& q)
```

2021-11-09 11:23 UTC, Suvraneel commented on C_CPP/Data Structures/Queue/Reversingqueue.md
> +int main()
```suggestion
}

// Main Function
int main()
```

2021-11-09 11:23 UTC, Suvraneel commented on C_CPP/Data Structures/Queue/Reversingqueue.md
> +To perform the reversing of a queue ,we first stored it in a stack and then re-inserted it in the queue.
```suggestion
To perform the reversing of a queue ,we first stored it in a stack and then re-inserted it in the queue.
```

* Store the elements
in what order ?

How does this re-insert affect the order
I mean elaborate this one-liner properly..
Ofc its simple but still elaborate as much as you can

2021-11-09 12:30 UTC, stutimohta20 commented
Made the changes.

2021-11-09 12:45 UTC, Suvraneel commented
@stutimohta20  Excellent ❤️  LGTM 🚀  :octocat:

2021-11-09 12:47 UTC, merged