React 6.1 -> Multi Page React App
girlscript/winter-of-contributing pull request #7203
Opened 2021-11-02 16:21 UTC by shreya024

<hr>

## Description 📜

Added Examples and Documentation along with output for React Router.
Fixes #6872 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-02 16:46 UTC, anandhu720 requested changes

2021-11-02 16:46 UTC, anandhu720 commented on Frontend_Web_Development_React_Angular_Vue/React/Week 6/Multi Page React App.md
> +- A Multi Page React App helps to add various other advanced functionalities like Lazy Loading,Flexible Routing Code with query params and Dynamic as well as Nested Routes for enhancing user experien
Please always add reference links at bottom

2021-11-02 16:48 UTC, heet-kumar requested changes
@shreya024  add references at the bottom

2021-11-03 00:56 UTC, shreya024 commented
Okay. I have added the references. Kindly check now.

2021-11-03 04:29 UTC, anandhu720 approved these changes

2021-11-03 04:29 UTC, merged