Create Application of Box-Model in CSS.md
girlscript/winter-of-contributing pull request #7241
Opened 2021-11-03 13:13 UTC by varnikarathee

<hr>

## Description 📜Application of Box-Model in CSS

Fixes #6941 
<hr>

## Type of change 📝Application of Box-Model in CSS

- [X ] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [X] Frontend Dev #HTML/CSS/JS

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

2021-11-03 14:21 UTC, 2024-SANDHYA requested changes
Image credit & external links missing

2021-11-03 15:51 UTC, kashishahuja2002 requested changes

2021-11-03 15:51 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/CSS_BoxModel/Application of Box-Model in CSS.md
> +![image](https://user-images.githubusercontent.com/77229404/140058998-66e64981-6773-4215-82d6-e446a07fa4cd.png)
Add reference source for image.

2021-11-03 15:51 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/CSS_BoxModel/Application of Box-Model in CSS.md
> +![image](https://user-images.githubusercontent.com/77229404/140059134-786cc5bf-4a9d-407f-bdf5-b9a3f574ced7.png)
Add reference source for the image.

2021-11-03 15:51 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/CSS_BoxModel/Application of Box-Model in CSS.md
> +![image](https://user-images.githubusercontent.com/77229404/140059207-32f84ca7-99c2-4495-bd2c-436f4f6dbc72.png)
Add reference source for the image.

2021-11-03 17:42 UTC, varnikarathee commented
@kashishahuja2002 I had a doubt, here actually all the images are created by me in paint, then what will be the reference source in that case?

2021-11-04 06:54 UTC, 2024-SANDHYA commented
> 
> 
> @kashishahuja2002 I had a doubt, here actually all the images are created by me in paint, then what will be the reference source in that case?

Then no need to mention the image credits, Just mention the reference links.

2021-11-05 18:06 UTC, varnikarathee commented
@2024-SANDHYA actually the whole content is written by me . I haven't copied it from any source . Do i still need to mention any reference link ?

2021-11-05 19:31 UTC, kashishahuja2002 commented
> @2024-SANDHYA actually the whole content is written by me . I haven't copied it from any source . Do i still need to mention any reference link ?

Taking reference doesn't mean coping. You might have studied it from somewhere, and put it in your own words. So, you need to mention that link here.

2021-11-06 08:55 UTC, varnikarathee commented
@kashishahuja2002 I have added external reference links. Kindly review.

2021-11-07 06:36 UTC, kashishahuja2002 approved these changes
LGTM

2021-11-07 12:04 UTC, varnikarathee commented
@2024-SANDHYA Please merge my pr if all seems good to the team.

2021-11-07 12:50 UTC, 2024-SANDHYA approved these changes

2021-11-07 12:50 UTC, merged