Css image reflection
girlscript/winter-of-contributing pull request #7246
Opened 2021-11-03 14:50 UTC by Dezyl1641

<hr>

## Description 📜

I fixed the issue regarding CSS Image Reflection and explained the topic in detail.
Fixes #6795 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

2021-11-03 15:57 UTC, kashishahuja2002 requested changes
Change code indentation to 4 spaces and add a reference to all the images just below it.

Remove all the binary files, drag and drop images to add them into the md file.

2021-11-03 15:57 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> +	-webkit-box-reflect: below;
Change the indentation to 4 spaces.

2021-11-03 15:57 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> +</ul>
Use markdown syntax instead of md.
Embed the reference link in the name of the website.

2021-11-03 15:57 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> +## Credits
Change it to references.

2021-11-03 15:57 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> +
Remove these lines.

2021-11-05 15:57 UTC, kashishahuja2002 requested changes
Remove all the binary files, drag and drop them into the md file directly.

2021-11-05 19:32 UTC, kashishahuja2002 requested changes
Remove  Web_Development/FrontEnd/HTML and Web_Development/FrontEnd/HTML: Search Engine Optimization Basics.md files.

2021-11-07 06:29 UTC, kashishahuja2002 approved these changes
LGTM.

2021-11-08 08:39 UTC, praveenscience requested changes
Please fix these and it's good to go.

2021-11-08 08:39 UTC, praveenscience commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> +**box-reflect** can hold the following values:
- Use one line space after and before the headings.
- Use one line space after and before paragraphs.
- Don't use `<br>`.
- Give code inside `inline code` not using **bold**.

2021-11-08 08:39 UTC, praveenscience commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> +}
If possible, indent them using 2 spaces, and give a space before starting `{`.

2021-11-08 08:39 UTC, praveenscience commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> +![Screenshot 2021-11-03 023324](https://user-images.githubusercontent.com/73912907/140558861-98dcdb37-9609-4e8c-834a-746925056f92.png)
Give a meaningful name to the `alt` tag.

2021-11-08 08:39 UTC, praveenscience commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> +}
If possible, indent them using 2 spaces, and give a space before starting `{`.

2021-11-08 08:39 UTC, praveenscience commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> +}
If possible, indent them using 2 spaces, and give a space before starting `{`.

2021-11-08 08:39 UTC, praveenscience commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> +}
If possible, indent them using 2 spaces, and give a space before starting `{`.

2021-11-08 08:39 UTC, praveenscience commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> + - [W3schools](https://www.w3schools.com/css/css3_image_reflection.asp)
Do not use W3Schools as a reference. Use Web Platform docs or MDN.

2021-11-08 08:39 UTC, praveenscience commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> +![Screenshot 2021-11-03 023240](https://user-images.githubusercontent.com/73912907/140559132-0a16f47b-a25d-40da-b540-a3f84e0b6e78.png)
Give a meaningful name to the `alt` tag.

2021-11-08 08:39 UTC, praveenscience commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> +![Screenshot 2021-11-03 023547](https://user-images.githubusercontent.com/73912907/140559178-b71001e3-9949-4913-a784-678256813756.png)
Give a meaningful name to the `alt` tag.

2021-11-08 08:40 UTC, praveenscience commented
Please make sure to revert the deleted lines on the description to get this merged as well. Thanks. 😊

2021-11-10 22:33 UTC, praveenscience requested changes

2021-11-10 22:33 UTC, praveenscience commented on Web_Development/FrontEnd/CSS Image Reflection/CSS_Image_Reflection.md
> + - [W3schools](https://www.w3schools.com/css/css3_image_reflection.asp)
Can you please resolve this? 🤔

2021-11-13 15:59 UTC, sifa123 approved these changes
Well done!! I think now we can merge this @praveenscience

2021-11-15 05:49 UTC, merged