Create Middle_Element_Of_Singly_Linked_List_C++.md
girlscript/winter-of-contributing pull request #7261
Opened 2021-11-03 21:27 UTC by ritika168

<hr>

## Description 📜

I have explained how to find the middle element in a singly linked list with proper code and examples.
Fixes #issue_number_here 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-11-03 21:34 UTC, ritika168 commented
@apeksha235 @Saviour1001 @Suvraneel please review!

2021-11-04 05:18 UTC, Suvraneel commented
@gunjan-g

2021-11-04 07:10 UTC, vasu-1 requested changes
Changes Required !

Do comment in the code !

Happy Diwali !!

2021-11-04 07:10 UTC, vasu-1 commented on C_CPP/Data Structures/Linked List/Singly Linked List (Normal Linked List)/Middle_Element_Of_Singly_Linked_List_C++.md
> +A singly linked list which is inputed by user.
```suggestion
Singly linked lists which are inputed by user.  
```

2021-11-04 07:10 UTC, vasu-1 commented on C_CPP/Data Structures/Linked List/Singly Linked List (Normal Linked List)/Middle_Element_Of_Singly_Linked_List_C++.md
> +* Create the Linked list by inputing the data value given by user.
```suggestion
* Create the Linked list by inputting the data value given by user.
```

2021-11-04 07:10 UTC, vasu-1 commented on C_CPP/Data Structures/Linked List/Singly Linked List (Normal Linked List)/Middle_Element_Of_Singly_Linked_List_C++.md
> +* Traverse the whole linked list and calculate the number of nodes in that list. Lets say : n nodes are there.
```suggestion
* Traverse the whole linked list and calculate the number of nodes in that list. Let's say : n nodes are there.
```

2021-11-04 08:05 UTC, ritika728 commented
Happy Diwali! 🪔
@vasu-1 I have made the required changes.

2021-11-04 11:28 UTC, Suvraneel commented
@ritika728  LGTM 👍🏻  💯

2021-11-04 11:28 UTC, merged