React 6.3 -> Good Coding Practices
girlscript/winter-of-contributing pull request #7263
Opened 2021-11-04 02:14 UTC by shreya024

<hr>

## Description 📜

Added code and documentation for Good Coding Practices. 
Fixes #6925 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-04 03:22 UTC, anandhu720 requested changes

2021-11-04 03:22 UTC, anandhu720 commented on Frontend_Web_Development_React_Angular_Vue/React/Week 6/Good Coding Practices.md
> +- **Reusability** : Code Reusability can be schieved in React with the help of reusable components.
Spelling mistake

2021-11-04 03:23 UTC, anandhu720 requested changes

2021-11-04 03:23 UTC, anandhu720 commented on Frontend_Web_Development_React_Angular_Vue/React/Week 6/Good Coding Practices.md
> +<h1 align="center">  Good Coding Practices </h1>
I think you can also add some details of folder structers also

2021-11-04 05:28 UTC, shreya024 commented
@anandhu720 Sure, I have made the suggested changes. Kindly check now.

2021-11-04 07:30 UTC, heet-kumar approved these changes
@shreya024  Nice PR LGTM! let's wait for the supervisor approval if they suggest any more changes then include that changes to.

2021-11-04 08:34 UTC, shreya024 commented
@heet-kumar Okay and thank you.

2021-11-06 04:02 UTC, anandhu720 approved these changes

2021-11-06 04:02 UTC, merged