m-coloring Problem
girlscript/winter-of-contributing pull request #7271
Opened 2021-11-04 07:16 UTC by am-dusky

<hr>

## Description 📜

I have discussed the approach to solve m-coloring problem. I have also provided the code for that.
Fixes #6806 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-11-04 14:37 UTC, apeksha235 requested changes
@am-dusky add the relative links to your file inside the readme of ```m-coloring``` folder

2021-11-04 14:37 UTC, apeksha235 commented on C_CPP/Algorithmic Approaches/Backtracking/m-coloring/mColoring.cpp
> +    return 0;
please add an input and output example for your code

2021-11-04 14:37 UTC, apeksha235 commented on C_CPP/Algorithmic Approaches/Backtracking/m-coloring/theory.md
> +> Time complexity : O(nm^n)
explain time complexity

2021-11-05 08:40 UTC, am-dusky commented
@apeksha235 I have made all the changes . kindly see !!

2021-11-05 10:34 UTC, gunjan-g requested changes
@am-dusky Please do the required changes

2021-11-05 10:34 UTC, gunjan-g commented on C_CPP/Algorithmic Approaches/Backtracking/m-coloring/m.txt
> +4
Delete this file m.text, you've already included input in your code and remove it from readme as well

2021-11-05 10:34 UTC, gunjan-g commented on C_CPP/Algorithmic Approaches/Backtracking/m-coloring/mColoring.cpp
> +                break;
Make it properly indented, like this
                if(graph[k][j]==1 and x[j]==x[k]) //colour adjacent to it have same colour
                break;

2021-11-05 10:34 UTC, gunjan-g commented on C_CPP/Algorithmic Approaches/Backtracking/m-coloring/mColoring.cpp
> +Example graph */
Please provide spaces for code to be more readable

2021-11-05 10:34 UTC, gunjan-g commented on C_CPP/Algorithmic Approaches/Backtracking/m-coloring/theory.md
> +![image](image1.png)
Provide a space between images and text too

2021-11-05 10:34 UTC, gunjan-g commented on C_CPP/Algorithmic Approaches/Backtracking/m-coloring/theory.md
> +			if(graph[k][j]==1 and x[j]==x[k]) //colour adjacent to it have same colour
```suggestion
			if(graph[k][j]==1 and x[j]==x[k]) //colour adjacent to it have same colour
			break;
```

2021-11-05 10:34 UTC, gunjan-g commented on C_CPP/Algorithmic Approaches/Backtracking/m-coloring/theory.md
> +			if(graph[k][j]==1 and x[j]==x[k]) //colour adjacent to it have same colour
```suggestion
			if(graph[k][j]==1 and x[j]==x[k]) //colour adjacent to it have same colour
```
Indent this too

2021-11-05 10:34 UTC, gunjan-g commented on C_CPP/Algorithmic Approaches/Backtracking/m-coloring/theory.md
> + The number of internal nodes in the state space tree is $\sum_{i=0}^{n-1} m_i$ = (m<sup>n</sup>-1)/(m-1) .At each internal node , O(mn) time is spent by NextValue function. Hence the total time is O
The symbols are not readable

2021-11-05 18:20 UTC, am-dusky commented
@gunjan-g  I have made all the changes , Kindly see it!

2021-11-05 18:31 UTC, gunjan-g requested changes
@am-dusky please rectify these too and then you're good to go

2021-11-05 18:31 UTC, gunjan-g commented on C_CPP/Algorithmic Approaches/Backtracking/m-coloring/theory.md
> +			if(graph[k][j]==1 and x[j]==x[k]) //colour adjacent to it have same colour
@am-dusky Just place break below if statement, they are not indented correctly,

2021-11-05 18:31 UTC, gunjan-g commented on C_CPP/Algorithmic Approaches/Backtracking/m-coloring/theory.md
> +			if(graph[k][j]==1 and x[j]==x[k]) //colour adjacent to it have same colour
@am-dusky Here too, break below if with proper indentation

2021-11-05 18:31 UTC, gunjan-g commented on C_CPP/Algorithmic Approaches/Backtracking/m-coloring/theory.md
> +At each internal node , O(mn) time is spent by NextValue function. Hence the total time is
```suggestion
At each internal node , O(mn) time is spent by NextValue function. Hence the total time is   
```
Put a space above this line

2021-11-05 19:03 UTC, gunjan-g approved these changes
@Saviour1001 @Suvraneel LGTM 🚀

2021-11-05 19:22 UTC, merged