Frontend web development html css js
girlscript/winter-of-contributing pull request #7274
Opened 2021-11-04 09:58 UTC by Yashesvinee

<hr>

## Description 📜

Added documentation of CSS web fonts
Fixes #7262 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-04 10:02 UTC, Yashesvinee commented
@2024-SANDHYA

2021-11-09 06:43 UTC, 2024-SANDHYA requested changes
Please do the needful & reopen the same PR closing this for now so you can work.

2021-11-09 06:43 UTC, 2024-SANDHYA commented on Web_Development/FrontEnd/CSS_web_fonts.md
> +This font can be defined within the CSS ` @font-face ` rule.
Not the exact correct definition. Web fonts are more than this, please include more information & also mention about importing Google Fonts into HTML & CSS file

2021-11-09 06:43 UTC, 2024-SANDHYA commented on Web_Development/FrontEnd/CSS_web_fonts.md
> +
Remove so many indentations, please write in a proper manner. The final output doesn't look good.

![image](https://user-images.githubusercontent.com/75671152/140874851-713b1087-1b2a-411f-b510-28523622dba1.png)

2021-11-09 06:43 UTC, 2024-SANDHYA commented on Web_Development/FrontEnd/CSS_web_fonts.md
> + Learn more about ` @font-face ` [here](https://www.digitalocean.com/community/tutorials/css-font-face).
Remove this, rather make a heading "reference links" & under that mention the website.

2021-11-09 16:34 UTC, 2024-SANDHYA approved these changes

2021-11-09 16:34 UTC, merged