JS Bitwise Operators: Documentation
girlscript/winter-of-contributing pull request #7311
Opened 2021-11-05 15:27 UTC by prishit55

<hr>

## Description 📜
I've made a new file in "JavaScript" called "JavaScript Bitwise Operators", and under that file a md file called "Js Bitwise" which is a brief discussion about various bitwise operators in Js has been created.

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] Frontend Dev HTML/CSS/JS
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-09 10:03 UTC, kashishahuja2002 requested changes
Good work.

2021-11-09 10:03 UTC, kashishahuja2002 commented on Web_Development/Javascript/JavaScript Bitwise Operator/JS Bitwise.md
> +### 6. Right Shift
Wrong level of heading, use ##

2021-11-09 20:57 UTC, prishit55 commented on Web_Development/Javascript/JavaScript Bitwise Operator/JS Bitwise.md
> +### 6. Right Shift
Done !!

2021-11-10 06:23 UTC, kashishahuja2002 approved these changes
LGTM. Tag the supervisor of your batch for further reviewing and merging the PR.

2021-11-11 13:53 UTC, merged