Competitive programming
girlscript/winter-of-contributing pull request #7369
Opened 2021-11-06 08:39 UTC by iam-sakshi

<hr>

## Description 📜
Summary : In this documentation , Binary Search simple applications are demonstrated with the aim that it can help others to look for binary search in competitive programming for other uses too . In this documentation , the requirement of Binary Search is discussed and programs like:
- first occurrence
- last occurrence
- Count of the element 
- floor of the element
- Ceil of the element
the programming language used in this is C++.
issue name :Competitive Programming : Binary Search  
issue number : #7131

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [x] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-07 18:17 UTC, iam-sakshi commented
please review my PR

2021-11-08 04:40 UTC, ravireddy07 requested changes
Please update the following things:

* remove spaces in filename, rename it to like `BinarySearch.md`.
* Can you explain the more on each sub-topic, like what exactly floor/ceil in this binary search doc and how it's related.
* add this explanation on top and code below. Like: Title->explanation->code...
* Add complexity's to each approach.

2021-11-08 18:12 UTC, iam-sakshi commented
okay

2021-11-09 05:47 UTC, ravireddy07 requested changes

2021-11-09 05:47 UTC, ravireddy07 commented on Competitive_Programming/C++/Searching & Sorting/Binary Search/BinarySearchApplication.md
> +Explanation:
```suggestion
## Approach:
```

2021-11-09 05:47 UTC, ravireddy07 commented on Competitive_Programming/C++/Searching & Sorting/Binary Search/BinarySearchApplication.md
> +- Similarily we can approach ceil, as we know ceil is the smallest greater element than the element for which we want to find ceil.
Place this above the code

2021-11-09 05:47 UTC, ravireddy07 commented on Competitive_Programming/C++/Searching & Sorting/Binary Search/BinarySearchApplication.md
> +These are some of the programs that can be solve by Binary Search , Binary search is really important in competitve programming as it do the searching in O(log (n)) time .
Add this complexity with title.

2021-11-09 05:47 UTC, ravireddy07 commented on Competitive_Programming/C++/Searching & Sorting/Binary Search/BinarySearchApplication.md
> +These are some of the programs that can be solve by Binary Search , Binary search is really important in competitve programming as it do the searching in O(log (n)) time .
```suggestion
## Complexity
These are some of the programs that can be solve by Binary Search , Binary search is really important in competitve programming as it do the searching in ```O(log (n))``` time .
```

2021-11-09 17:27 UTC, iam-sakshi commented
Done all the suggested changes.

2021-11-10 04:33 UTC, ravireddy07 requested changes
please change following things;

* Add formatted code.
* Place the explanation above and the code below.

Hope you got this.

2021-11-10 04:33 UTC, ravireddy07 commented on Competitive_Programming/C++/Searching & Sorting/Binary Search/BinarySearchApplication.md
> +>Title -> explanation -> code -> Time Complexity
remove this

2021-11-10 06:55 UTC, iam-sakshi commented
Done

2021-11-10 09:58 UTC, ravireddy07 approved these changes

2021-11-10 09:58 UTC, ravireddy07 commented
Good work @iam-sakshi  👍

2021-11-10 10:04 UTC, ravireddy07 commented
@iam-sakshi  Please Update the status of PR in PR Tracksheet

2021-11-14 13:33 UTC, merged