Trie : Introduction and Implementation
girlscript/winter-of-contributing pull request #7388
Opened 2021-11-06 12:30 UTC by shreya024

<hr>

## Description 📜

Added Documentation and Implementation of User Defined Data Structure Trie along with code.
Fixes #7228  

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-07 16:11 UTC, apeksha235 requested changes
@shreya024

2021-11-07 16:11 UTC, apeksha235 commented on C_CPP/Data Structures/User Defined Data Structures/Trie/Trie.md
> +<h1 align="center">  Trie or Prefix Tree </h1>
avoid using html tags for markdown formatting refer [this](https://www.markdownguide.org/basic-syntax/) instead

2021-11-08 00:31 UTC, shreya024 commented
@apeksha235 I have made the suggested change. Kindly check now.

2021-11-09 10:05 UTC, apeksha235 approved these changes
@shreya024 amazing!
@Saviour1001 please merge this

2021-11-09 10:38 UTC, shreya024 commented
@apeksha235 Thank you :)

2021-11-09 11:00 UTC, merged