Undefined Behaviour in C/CPP
girlscript/winter-of-contributing pull request #7428
Opened 2021-11-07 09:41 UTC by elixir14082002

<hr>

## Description 📜

Added a documentation on Undefined Behaviour in C/CPP.
#7424

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-07 09:42 UTC, elixir14082002 commented
@Suvraneel Please review my PR!

2021-11-07 17:24 UTC, vasu-1 requested changes

2021-11-07 17:24 UTC, vasu-1 commented on C_CPP/Fundamentals/Undefined Behaviour/Undefined-Behaviour.md
> +The above are the few common mistakes which lead to undefined behaviour. There are also other reasons that that lead to this kind of behaviour.
```suggestion
The above are the few common mistakes which lead to undefined behaviour. There are also other reasons that lead to this kind of behaviour.
```

2021-11-08 00:44 UTC, elixir14082002 commented
@vasu-1 @Suvraneel I made the required changes.

2021-11-08 10:26 UTC, vasu-1 requested changes
.

2021-11-08 10:29 UTC, vasu-1 approved these changes
LGMT @elixir14082002 

@Saviour1001 Please Check it for Once !

2021-11-09 11:14 UTC, merged