What is subarray & subsequence?
girlscript/winter-of-contributing pull request #7437
Opened 2021-11-07 12:42 UTC by Nandani-koli

<hr>

## Description 📜

What is Subarray and Subsequence.
Program to print subarray and subsequence
Fixes #7036 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

2021-11-07 15:54 UTC, apeksha235 requested changes
@Nandani-koli

2021-11-07 15:54 UTC, apeksha235 commented on C_CPP/Data Structures/Array/Subarray&Subsequence.md
> +*A subsequence is defined as a sequence that can be derived from an array by selecting zero or more elements without changing the order of the remaining elements.*
mention the formula for subsequence

2021-11-07 15:54 UTC, apeksha235 commented on C_CPP/Data Structures/Array/Subarray&Subsequence.md
> +
mention the time complexity as well

2021-11-08 05:10 UTC, Nandani-koli commented
@apeksha235 Thank you ma'am. I updated file.

2021-11-09 12:25 UTC, deeqakkk requested changes
Nandani, avoid using HTML stuff here(, it's not a good practice.
your code has so manyyyy nbsp, fix that.

2021-11-09 16:20 UTC, Nandani-koli commented
@deeqakkk Thank you sir, I have made changes

2021-11-10 07:57 UTC, apeksha235 commented
@Nandani-koli amazing! 
@Saviour1001 please merge this

2021-11-10 10:40 UTC, merged