[JS] Topic: Tutorial for JavaScript Operators Fixed #202
girlscript/winter-of-contributing pull request #748
Opened 2021-09-18 18:03 UTC by Himanshu664

## Description 📜

Created a tutorial for operators in JavaScript.
Fixes #202 

<hr>

## Type of change 📝

- [ ] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev (Flutter, Java, Kotlin)
- [ ] Backend Dev (Java, .NET, Python)
- [ ] C/CPP
- [ ] Competitive Programming
- [ ] Cyber Security
- [ ] DSA
- [ ] Database
- [ ] Datascience with Python
- [ ] Datascience with R
- [ ] Frontend Dev (HTML, CSS, JS)
- [ ] Frontend Dev (React, Angular, Vue)
- [ ] Golang
- [ ] Interview Prep
- [ ] Java
- [x] JavaScript
- [ ] MERN
- [ ] Machine Learning
- [ ] Open Source
- [ ] Python
- [ ] Rust
- [ ] Statistics
- [ ] UI/UX

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-09-18 18:06 UTC, Himanshu664 commented
@paramsiddharth as you suggested in todays meet I have close my previous PR,and created a fresh PR made changes as you told me.

2021-09-19 06:01 UTC, paramsiddharth requested changes

2021-09-19 06:01 UTC, paramsiddharth commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/README.md
> +                   alert(x + y);
The unwanted indentation is still there!

2021-09-19 06:01 UTC, paramsiddharth commented on Web_Development/Javascript/Topics/5.Syntax/2.Operators/README.md
> +		       0utput : 14
It should be Output, not 0utput!
Also, the output should be outside the syntax-highlighted code-block.

2021-09-19 06:49 UTC, Himanshu664 commented
@paramsiddharth Please review changes.

2021-09-20 04:55 UTC, paramsiddharth approved these changes
@Creatoon @dakshsethi @s4-2 Please review further.

2021-09-20 05:05 UTC, s4-2 approved these changes

2021-09-20 05:06 UTC, s4-2 commented
@Himanshu664 very well structured. I have reviewed and approved it. Keep it up:-)

2021-09-21 12:13 UTC, dakshsethi requested changes

2021-09-22 06:54 UTC, merged