Create CSS-Position-Properties.md
girlscript/winter-of-contributing pull request #7554
Opened 2021-11-08 13:50 UTC by Jaya3112

<hr>

## Description 📜

CSS Position Properties #6561

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #HTML/CSS/JS

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

2021-11-08 13:52 UTC, SauravMukherjee44 approved these changes

2021-11-08 14:00 UTC, praveenscience requested changes
Kindly make the following requested changes.

@SauravMukherjee44 How did you miss these? We're doing a Markdown not a text document.

/cc @2024-SANDHYA @salil-naik @kashishahuja2002

2021-11-08 19:22 UTC, kashishahuja2002 requested changes
Can you also add some SS for better understanding?

2021-11-09 08:17 UTC, praveenscience requested changes

2021-11-09 08:17 UTC, praveenscience commented on Web_Development/FrontEnd/CSS-Position-Properties.md
> +```
Should be for all:

    ```css

2021-11-09 08:17 UTC, praveenscience commented on Web_Development/FrontEnd/CSS-Position-Properties.md
> +  ## 2.  Relative Position:
The space is messing it up.

2021-11-09 12:40 UTC, praveenscience approved these changes
There are too many grammatical changes, but go for it. 😅

2021-11-09 12:40 UTC, merged