What_is_Encapsulation_in_cpp(A).md
girlscript/winter-of-contributing pull request #7572
Opened 2021-11-08 15:56 UTC by miraj0507

<hr>

## Description 📜

What is Encapsulation in Object-Oriented Programming Languages?
Detailed discussion about the use of encapsulation to hide data.
Fixes #7567

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)

<hr>

## Domain of Contribution 📊

- [x] C/#CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-17 15:30 UTC, Suvraneel commented
@gunjan-g @ChetasShree

2021-11-17 15:33 UTC, Suvraneel commented
@miraj0507  Kindly follow proper PR template directives from next time... You had to remove that hashtag from domain `C/CPP`... Consequently, this wasn't labelled as CPP... And it didn't show up in the mentors/sups feed

2021-11-17 17:00 UTC, vasu-1 requested changes
- Do some markdown Formatting !
- Add your md file link in the respective folder's `readme.md`


Audio is LGTM @miraj0507

2021-11-18 14:13 UTC, miraj0507 commented
> * Do some markdown Formatting !
> * Add your md file link in the respective folder's `readme.md`
> 
> Audio is LGTM @miraj0507

I have successfully made the changes

2021-11-18 14:17 UTC, gunjan-g requested changes
@miraj0507 Please do the required changes

2021-11-18 14:17 UTC, gunjan-g commented on C_CPP/OOPs in C++/Encapsulation/What_is_Encapsulation_in_cpp(A).md
> +WHY THERE WAS A NEED FOR ENCAPSULATION?<br />
```suggestion
WHY THERE WAS A NEED FOR ENCAPSULATION?<br /> <br/>
```

2021-11-18 14:17 UTC, gunjan-g commented on C_CPP/OOPs in C++/Encapsulation/What_is_Encapsulation_in_cpp(A).md
> +2)How is it used as a mechanism to restrict certain action of classes outsite the scope are discussed in the audio.<br />
```suggestion
2)How is it used as a mechanism to restrict certain action of classes outsite the scope are discussed in the audio.<br /> <br/>
```

2021-11-18 14:17 UTC, gunjan-g commented on C_CPP/OOPs in C++/Encapsulation/What_is_Encapsulation_in_cpp(A).md
> +[Getting started with oops? Understand Encapsulation.](https://drive.google.com/file/d/1WmftmYcTooSUnkA6lU3iOG3HfsXiVm0n/view?usp=sharing)
```suggestion
[Getting started with OOPS? Understand Encapsulation.](https://drive.google.com/file/d/1WmftmYcTooSUnkA6lU3iOG3HfsXiVm0n/view?usp=sharing)
```

2021-11-18 14:22 UTC, gunjan-g approved these changes
@Suvraneel @Saviour1001 LGTM 🚀

2021-11-18 18:47 UTC, merged