Frontend web development html css js
girlscript/winter-of-contributing pull request #7600
Opened 2021-11-08 19:30 UTC by Shreya241

<hr>

## Description 📜

Documentation added for HTML multimedia.
Fixes #7595

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-09 06:17 UTC, 2024-SANDHYA requested changes
You need to create .md file not .txt

2021-11-09 06:24 UTC, Shreya241 commented
I have created both .md and .txt file.
I will delete the .txt file.

2021-11-09 06:27 UTC, Shreya241 commented
@2024-SANDHYA I have deleted that txt file, now can u pls merge my PR.

2021-11-09 06:35 UTC, 2024-SANDHYA requested changes
Add relevant content which explains the use of multimedia & code for the same, there's a lot more under this topic such go through it once and do the needful. Closing the PR here once done just ping me here or on the server

2021-11-09 06:35 UTC, 2024-SANDHYA commented on Web_Development/FrontEnd/HTML_Multimedia/README.md
> +It can be anything you can hear or see, such as photos, music, sound, videos, records, films, animations, and so on. Web sites frequently incorporate multimedia content of various sorts and formats.
Add this under one heading.

2021-11-09 06:35 UTC, 2024-SANDHYA commented on Web_Development/FrontEnd/HTML_Multimedia/README.md
> +|WebM| .webm | Mozilla, Opera, Google, and Adobe collaborated to create this format. HTML5 is compliant. |
No need of such huge tables, this can be found on any other website as well

2021-11-09 06:35 UTC, 2024-SANDHYA commented on Web_Development/FrontEnd/HTML_Multimedia/README.md
> +
Remove these two tables.

2021-11-09 07:49 UTC, Shreya241 commented
Ok, i will add the changes

2021-11-12 11:05 UTC, Shreya241 commented
@2024-SANDHYA Hey I have made all the changes and added new content, can u pls now open my PR and accept it.

2021-11-12 12:13 UTC, Shreya241 commented
The changes are there in my forked repo. I think now you can see the chnages??

2021-11-12 12:32 UTC, 2024-SANDHYA commented
Oh my goodness only 2.42% of the content is unique means the rest 97.58% is plagiarized 😱 . Not Acceptable at all !! Closing the PR here itself.

![image](https://user-images.githubusercontent.com/75671152/141467764-7f76ded9-e5a9-4819-8f1e-05a74204c512.png)

2021-11-12 12:32 UTC, closed without merging