C_CPP: Overloading Unary Operators Using Member Functions
girlscript/winter-of-contributing pull request #7726
Opened 2021-11-11 03:28 UTC by 124015001

<hr>

## Description 📜

Explained the use of Member Function in Overloading a Unary Operator. Also, performed a program explaining the same.
Fixes #7454 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-11-11 16:11 UTC, apeksha235 requested changes
@124015001

2021-11-11 16:11 UTC, apeksha235 commented on C_CPP/OOPs in C++/Operator Overloading/overloading-unary-operators-using-member-functions.md
> +### *Output*
@124015001 please fix the alignment

![image](https://user-images.githubusercontent.com/84583787/141330712-a0f33dfe-0749-4ec7-8232-c9a05f47acbb.png)

also please add all the output inside ``` highlighter

2021-11-11 16:28 UTC, 124015001 reviewed
updated file

2021-11-11 16:36 UTC, 124015001 commented
@apeksha235 I didn't add highlighter in the output because then it will show the whole output in a single line.

2021-11-12 16:51 UTC, apeksha235 commented
@124015001 no problem.. looks good to me.. @Saviour1001 please merge this

2021-11-12 19:41 UTC, merged