LCA of a Binary Tree
girlscript/winter-of-contributing pull request #7761
Opened 2021-11-11 17:24 UTC by stutimohta20

<hr>

## Description 📜

Lowest Common Ancestor (LCA) of a node in a binary tree.
Fixes #7687 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-11 17:25 UTC, stutimohta20 commented
Please review my pr.

2021-11-11 18:38 UTC, vasu-1 requested changes
Mention Time & Space Complexities !

2021-11-11 18:38 UTC, vasu-1 commented on C_CPP/Data Structures/Trees/readme.md
> +- [LCA of a Binary Tree](C_CPP/Data Structures/Trees/LCAofBinaryTree.md)
```suggestion
- [LCA of a Binary Tree](./LCAofBinaryTree.md)
```

2021-11-11 18:38 UTC, vasu-1 commented on C_CPP/Data Structures/Trees/LCAofBinaryTree.md
> +It works on the rule that a node which has lesser value that the root is place on the left subtree and the one with more value
```suggestion
It works on the rule that a node which has lesser value that the root is placed on the left subtree and the one with more value 
```

2021-11-11 18:38 UTC, vasu-1 commented on C_CPP/Data Structures/Trees/LCAofBinaryTree.md
> +```
```suggestion
```cpp
```

for syntax effect

2021-11-12 06:47 UTC, stutimohta20 commented
Made the changes.

2021-11-12 10:15 UTC, stutimohta20 commented
Please review @vasu-1

2021-11-13 03:51 UTC, vasu-1 approved these changes
LGTM @stutimohta20 

@Suvraneel

2021-11-13 13:15 UTC, merged

2021-11-13 13:15 UTC, Suvraneel commented
@stutimohta20  Nice contribution 🚀  ❤️  :octocat: LGTM