Backend development with php
girlscript/winter-of-contributing pull request #7766
Opened 2021-11-11 19:53 UTC by vasu-1

<hr>

## Description 📜

I have added documentation about data types in php.

Fixes #7765 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [x] Backend Dev (PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-11 19:55 UTC, vasu-1 commented
Please Review this Pr @praveenscience @meinhoonharsh

2021-11-14 01:07 UTC, vasu-1 commented
@praveenscience

2021-11-28 07:53 UTC, krithikha2001 requested changes
Please check the text using some grammar tools for betterment.

2021-11-28 07:53 UTC, krithikha2001 commented on Backend_Development_With_PHP/Language_Highlights/Fundamentals/datatype.md
> +- it can be denoted in decimal (base 10), hexadecimal (base 16), octal (base 8) or binary (base 2) notation. The negation operator can be used to denote a negative number.
Can capitalize the starting letter of each point.

2021-11-28 07:53 UTC, krithikha2001 commented on Backend_Development_With_PHP/Language_Highlights/Fundamentals/datatype.md
> +- A float is a number with a decimal point or we can say that is is a number in exponential form.
"is" repeated twice

2021-11-28 07:53 UTC, krithikha2001 commented on Backend_Development_With_PHP/Language_Highlights/Fundamentals/datatype.md
> +- A map is a type that associates values to keys.
In PHP, an array is an ordered map. 
--- Please check the whole text content in grammar checker tools once

2021-11-28 09:17 UTC, vasu-1 commented
Suggested Changes Made @krithikha2001

2021-11-28 09:54 UTC, krithikha2001 commented
@praveenscience  Please merge this PR or let us know if any other changes are to be done.

2021-11-28 09:57 UTC, krithikha2001 approved these changes
👍👍

2021-11-30 09:34 UTC, vasu-1 commented
@2024-SANDHYA @gauravdas014 @praveenscience

2021-11-30 09:35 UTC, 2024-SANDHYA commented
> @2024-SANDHYA @gauravdas014 @praveenscience

Kindly tag supervisors of your domain. @vasu-1

2021-11-30 09:47 UTC, vasu-1 commented
They all are inactive @2024-SANDHYA

2025-08-27 18:32 UTC, closed without merging