Frontend web development react angular vue : History Mode in routes (Vue.js)
girlscript/winter-of-contributing pull request #7786
Opened 2021-11-12 10:21 UTC by HastiSutaria

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #7634 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [x] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x]I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-12 14:10 UTC, anandhu720 commented
@SourabhSaraswat-191939 Please review it

2021-11-13 05:14 UTC, HastiSutaria commented
@SourabhSaraswat-191939 PLEASE REVIEW MY PR.

2021-11-14 14:06 UTC, heet-kumar requested changes
@HastiSutaria make this code snippets of the jsx or javascript that's look nice

2021-11-14 14:06 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/Vue/Week 7/History Mode in routes.md
> +```
make this all code snippets of the javascript or jsx

2021-11-14 14:06 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/Vue/Week 7/History Mode in routes.md
> +```
make this all code snippets of the javascript or jsx

2021-11-14 14:06 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/Vue/Week 7/History Mode in routes.md
> +```
make this all code snippets of the javascript or jsx

2021-11-14 14:06 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/Vue/Week 7/History Mode in routes.md
> +```
make this all code snippets of the javascript or jsx

2021-11-14 14:09 UTC, heet-kumar commented
@SourabhSaraswat-191939 review this PR once from your side bro.

2021-11-14 14:49 UTC, HastiSutaria commented
> @HastiSutaria make this code snippets of the jsx or javascript that's look nice

Done. @heet-kumar

2021-11-14 15:31 UTC, heet-kumar approved these changes
@HastiSutaria Nice PR Every things looks good 👍 lets wait for the supervisor approval if they mention any changes make that to .

2021-11-14 17:36 UTC, anandhu720 approved these changes

2021-11-14 17:36 UTC, merged

2021-11-14 19:59 UTC, SourabhSaraswat-191939 commented
Good Job @HastiSutaria