Competitive programming: Competitve Programming: Activity Selction Problem
girlscript/winter-of-contributing pull request #7810
Opened 2021-11-12 17:57 UTC by Jinal4502

<hr>

## Description 📜

I have explained the activity selection algorithm alongwith its implementation in Python.
Fixes #7802 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Competitive Programming
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-12 18:03 UTC, Jinal4502 commented
Hey, I don't know why, but it is also showing me the old commits in the current pr which are already merged.

2021-11-13 20:04 UTC, Jinal4502 commented
I tried to remove those old commits by changing branch to other and again setting it back, but it didn't work. Anyway, even the old commits of my last pr https://github.com/girlscript/winter-of-contributing/pull/7657, are remerged it won't be a problem as they are already approved once. So, please review my pr.

2021-11-15 05:04 UTC, ravireddy07 reviewed
Only One file is allowed per contribution. So, Add one file only.
And seems like you have deleted some file(`Competitive_Programming/Python/Greedy/README.md`), Please add it. Only add your file only.

2021-11-15 05:07 UTC, ravireddy07 commented
> #7657

But with-respect-to-PR, we need to maintain that clarity that in which PR what exactly got merged.
So, the previous PR got merged. you can update your branch and remove unrequired files.

2021-11-15 06:44 UTC, Jinal4502 commented
Hey, I updated my forked repository and now only 2 files are there in the 'files changed' section, one is my own file and second is the one I deleted, so I added it back.

2021-11-15 07:45 UTC, ravireddy07 requested changes
After going through the doc, As a reader i've few concerns like

* What about other resources like Q,R,T,U,V..etc, they'll be picked or not..?
* Is it always starts from first resource or which has minimum starting time..?
* How does the complexity defines for this

can you explain this points in the doc so that the reader can exit without doubts. Please add more points few you came across

2021-11-15 07:45 UTC, ravireddy07 commented on Competitive_Programming/Python/Greedy/activity_selection.md
> +```
Better you just highlight this sentance. The reader can't scroll to right till end, it's a bad user experience.

2021-11-15 07:45 UTC, ravireddy07 commented on Competitive_Programming/Python/Greedy/activity_selection.md
> +While choosing activities, we need to keep in mind that two activities i and j are compatible if the half-open interval <b>[s<sub>i</sub> >= f<sub>j</sub>)</b> or <b>[s<sub>j</sub> >= f<sub>i</sub>)<
Can you add a note about what is **_s<sub>i</sub>, f<sub>j</sub>_**...etc
It will be easy to read.

2021-11-15 07:45 UTC, ravireddy07 commented on Competitive_Programming/Python/Greedy/activity_selection.md
> +```
same for this, just highlight it

2021-11-15 08:43 UTC, Jinal4502 commented
@ravireddy07, I have added explanation for not selecting activities Q, R, T, U, V, X and Y. Also, I have added the reason for choosing the first activity alongwith a brief explanation on time complexity. Also, I have removed greedy-definition and applications from the code block. And lastly, I have also added a short note about  si, fi, sj and fj. You can review all the changes, thank you!

2021-11-15 09:14 UTC, ravireddy07 requested changes
Good work @Jinal4502 ,
You can remove/unstag this file(`Competitive_Programming/Python/Greedy/README.md`)

2021-11-15 09:25 UTC, Jinal4502 commented
@ravireddy07, okay, I removed it.

2021-11-15 10:00 UTC, ravireddy07 approved these changes

2021-11-15 11:26 UTC, merged