Create ML_8.6_Transformers (D) .md
girlscript/winter-of-contributing pull request #7824
Opened 2021-11-13 10:41 UTC by shrestharushika

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #issue_number_here 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-13 11:25 UTC, Isha307 requested changes
And follow this https://github.com/girlscript/winter-of-contributing/blob/Machine_Learning/Machine_Learning/Demo/ML_%23_%23_Documentation%20Template_(D).md and also try to add some more content with clear explanation.

2021-11-13 11:25 UTC, Isha307 commented on Machine_Learning/ML_For_Sequential_Data_&_Visual_Data/ML_8.6_Transformers (D) .md
> +
Remove your name and batch number.

2021-11-14 04:00 UTC, abhisheks008 commented
@shrestharushika Do the needful changes.

2021-11-14 06:03 UTC, abhisheks008 commented
@shrestharushika You have deleted the title in the markdown file. Add the title.

2021-11-14 15:48 UTC, Isha307 requested changes
Please change 8.6 to 8_6 in the file name.

2021-11-16 05:41 UTC, Isha307 approved these changes

2021-11-16 05:41 UTC, merged