NP Completeness
girlscript/winter-of-contributing pull request #7875
Opened 2021-11-14 09:26 UTC by vishnu95075

<hr>

## Description 📜

# NP Completeness
- Image refrence example 
- Discription

Fixes #7874

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-15 08:45 UTC, deeqakkk requested changes
Vishnu, remove all the .png files from the PR and if required embed them in the NP_copleteness.md file itself.

2021-11-15 10:01 UTC, vishnu95075 commented
@deeqakkk , please review my changes.

2021-11-16 10:35 UTC, deeqakkk requested changes
![image](https://user-images.githubusercontent.com/78724676/141969531-0932b79f-65f2-4c93-bb28-21ddde445daa.png)
fix typo and there is no content under the reduction formula, fix this as well.

2021-11-17 16:00 UTC, deeqakkk requested changes

2021-11-17 16:00 UTC, deeqakkk commented on C_CPP/Algorithmic Approaches/NP Completeness/NP_Completeness.md
> +- [Refrence from geeksforgeeks](https://www.geeksforgeeks.org/np-completeness-set-1/)
remove this line as it is already there in reference part.

2021-11-17 16:47 UTC, vasu-1 commented
![image](https://user-images.githubusercontent.com/76911582/142243786-a3d6751b-f3fa-426c-88c8-7cd7298ae7aa.png)
Why have you mentioned Pr (#7890) instead of Issue ?

have you made an issue for this Pr ?

2021-11-17 22:56 UTC, vishnu95075 commented
@vasu-1 **(Issue no: #7874 that is fixes. so that i am mention ther**
![gitpng](https://user-images.githubusercontent.com/75454756/142295380-4177a8a2-34db-4873-b8a4-be6a3b90394e.png)

# Can you see this  is already merged.

2021-11-19 02:56 UTC, vasu-1 commented
ohk ohk my bad !

2021-11-19 03:05 UTC, vasu-1 requested changes
.

2021-11-19 10:26 UTC, deeqakkk approved these changes
@Suvraneel it's good to be merged.
Good work Vishnu and kudos to your patiences🎉👏

2021-11-20 01:09 UTC, vishnu95075 commented
@vasu-1 , Sorry for that I am image take from **GFG** , I think So it is giving some palagiarism . But I am give refrence for that.

2021-11-20 06:15 UTC, merged