Sort a stack -documentation added
girlscript/winter-of-contributing pull request #7876
Opened 2021-11-14 09:51 UTC by uzma024

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #7164

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [x] DSA
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

2021-11-15 14:44 UTC, uzma024 commented
@Muskan-creator @nimisha-yadav Kindly review and merge my pr.

2021-11-16 13:04 UTC, Muskan-creator commented
Hey @uzma024 .The issue was for documentation  not video contribution

2021-11-16 13:07 UTC, Muskan-creator requested changes

2021-11-16 13:07 UTC, Muskan-creator commented on DSA/4.1 Stacks/01. Introduction/3.Introduction_to_Stacks_video.md
> +## Introduction to stacks:
Kindly remove this file of stack and remain that file only which was for sorting a stack

2021-11-16 13:07 UTC, Muskan-creator commented on DSA/4.1 Stacks/01. Introduction/3.Introduction_to_Stacks_video.md
> + [![image](https://i.ibb.co/6mC1LRX/Screenshot-2021-11-14-at-11-48-47-PM.png)](https://youtu.be/nwNHV98-nao)
There is no need to add a video on stack that issue was already assigned or created

2021-11-16 13:30 UTC, Muskan-creator commented on DSA/4.1 Stacks/09. Sort a stack/1.Sort_a_stack _documentation.md
> +    Stack is a data structure that follows Last In First Out(LIFO) methord for
Spelling mistake in method

2021-11-17 13:56 UTC, uzma024 commented
I am not able to create changes here and its a bit too messy. So I have created another pull request.
Kindly review it. 
https://github.com/girlscript/winter-of-contributing/pull/7959#issue-1054875856

2021-11-22 15:41 UTC, closed without merging