Frontend web development html css js
girlscript/winter-of-contributing pull request #7895
Opened 2021-11-14 18:02 UTC by darshan4903

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #issue_number_here 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [x] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-16 05:06 UTC, kashishahuja2002 requested changes
Add only one md file.

2021-11-16 05:28 UTC, darshan4903 commented
deleted @kashishahuja2002

2021-11-16 08:17 UTC, kashishahuja2002 requested changes

2021-11-16 08:17 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML detail tag/HTML detailtag.md
> +# Attributes
Wrong level of heading, use ##.

2021-11-16 08:17 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML detail tag/HTML detailtag.md
> +### Syntax
Wrong level of heading, use ##.

2021-11-16 08:17 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML detail tag/HTML detailtag.md
> +### Example for detail tag
Wrong level of heading, use ##.

2021-11-16 08:17 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML detail tag/HTML detailtag.md
> +#### Code for above Example
Don't make it a heading, just bold.
Change text to: "Code:"

2021-11-16 08:17 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/HTML detail tag/HTML detailtag.md
> +
Instead of these screenshots, add a video output.

2021-11-16 14:32 UTC, darshan4903 commented
Updated @kashishahuja2002

2021-11-18 08:13 UTC, kashishahuja2002 requested changes
LGTM. Tag the supervisor of your batch to further review and merge the PR.

2021-11-18 08:14 UTC, kashishahuja2002 approved these changes

2021-11-18 09:06 UTC, darshan4903 commented
@2024-SANDHYA please merge this PR as it os approved

2021-11-18 10:28 UTC, 2024-SANDHYA commented
> 
> 
> @2024-SANDHYA please merge this PR as it os approved

I am not a supervisor though, but still, lemme check.

2021-11-18 10:29 UTC, merged