Frontend_with_Framework: React 7.1 -> State Management in React
girlscript/winter-of-contributing pull request #7904
Opened 2021-11-14 21:35 UTC by nisha855

<hr>

## Description 📜

Created documentation for State Management in React.
Fixes #7590

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [x] Frontend Dev React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-15 07:05 UTC, nisha855 commented
@heet-kumar Please review.

2021-11-16 12:42 UTC, heet-kumar requested changes
@nisha855 just add code snippets of the jsx
just in starting of the code after the 3 back-ticks add jsx (```jsx) just like this.

2021-11-16 12:42 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/React/Week 7/State Management in React.md
> +```
make this code snippets of the jsx
just in starting of the code after the 3 back-ticks add jsx (```jsx) just like this.

2021-11-16 12:42 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/React/Week 7/State Management in React.md
> +```
same here as above mention

2021-11-16 12:42 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/React/Week 7/State Management in React.md
> +```
same here also

2021-11-16 12:42 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/React/Week 7/State Management in React.md
> +```
same here also as above mentioned

2021-11-16 12:42 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/React/Week 7/State Management in React.md
> +```
same here also as above mentioned

2021-11-16 12:42 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/React/Week 7/State Management in React.md
> +```
same here also as above mentioned

2021-11-16 12:42 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/React/Week 7/State Management in React.md
> +```
same here also as above mentioned

2021-11-17 05:34 UTC, nisha855 commented
@heet-kumar  Done the required changes.

2021-11-17 17:20 UTC, heet-kumar approved these changes
@nisha855 Great work done LGTM ! 👍 lets wait for the supervisor approval and if they suggest any changes then make that to.

2021-11-17 17:21 UTC, heet-kumar commented
@anandhu720 once review this PR from your side.

2021-11-18 03:48 UTC, anandhu720 approved these changes

2021-11-18 03:48 UTC, merged