Euclid Algorithm
girlscript/winter-of-contributing pull request #7931
Opened 2021-11-15 19:44 UTC by iam-sakshi

<hr>

## Description 📜
Explain the brute force to find GCD and the Euclid way to find the GCD with explanation , code and Time Complexity. 
 
##Number Theory : Euclid Algorithm #7383
<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [x] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-16 04:14 UTC, iam-sakshi commented
please review

2021-11-24 18:26 UTC, iam-sakshi commented
@ravireddy07 please review

2021-11-25 07:48 UTC, ravireddy07 requested changes

2021-11-25 07:48 UTC, ravireddy07 commented on Competitive_Programming/C++/Maths & Number Theory/EuclidAlgorithm.md
> +## GCD
Please differentiate this two approaches with explanation. Before going to code, the user/reader need to understand the concept/approach that used.

Like: how we're going to solve this problem in this approach.

2021-11-25 07:48 UTC, ravireddy07 commented on Heap/TopKthFrequentElement/TopKthFrequentElement.md
> +## Top K Frequent Elements
Remove  this file

2021-11-25 18:31 UTC, iam-sakshi commented
done all the required changes, please review

2021-11-26 03:45 UTC, ravireddy07 requested changes
Please differentiate this two approaches with explanation. Before going to code, the user/reader need to understand the concept/approach that used with Heading.

like Basic approach, Euclid Algorithm.

and place the formatted code.

2021-11-26 05:36 UTC, iam-sakshi commented
I have placed the headings and the code is formatted . please review.

2021-11-26 07:45 UTC, ravireddy07 approved these changes

2021-11-26 08:24 UTC, iam-sakshi commented
@Rishabh510 please review

2021-11-26 13:48 UTC, ravireddy07 commented
wait @Rishabh510 , Don't merge!

Seems like you have created another PR with same branch before merging this PR. Hence, you see there two files in this. @iam-sakshi .
Please follow the exact steps to create a PR.

2021-11-26 14:58 UTC, iam-sakshi commented
I have deleted it. I am sorry ,I didn't noticed . 
But now there is only one file that was approved by @ravireddy07 .
@Rishabh510 please review

2021-11-27 00:58 UTC, merged