C_CPP: Virtual Destructor
girlscript/winter-of-contributing pull request #7940
Opened 2021-11-16 05:00 UTC by 124015001

<hr>

## Description 📜

Explained the use of Virtual Destructor. Also, performed a program explaining the same.
Fixes #7850 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-11-16 16:57 UTC, vasu-1 requested changes

2021-11-16 16:57 UTC, vasu-1 commented on C_CPP/OOPs in C++/Virtual Functions, Friend Functions & Friend Classes/virtual-destructor.md
> +Destrcutors are called in the reverse order in the class hierarchy i.e. reverse to the order in which their counterpart constructors are invoked. A destructor of a base class is not declared virtual
```suggestion
Destructors are called in the reverse order in the class hierarchy i.e. reverse to the order in which their counterpart constructors are invoked. A destructor of a base class is not declared virtual and a base class pointer containing the address of a derived class object is obtained dynamically using a new operator. The concept of virtual destructors come into the picture when the objects in the derived class are created using the new operator.  
```

2021-11-16 17:03 UTC, 124015001 commented
@vasu-1 Committed your suggested changes.

2021-11-17 16:14 UTC, vasu-1 approved these changes
LGTM  @124015001 
@Saviour1001

2021-11-17 18:21 UTC, merged