Merge two arrays according to constraints added.
girlscript/winter-of-contributing pull request #7956
Opened 2021-11-16 12:40 UTC by priyankapiba

<hr>

## Description 📜
Merge two arrays by satisfying given constraints
Given two sorted arrays X[] and Y[] of size m and n each where m >= n and X[] has exactly n vacant cells, merge elements of Y[] in their correct position in array X[], i.e., merge (X, Y) by keeping the sorted order.
 #7955 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [x] Competitive Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-21 19:18 UTC, Manvi1203 commented
/assign

2021-11-22 06:51 UTC, priyankapiba commented
/assign

2021-11-23 04:29 UTC, priyankapiba commented
Hey @Manvi1203, my PR is under review, kindly work on a different issue.

2021-11-26 08:56 UTC, ravireddy07 requested changes

2021-11-26 08:56 UTC, ravireddy07 commented on Competitive_Programming/C++/Array/Merge-two-arrays.md
> +#include <stdio.h>
Use `#include<bits/stdc++.h`

2021-11-26 08:56 UTC, ravireddy07 commented on Competitive_Programming/C++/Array/Merge-two-arrays.md
> +### The time complexity of the above solution is O(m + n) and runs in constant space. Here, m and n are the size of the first and second array, respectively.
Add Time/Space Complexity's with Heading

2021-11-26 13:43 UTC, ravireddy07 approved these changes

2021-11-27 00:56 UTC, merged