High Resoution Using Retina Display
girlscript/winter-of-contributing pull request #7984
Opened 2021-11-17 09:34 UTC by satyam-mahajan

<hr>

## Description 📜

Apple made a retina display for high resolution which is more pixelated and much cleared than normal one. Let's we go to study in detail. 
Fixes #7627 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-17 10:03 UTC, kashishahuja2002 requested changes
Very less content, add a bit more.

2021-11-17 10:03 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/High Resolution Display in CSS/Retina Display for High Resolution.md
> +### Display Resolution
Wrong level of heading, use ##.

2021-11-17 10:03 UTC, kashishahuja2002 commented on Web_Development/FrontEnd/High Resolution Display in CSS/Retina Display for High Resolution.md
> +### Retina Display
Wrong level of heading, use ##.

2021-11-17 10:36 UTC, satyam-mahajan commented
I do the changes ,please it again.

2021-11-17 11:16 UTC, kashishahuja2002 commented
> I do the changes ,please review it again @kashishahuja2002

Did you add a little more content, looks the same to me.

2021-11-17 11:22 UTC, satyam-mahajan commented
No , I add one paragraph after you say.. Need I write some more? @kashishahuja2002

2021-11-17 11:38 UTC, satyam-mahajan commented
I add some more content . Please can you review it @kashishahuja2002

2021-11-18 05:10 UTC, kashishahuja2002 approved these changes
LGTM. Tag the supervisor of your batch fir further reviewing and merging of the PR.

2021-11-18 06:10 UTC, satyam-mahajan commented
please review my PR @Knighthawk-Leo

2021-11-18 06:41 UTC, Knighthawk-Leo commented
Ok looking for it

2021-11-19 15:52 UTC, satyam-mahajan commented
please review and merge my PR  @code-reaper08 .

2021-11-19 16:26 UTC, code-reaper08 requested changes
Hello @satyam-mahajan 👋 
There are many typos and grammatical mistakes, please fine tune them. I would also suggest you to add image source links right below the images.

2021-11-19 17:54 UTC, satyam-mahajan commented
I do the required changes , please review it @code-reaper08 .

2021-11-19 18:00 UTC, code-reaper08 requested changes
Please format the spacings and still there are grammatical errors. Take your time and do the changes.

2021-11-19 18:37 UTC, satyam-mahajan commented
I remove all grammatical mistakes ,please you review it once again @code-reaper08 .

2021-11-20 16:17 UTC, satyam-mahajan commented
please review my PR @code-reaper08 .

2021-11-20 19:13 UTC, code-reaper08 requested changes
@satyam-mahajan still there are more grammatical errors, I suggest you to use a service like **Grammarly** to clean up the errors.

2021-11-20 19:51 UTC, satyam-mahajan commented
I remove all grammatical mistakes , please review it @code-reaper08

2021-11-21 04:36 UTC, code-reaper08 requested changes
Kindly look through the review and change the captions.

Grammatical errors are now fixed 👍

2021-11-21 04:36 UTC, code-reaper08 commented on Web_Development/FrontEnd/High Resolution Display in CSS/Retina Display for High Resolution.md
> +[Retina Display Image](https://user-images.githubusercontent.com/54473091/142192529-16602e16-c339-44de-915d-ddc02687b69d.jpg)
Place a link to the actual source.
AFAIK you've taken the images from [here](https://en.wikipedia.org/wiki/Retina_display).

Do update the captions to real links to source.

2021-11-21 04:36 UTC, code-reaper08 commented on Web_Development/FrontEnd/High Resolution Display in CSS/Retina Display for High Resolution.md
> +[Non Retina Display Image](https://user-images.githubusercontent.com/54473091/142193055-64f38832-168c-45ed-94ee-d02bfb779dbb.jpg)
Same here,
Place a link to the actual source.
AFAIK you've taken the images from [here](https://en.wikipedia.org/wiki/Retina_display).

Do update the captions to real links to source.

2021-11-21 07:16 UTC, satyam-mahajan commented
please review it again @code-reaper08 .

2021-11-22 08:02 UTC, satyam-mahajan commented
Please review it @code-reaper08 . I do all the required changes.

2021-11-23 11:58 UTC, satyam-mahajan commented
please review my PR @code-reaper08 and @Knighthawk-Leo

2021-11-23 15:47 UTC, code-reaper08 approved these changes
LGTM ✨

2021-11-23 15:48 UTC, merged