Create integer_to_roman.md
girlscript/winter-of-contributing pull request #8004
Opened 2021-11-17 17:13 UTC by Preet1406

<hr>

## Description 📜

I've added a file to convert integer to roman numeral. 
Fixes #8000  

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-17 17:17 UTC, Preet1406 commented
@apeksha235  please review it

2021-11-18 06:05 UTC, Preet1406 commented
@apeksha235 @kashishahuja2002 please review it

2021-11-18 06:18 UTC, apeksha235 requested changes
@Preet1406 Add the relative link of your file in the readme of the respective folder

2021-11-18 06:23 UTC, apeksha235 requested changes
@Preet1406 make these changes

2021-11-18 06:23 UTC, apeksha235 commented on C_CPP/Number System/Conversion-Programs/integer_to_roman.md
> +    int val[13] = {1000,900,500,400,100,90,50,40,10,9,5,4,1};
add relevant comments to your code

2021-11-18 06:23 UTC, apeksha235 commented on C_CPP/Number System/Conversion-Programs/integer_to_roman.md
> +Input: number = 3
add the input and output inside the highlighter ```

2021-11-18 14:42 UTC, Preet1406 commented
@apeksha235 Changes done, for the link, there is no readme file in the respective folder. Please check

2021-11-18 21:10 UTC, apeksha235 commented
@Preet1406 
![image](https://user-images.githubusercontent.com/84583787/142497036-ca716568-3df8-45da-a2db-8d4dc4d2fd18.png)

Add the link under the ```conversion programs``` as a subheading

2021-11-19 14:20 UTC, Preet1406 commented
@apeksha235 Please check again

2021-11-20 06:08 UTC, apeksha235 approved these changes
@Preet1406 Good!! 
@Saviour1001 please merge this

2021-11-20 10:01 UTC, merged