Added responsiveness in css files
girlscript/winter-of-contributing pull request #8029
Opened 2021-11-18 12:10 UTC by niharikamahajan02

<hr>

## Description 📜

Details about what is a responsive website and how it's implemented using CSS
Fixes #7674 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-18 12:11 UTC, niharikamahajan02 commented
please review

2021-11-20 19:39 UTC, code-reaper08 requested changes
Hello @niharikamahajan02 
I've left a review, please check.
I would also suggest you to add images as upload assets (using drag and drop)
This would make the repo much more light weight.

If you need any help tag me here :-)

2021-11-20 19:39 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_REPONSIVENESS/reponsiveness.md
> +```
Wrong image captions and example taken from https://www.w3schools.com/css/tryit.asp?filename=tryresponsive_mediaquery_orientation2

Please try to do examples on your own, or else at least specify the source.

2021-11-20 19:39 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_REPONSIVENESS/reponsiveness.md
> +```
Please add source https://www.w3schools.com/css/tryit.asp?filename=trycss_mediaqueries_fontsize

2021-11-20 19:39 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_REPONSIVENESS/reponsiveness.md
> +```
Please add source https://www.w3schools.com/css/tryit.asp?filename=tryresponsive_mediaquery_orientation2

2021-11-20 19:39 UTC, code-reaper08 commented on Web_Development/FrontEnd/CSS_REPONSIVENESS/reponsiveness.md
> +> We  use CSS and HTML to resize, hide, shrink, enlarge, or move the content to make it look good on any screen.
Remove formatting

2021-11-20 21:01 UTC, niharikamahajan02 commented
@code-reaper08 , please review again , I have done the suggested changes .
Also have uploaded the images again , please tell if this was the way to upload images , you told me about.

2021-11-21 04:39 UTC, code-reaper08 approved these changes
LGTM ✨

2021-11-21 04:40 UTC, code-reaper08 commented
> @code-reaper08 , please review again , I have done the suggested changes . Also have uploaded the images again , please tell if this was the way to upload images , you told me about.

Yep Images are good now!
Thanks for contributing 😄

2021-11-21 04:40 UTC, merged

2021-11-21 07:59 UTC, niharikamahajan02 commented
> > @code-reaper08 , please review again , I have done the suggested changes . Also have uploaded the images again , please tell if this was the way to upload images , you told me about.
> 
> Yep Images are good now! Thanks for contributing 😄

Thankss!!