Documentation of traversal problems
girlscript/winter-of-contributing pull request #8055
Opened 2021-11-19 04:42 UTC by ANUSHKA-AARYA

In this documentation, I have explained about wave and spiral traversal problems using 2D array in c language.

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-20 06:20 UTC, Suvraneel commented
@gunjan-g

2021-11-22 08:56 UTC, ANUSHKA-AARYA commented
@Suvraneel please review this

2021-11-22 09:18 UTC, gunjan-g requested changes
@ANUSHKA-AARYA Please include proper spacing inside the codes for better view

2021-11-22 09:18 UTC, gunjan-g commented on C_CPP/Data Structures/Array/TRAVERSAL PROBLEMS/wave_spiral_traversal.md
> +```
```suggestion
```cpp
```
Use cpp markdown for codes written in cpp

2021-11-22 14:05 UTC, ANUSHKA-AARYA commented
@gunjan-g  kindly review this....

2021-11-22 17:55 UTC, gunjan-g commented
> @gunjan-g kindly review this....

Please fetch from the cpp branch first and then commit your changes

2021-11-22 18:09 UTC, ANUSHKA-AARYA commented
@gunjan-g

2021-11-23 07:26 UTC, gunjan-g commented
@ANUSHKA-AARYA Have you pushed changes from the same branch you've used before to contribute to some other domain?

2021-11-23 12:12 UTC, ANUSHKA-AARYA commented
@gunjan-g  no, i have made the changes you said, and simply pushed in the current domain. You once check array folder in data structures contribution is there

2021-11-23 12:38 UTC, Suvraneel commented
@ANUSHKA-AARYA 
These are diverged branches... The branch from where you made the PR is not based off CPP...
![image](https://user-images.githubusercontent.com/63473496/143025285-ea44300b-f4ed-4e6a-a5b1-f971fffd84f5.png)

2021-11-23 12:38 UTC, closed without merging

2021-11-23 12:42 UTC, gunjan-g commented
@ANUSHKA-AARYA You can make a new pr

2021-11-23 12:52 UTC, Suvraneel commented
That new PR must not be from this or similar hybrid branch though

2021-11-23 16:50 UTC, ANUSHKA-AARYA commented
@gunjan-g ok

2021-11-23 17:08 UTC, ANUSHKA-AARYA commented
@Suvraneel  sry, but  I am not getting what you are saying and i am unable to work on my new issue it is not fetching upstream.

2021-11-24 18:07 UTC, ANUSHKA-AARYA commented
@Suvraneel

2021-11-24 19:54 UTC, Suvraneel commented
@ANUSHKA-AARYA  If you're being unable to fetch upstream, it means you've somehow messed up & caused conflicts....
That could be solved in a session ofc...

But I have a better solution... Delete your fork, refork & then make a fresh PR