Video
girlscript/winter-of-contributing pull request #806
Opened 2021-09-19 08:25 UTC by Sarfraz-droid

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #247  

<hr>

## Type of change 📝

- [x ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x ] JavaScript

<hr>
 
## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

![image](https://user-images.githubusercontent.com/73013838/133920716-432e4aad-1fd7-47fe-bee5-19d57ad3aa8e.png)

<hr>

2021-09-21 05:54 UTC, paramsiddharth commented
@Creatoon @dakshsethi @s4-2 Please review.

2021-09-21 05:59 UTC, paramsiddharth requested changes
Mostly format changes (critical to ASI). Please update the PR. Looks great to me!

2021-09-21 05:59 UTC, paramsiddharth commented on JavaScript/Topics/5.Syntax/6.Functions/Video.md
> +```
Please indent and not use not-needed whitespace.
```suggestion
```javascript
function myFunction(p1, p2) {
    return p1 * p2; // The function returns the product of p1 and p2
}
```
```

2021-09-21 05:59 UTC, paramsiddharth commented on JavaScript/Topics/5.Syntax/6.Functions/Video.md
> +```
```suggestion
``` javascript
if (true) {
    const a = 2;
}

console.log(a); //ReferenceError
```
```

2021-09-21 05:59 UTC, paramsiddharth commented on JavaScript/Topics/5.Syntax/6.Functions/Video.md
> +}
```suggestion
```javascript
function myFunction(p1, p2) {
    return p1 * p2; // The function returns the product of p1 and p2
}
```

2021-09-21 05:59 UTC, paramsiddharth commented on JavaScript/Topics/5.Syntax/6.Functions/Video.md
> +```
```suggestion
```javascript
function sum(a,b) {
	c = a+b
	console.log(c);
}

sum(10,12);
```
```

2021-09-21 05:59 UTC, paramsiddharth commented on JavaScript/Topics/5.Syntax/6.Functions/Video.md
> +```
```suggestion
```javascript
const show = function(){
	console.log("Anonymouse Function");
}
	
show();
```
```

2021-09-21 05:59 UTC, paramsiddharth commented on JavaScript/Topics/5.Syntax/6.Functions/Video.md
> +```
```suggestion
```javascript
function subtract(num1, num2) {
	return num1 - num2;
}
```
```

2021-09-21 06:36 UTC, Sarfraz-droid commented
Done @paramsiddharth

2021-09-21 08:15 UTC, Sarfraz-droid commented
Done

2021-09-21 09:08 UTC, s4-2 approved these changes
Looks good to me:)

2021-09-22 05:36 UTC, paramsiddharth commented
@Creatoon @dakshsethi Please review.

2021-09-22 05:38 UTC, paramsiddharth requested changes
Please close the code-blocks properly. The rest looks great!

2021-09-22 05:38 UTC, paramsiddharth commented on JavaScript/Topics/5.Syntax/6.Functions/Video.md
> +This time javascript throws an error. Why is it so?
```suggestion
```javascript
function myFunction(p1, p2) {
    return p1 * p2; // The function returns the product of p1 and p2
}

But before learning functions, lets learn about **scope**.

<hr>

### Scope

The scope is basically the availability of your code.  
Let’s see by an example

``` javascript
if (true) {
    const a = 2;
}

console.log(a); //ReferenceError
```

This time javascript throws an error. Why is it so?
```

You forgot to turn off the code-block.

2021-09-22 05:38 UTC, paramsiddharth commented on JavaScript/Topics/5.Syntax/6.Functions/Video.md
> +
Here too.

2021-09-22 05:38 UTC, paramsiddharth commented on JavaScript/Topics/5.Syntax/6.Functions/Video.md
> +**Arrow Functions**
Same here.

2021-09-22 07:06 UTC, paramsiddharth approved these changes
@Creatoon @dakshsethi Please review.

2021-09-22 16:40 UTC, dakshsethi requested changes

2021-09-22 16:40 UTC, dakshsethi commented on JavaScript/Topics/5.Syntax/6.Functions/Video.md
> +
It should be `# JavaScript Functions`

2021-09-22 17:04 UTC, Sarfraz-droid commented
Done @dakshsethi

2021-09-22 18:18 UTC, dakshsethi approved these changes
Looks good to me!! 🔥🔥🔥

2021-09-23 01:47 UTC, Creatoon requested changes

2021-09-23 01:47 UTC, Creatoon commented on JavaScript/Topics/5.Syntax/6.Functions/Video.md
> +A **JavaScript function** is a block of code designed to perform a particular task. Its basically dividing you program into different parts.
```suggestion
A **JavaScript function** is a block of code designed to perform a particular task. Its basically dividing your program into different functional components.
```

2021-09-23 01:47 UTC, Creatoon commented on JavaScript/Topics/5.Syntax/6.Functions/Video.md
> +console.log(a); //ReferenceError
Write full reference error text

2021-09-23 01:47 UTC, Creatoon commented on JavaScript/Topics/5.Syntax/6.Functions/Video.md
> +
```suggestion
```
aren't these 2 lines are combined?

2021-09-23 01:50 UTC, Creatoon commented
Missing Points:

1)Behavior of this variable inside both type of function, normal one and arrow one

Just don't define THIS keyword fully, you have to talk about its behavior as its details will be covered in THIS topic.

2021-09-23 03:59 UTC, Sarfraz-droid commented
@Creatoon Done

2021-09-23 04:05 UTC, Creatoon approved these changes

2021-09-23 04:10 UTC, merged