Exception Handling in C++
girlscript/winter-of-contributing pull request #8068
Opened 2021-11-19 10:27 UTC by saniya44

<hr>

## Description 📜

C_CPP:- Video of Exception Handling in C++ #6957 issue was assigned to me. I did my best and added VIDEO_Exception Handling in C++ folder into Exception Handling directory of C_CPP branch.
Fixes #6957 

<hr>

## Type of change 📝

- [x] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-20 19:33 UTC, Suvraneel requested changes
@saniya44  Kindly stick to `.md` format to maintain uniformity across this domain...
Remove the `.ipynb` file and add those examples as codeblocks in the md itself

Also, readme.md is reserved here for indexes only... rename your 1st file

After that, mentors will review...

2021-11-21 03:58 UTC, saniya44 commented
> @saniya44  Kindly stick to `.md` format to maintain uniformity across this domain...
> Remove the `.ipynb` file and add those examples as codeblocks in the md itself
> 
> Also, readme.md is reserved here for indexes only... rename your 1st file
> 
> After that, mentors will review... 

Okay 👍

2021-11-22 18:57 UTC, saniya44 commented
Done requested changes.

2021-11-23 12:31 UTC, Suvraneel requested changes
@saniya44  Observe changes made to video link file...

In the source code, put every code in a separate codeblock
& use codeblock highlighting , like this  ` ```cpp `

2021-11-23 12:31 UTC, Suvraneel commented on C_CPP/Exception Handling/VIDEO_Exception Handling in C++/SourceCode.md
> +using namespace std;
```suggestion
1. Exception.cpp
```cpp
//Simple Exception Handling- Divide by 0
#include <iostream>
using namespace std;

```

2021-11-23 12:31 UTC, Suvraneel commented on C_CPP/Exception Handling/VIDEO_Exception Handling in C++/SourceCode.md
> +#include <iostream>
```suggestion
}
```

## 2. Exception2.cpp
```cpp
//Exception Handling using multiple throw and catch
#include <iostream>

```

2021-11-23 12:31 UTC, Suvraneel commented on C_CPP/Exception Handling/VIDEO_Exception Handling in C++/SourceCode.md
> +//Multiple throw single catch block
Same

2021-11-23 12:34 UTC, Suvraneel commented
![image](https://user-images.githubusercontent.com/63473496/143024617-71e94ea7-252f-4771-8337-75a5f08639a1.png)
@saniya44  Also, these many commits aren't desirable... Use Git Bash... or GitHub desktop even... Dont use the Web Interface

2021-11-23 14:20 UTC, saniya44 commented
Okay 👍

2021-11-23 15:42 UTC, saniya44 commented
Okay 👍

2021-11-25 10:02 UTC, closed without merging

2021-11-25 10:52 UTC, saniya44 commented
Closed this cause of so many mistakes...
Refer correct one here: https://github.com/girlscript/winter-of-contributing/pull/8427