fake-news-detection
girlscript/winter-of-contributing pull request #8118
Opened 2021-11-20 10:07 UTC by ASLManasa

ML : Fake News Classification (ML-Projects) #8021
 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ x] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x ] I have performed a self-review of my own code or work.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generates no new warnings.
- [x ] I'm GWOC'21 contributor

<hr>

2021-11-20 12:53 UTC, abhisheks008 requested changes
1. `Model/README.md` file's bullet points are not properly aligned.
2. Rename `Dataset/dataset.md` as `Dataset/README.md`
3. In the ipynb file, comment out in the cells and provide some explanation

@ASLManasa

2021-11-21 04:21 UTC, abhisheks008 commented
@ASLManasa Please do the needful changes by EOD.

2021-11-21 15:14 UTC, ASLManasa commented
@abhisheks008 yes sir done.

2021-11-21 15:16 UTC, abhisheks008 approved these changes

2021-11-21 15:16 UTC, merged