Solved Issue #8077
girlscript/winter-of-contributing pull request #8132
Opened 2021-11-20 14:46 UTC by Ajinkyap331

<hr>

## Description 📜

Solved Issue #8077 as a Source of Documentation
Solved Issue #8077 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] Frontend Dev #React/Angular/Vue

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-11-20 14:47 UTC, Ajinkyap331 commented
@anandhu720 @heet-kumar please review this

2021-11-20 14:54 UTC, anandhu720 commented
@heet-kumar please review it

2021-11-21 14:43 UTC, heet-kumar commented
> @heet-kumar please review it

sure bro

2021-11-21 15:19 UTC, heet-kumar requested changes
@Ajinkyap331 add explanation and process of the code

2021-11-21 15:19 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/React/Week 8/Unfetch.md
> +```
just add explanation and process of these code.

2021-11-21 15:19 UTC, heet-kumar commented on Frontend_Web_Development_React_Angular_Vue/React/Week 8/Unfetch.md
> +```
here also just add explanation and process of these code.

2021-11-23 00:34 UTC, Ajinkyap331 commented
Ok I will do it today itself @heet-kumar

2021-11-23 12:27 UTC, Ajinkyap331 commented
@heet-kumar  review this Please

2021-11-24 07:56 UTC, heet-kumar requested changes
@Ajinkyap331 add theory explanation in short I mean add more content because theory explanation/content is less so add that also.

2021-11-24 19:43 UTC, Ajinkyap331 commented
@heet-kumar Can I do it tomorrow i.e 26th

2021-11-25 07:01 UTC, heet-kumar commented
@Ajinkyap331 ok no problem try to do asap.

2021-11-25 15:20 UTC, Ajinkyap331 commented
@heet-kumar I have done all I can do cause only documentation is the place where I can get the info NO tutorial NO youtube video. I guess I have added many things

2021-11-26 03:56 UTC, heet-kumar commented
@Ajinkyap331 I only want that, just add how these code is working which you have added in the documentation, just explain the process of the code just below that code.

2021-11-26 04:22 UTC, Ajinkyap331 commented
@heet-kumar thanks I will do it now itself

2021-11-26 04:42 UTC, heet-kumar commented
> @heet-kumar thanks I will do it now itself

ok do it then we will merge it PR.

2021-11-26 05:10 UTC, Ajinkyap331 commented
@heet-kumar  Done

2021-11-26 06:25 UTC, heet-kumar approved these changes
@Ajinkyap331 Nice explanation LGTM PR !! 👍 let's wait for the supervisor approval if they mention any changes then make that to.

2021-11-26 06:25 UTC, heet-kumar commented
@anandhu720 once review from your side get merged this PR.

2021-11-26 08:16 UTC, Ajinkyap331 commented
> @Ajinkyap331 Nice explanation LGTM PR !! 👍 let's wait for the supervisor approval if they mention any changes then make that to.

LGTM meaning?

2021-11-26 09:41 UTC, heet-kumar commented
> > @Ajinkyap331 Nice explanation LGTM PR !! 👍 let's wait for the supervisor approval if they mention any changes then make that to.
> 
> LGTM meaning?

Lets get the merge PR

2021-11-26 10:21 UTC, Ajinkyap331 commented
> > > @Ajinkyap331 Nice explanation LGTM PR !! 👍 let's wait for the supervisor approval if they mention any changes then make that to.
> > 
> > 
> > LGTM meaning?
> 
> Lets get the merge PR

OK

2021-11-26 15:46 UTC, anandhu720 approved these changes

2021-11-26 15:46 UTC, merged