C_CPP : Multiple Inheritance in C++
girlscript/winter-of-contributing pull request #8183
Opened 2021-11-21 13:23 UTC by vartikavr

<hr>

## Description 📜

Added documentation for multiple inheritance in C++.
Fixes #8181 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-21 14:15 UTC, gunjan-g requested changes
@vartikavr Use cpp markdown instead of normal one, where you've used cpp codes

2021-11-21 14:16 UTC, gunjan-g requested changes
like this

2021-11-21 14:16 UTC, gunjan-g commented on C_CPP/OOPs in C++/Inheritance and its types or Function overriding/multiple_inheritance_doc.md
> +```
```suggestion
```cpp
```

2021-11-21 17:44 UTC, vartikavr commented
@gunjan-g, I've done the suggested changes. Kindly review again.

2021-11-21 18:43 UTC, apeksha235 requested changes

2021-11-21 18:43 UTC, apeksha235 commented on C_CPP/OOPs in C++/Inheritance and its types or Function overriding/multiple_inheritance_doc.md
> +#include <iostream>
@vartikavr this is a pretty basic example, give another better example along with this.

2021-11-21 19:32 UTC, vartikavr commented
@apeksha235, I've changed and tried to include a better example. Kindly review again.

2021-11-23 17:56 UTC, apeksha235 approved these changes
@Saviour1001 Please merge this

2021-11-23 18:14 UTC, merged