Create Reversing every word in a String
girlscript/winter-of-contributing pull request #8244
Opened 2021-11-22 12:31 UTC by yellowberard

<hr>

## Description 📜
To reverse every word in a string.
Fixes #issue_number_here 

<hr>

## Type of change 📝

- [X] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [X] C/#CPP
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-11-22 12:41 UTC, yellowberard commented
@kashishahuja2002 Please review my PR

2021-11-22 12:42 UTC, yellowberard commented
closes pr #5665

2021-11-25 04:56 UTC, vasu-1 requested changes
- First of all add your file link into respective folder's readme.md
- remove unneccessary empty lines
- beautify your document with markdown formatting
- add space complexities

2021-11-25 08:20 UTC, yellowberard commented
I have taken the problem statement and examples from leetcode so do I have to change the language of the question. @vasu-1

2021-11-25 14:29 UTC, vasu-1 commented
> 

Please check it once , i have updated the requested changes

2021-11-25 14:46 UTC, yellowberard commented
@vasu-1 I have made the requested changes.

2021-11-26 08:59 UTC, vasu-1 requested changes

2021-11-26 08:59 UTC, vasu-1 commented on C_CPP/Competitive Programming/Reversing_every_word_in_string.md
> +- [Mayank Goel](https://github.com/yellowberard) For documentation
No need
Please REmove

2021-11-26 08:59 UTC, vasu-1 commented on C_CPP/Competitive Programming/Reversing_every_word_in_string.md
> +}
Put whole code !

2021-11-26 13:43 UTC, yellowberard commented
@vasu-1 I have made the requested changes.

2021-11-26 14:20 UTC, vasu-1 requested changes

2021-11-26 14:20 UTC, vasu-1 commented on C_CPP/Competitive Programming/Reversing_every_word_in_string.md
>  ```
```suggestion
```cpp
```

for syntax effect

2021-11-26 14:32 UTC, yellowberard commented
@vasu-1 I have made the requested changes.

2021-11-26 14:37 UTC, vasu-1 approved these changes
LGTM @yellowberard 

@Suvraneel @Saviour1001

2021-11-26 15:04 UTC, merged