Function_call in C++
girlscript/winter-of-contributing pull request #8307
Opened 2021-11-23 14:45 UTC by Anu2001-prog

FUNCTION CALL IN C++ & ITS TYPES

## Description 📜

I have included the codes, documentation, and video of the presentation with audio explaining the function call and its types..
Fixes #8285 

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Video (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-23 15:18 UTC, Suvraneel requested changes
@Anu2001-prog  Good work 

Changes :
1. Shift video to top of md file... Dikhna chahiye ekdumm upar
2. Add appropriate line to `C_CPP/Fundamentals/Functions & Recursion and its types/readme.md`

2021-11-23 15:18 UTC, Suvraneel commented on C_CPP/Fundamentals/Functions & Recursion and its types/Function_call.md
> +### What is a function call in c++?
```suggestion
## What is a function call in c++?
```
Redundant

2021-11-23 15:18 UTC, Suvraneel commented on C_CPP/Fundamentals/Functions & Recursion and its types/Function_call.md
> + ### video explanation :
```suggestion
 ### Video Explanation :
```

2021-11-23 16:27 UTC, merged

2021-11-23 16:27 UTC, Suvraneel commented
@Anu2001-prog  LGTM

2021-11-25 06:02 UTC, Anu2001-prog commented
thank you. @Suvraneel