Added Documentation for Binary Search For Repeated Elements
girlscript/winter-of-contributing pull request #8337
Opened 2021-11-23 21:18 UTC by VaibhavMalik4187

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #8121

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [X] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [X] C/#CPP

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-23 21:18 UTC, VaibhavMalik4187 commented
@Saviour1001 @Suvraneel Please review my PR

2021-11-24 06:47 UTC, Suvraneel commented
@gunjan-g

2021-11-24 12:33 UTC, vasu-1 requested changes
![Screenshot_2021-11-24-18-03-04-23.jpg](https://user-images.githubusercontent.com/76911582/143239150-b795917c-6fd0-46af-a5e1-8090b4f6bb57.jpg)

Please remove this hash sign from C/CPP

2021-11-24 12:34 UTC, vasu-1 requested changes
Add your file link into respective folder's readme.md

2021-11-24 12:41 UTC, vasu-1 commented
Rest of the things LGTM 🌝

2021-11-24 12:43 UTC, VaibhavMalik4187 commented
> ![Screenshot_2021-11-24-18-03-04-23.jpg](https://user-images.githubusercontent.com/76911582/143239150-b795917c-6fd0-46af-a5e1-8090b4f6bb57.jpg)
> 
> Please remove this hash sign from C/CPP

Done

2021-11-24 12:52 UTC, VaibhavMalik4187 commented
> Add your file link into respective folder's readme.md
Done

2021-11-24 12:53 UTC, VaibhavMalik4187 commented
@vasu-1 I have made the changes that you requested, now kindly review again and merge my PR

2021-11-24 13:47 UTC, Suvraneel requested changes
@VaibhavMalik4187

2021-11-24 13:47 UTC, Suvraneel commented on C_CPP/Algorithmic Approaches/Divide & Conquer/BinarySearchForRepeatedElements.md
> +
```suggestion
  
  
```
Remove all html tags... use 2 spaces at end of each line for line breaks

2021-11-24 13:47 UTC, Suvraneel commented on C_CPP/Algorithmic Approaches/Divide & Conquer/BinarySearchForRepeatedElements.md
> +```C++
```suggestion
  

```C++
```

2021-11-24 15:18 UTC, VaibhavMalik4187 commented
@Suvraneel I have removed all the <br> tags, can you please review my PR again?

2021-11-24 15:21 UTC, merged

2021-11-24 15:22 UTC, Suvraneel commented
@VaibhavMalik4187  LGTM 🚀 :octocat: