19.02 Overview of MVP architecture in Android(Audio file)
girlscript/winter-of-contributing pull request #8338
Opened 2021-11-23 21:19 UTC by Parth-001-git

<hr>

## Description 📜

In this repo we will get to know about  Overview of MVP architecture in Android
Fixes #7357

<hr>

## Type of change 📝

- [x] Audio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [x] Android Dev (Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-23 21:20 UTC, Parth-001-git commented
@rahulsain  because there was no new file related to the 19 number I knowingly have to create another one please review.

2021-11-24 14:24 UTC, rahulsain commented
The naming of the main folder should be referred from the roadmap.
1 PR should solve only 1 issue, so make the changes that solves the mentioned issue one at a time

2021-11-24 14:26 UTC, rahulsain requested changes

2021-11-24 14:26 UTC, rahulsain commented on Android_Development_with_Kotlin/05.1 Basic Implementation of Views in Android.md
> +[Basic Implementation of Views in Android]( https://drive.google.com/drive/u/0/folders/1Y2rTWJnhnOuRWRMPmEo5gVh4tjsBZDM2)
this doesnt fixed the mentioned issue, hence this file is not required in this PR

2021-11-24 14:26 UTC, rahulsain commented on Chronometer in Android.md
> +Generally, we can create use ChronoMeter widget in XML layout but we can do it programmatically also._
this doesnt fixed the mentioned issue, hence this file is not required in this PR

2021-11-24 14:26 UTC, rahulsain commented on Android_Development_with_Kotlin/19. Overview of MVP architecture in Android/19.02 Overview of MVP architecture in Android.md
> +[MVP architecture in Android ](https://drive.google.com/file/d/1yons4_a1zp-TUSe2AqQglbtjk-Ak5-XJ/view?usp=sharing)
change folder structure from `Android_Development_with_Kotlin/19. Overview of MVP architecture in Android/19.02 Overview of MVP architecture in Android.md` to `Android_Development_with_Kotlin/19. Architecture/19.02 Overview of MVP architecture in Android.md`

2021-11-24 15:29 UTC, closed without merging