Competitve Programming: Find nth Magic Number
girlscript/winter-of-contributing pull request #8350
Opened 2021-11-24 06:53 UTC by Jinal4502

<hr>

## Description 📜

I have provided explanation about the method to calculate the nth magic number alongwith its implementation in Python.
Fixes #8310 

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)
<hr>

## Domain of Contribution 📊

- [x] Competitive Programming

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-25 12:26 UTC, Jinal4502 commented
@ravireddy07, please review this pr.

2021-11-26 08:54 UTC, ravireddy07 requested changes
rename the folder and file name as NthMagicNumber only. As this is not a standard algorithm. There are many magic number problems...

2021-11-26 09:11 UTC, Jinal4502 commented
> rename the folder and file name as NthMagicNumber only. As this is not a standard algorithm. There are many magic number problems...

I renamed both folder and file as NthMagicNumber.

2021-11-26 13:43 UTC, ravireddy07 approved these changes

2021-11-27 00:56 UTC, merged