Machine learning
girlscript/winter-of-contributing pull request #8351
Opened 2021-11-24 07:09 UTC by shrestharushika

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #issue_number_here 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-24 12:03 UTC, abhisheks008 requested changes
1. Create `Images` folder to store the images that you've got during the visualization of your dataset.
2. Inside the `Model` folder, create the `README.md` file, which provides the idea/summary of the project.

🔴 How to create the `README.md` file and what it belongs ?
Check out here, [README file details](https://github.com/girlscript/winter-of-contributing/tree/Machine_Learning/Machine_Learning/Basic_Projects_of_Machine_Learning/Demo_Project/Model)

**Take the Reference from these two projects attached here,**

1. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Airbnb%20Price%20Prediction
2. https://github.com/prathimacode-hub/ML-ProjectKart/tree/main/Bike%20Crash%20Analysis

Changes requested @shrestharushika

2021-11-25 13:56 UTC, abhisheks008 requested changes

2021-11-25 13:56 UTC, abhisheks008 commented on Machine_Learning/Basic_Projects_of_Machine_Learning/Market Basket Analysis/Model/README.md
> +##Frequency of most popular items
This will be `## Frequency....`

2021-11-25 13:56 UTC, abhisheks008 commented on Machine_Learning/Basic_Projects_of_Machine_Learning/Market Basket Analysis/Model/README.md
> +#Most popular food products
This will be `## Most....`

2021-11-25 13:56 UTC, abhisheks008 commented on Machine_Learning/Basic_Projects_of_Machine_Learning/Market Basket Analysis/Model/README.md
> +##Frequency of most popular items
@shrestharushika

2021-11-25 13:57 UTC, abhisheks008 commented on Machine_Learning/Basic_Projects_of_Machine_Learning/Market Basket Analysis/Model/README.md
> +#Most popular food products
@shrestharushika

2021-11-25 14:08 UTC, shrestharushika commented
done sir

2021-11-25 14:44 UTC, abhisheks008 approved these changes

2021-11-25 14:44 UTC, merged