[CP]: Lowest Common Ancestor in Binary Tree
girlscript/winter-of-contributing pull request #8391
Opened 2021-11-24 16:58 UTC by areenoverclouds

<hr>

## Description 📜

This is the documentation about lowest common ancestor problem.
Fixes ##7966

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [x] Competitive Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-27 09:16 UTC, ravireddy07 requested changes

2021-11-27 09:16 UTC, ravireddy07 commented on Competitive_Programming/C++/Binary Trees/lca.md
> +**Method 1:**
name this approach here as well.

2021-11-27 09:16 UTC, ravireddy07 commented on Competitive_Programming/C++/Binary Trees/lca.md
> +    5. If current node is NULL then we have reached the end of tree.
Place this _below_ approach-1's code and _above_ approach-2's code.
Like:

Description
Code
Description
Code

2021-11-27 09:16 UTC, ravireddy07 commented on Competitive_Programming/C++/Binary Trees/lca.md
> +## Complexity Analysis
Add the Complexity details for both the approaches

2021-11-27 17:47 UTC, areenoverclouds commented
@ravireddy07 I have made the changes, please recheck.

2021-11-28 09:42 UTC, ravireddy07 approved these changes

2021-11-28 09:42 UTC, ravireddy07 commented
Please update the status in PR Tracksheet @areenoverclouds

2021-11-29 13:53 UTC, merged