Array
girlscript/winter-of-contributing pull request #8400
Opened 2021-11-24 18:07 UTC by amanraj-iit

<hr>

## Description 📜

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #issue_number_here 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [ ] Doc#umentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [ ] C/#CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [ ] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [ ] I have performed a self-review of my own code or work.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generates no new warnings.
- [ ] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-24 18:10 UTC, amanraj-iit commented
@Saviour1001

2021-11-25 04:07 UTC, amanraj-iit commented
@Saviour1001 sir please review

2021-11-25 05:39 UTC, vasu-1 commented
![image](https://user-images.githubusercontent.com/76911582/143385753-808e9b94-2985-43de-91a6-bcc7b155f132.png)
Mention your issue number
remove hash signs from c/cpp and documentation !

2021-11-25 05:42 UTC, vasu-1 requested changes
beautify your document with markdown formatting !
Plagiarisms detected !
![image](https://user-images.githubusercontent.com/76911582/143386077-bc18b0e7-d664-499c-a27b-d371c022bde6.png)

Make it unique (use your own words)

2021-11-25 05:42 UTC, vasu-1 commented on C_CPP/Competitive Programming/Array_and_Equilibrium_index.md
> +```
```suggestion
```cpp
```

2021-11-25 05:42 UTC, vasu-1 commented on C_CPP/Competitive Programming/Array_and_Equilibrium_index.md
> +(A[0] + A[1] + … + A[i-1]) = (A[i+1] + A[i+2] + … + A[n-1]), where 0 < i < n-1
```suggestion
`(A[0] + A[1] + … + A[i-1]) = (A[i+1] + A[i+2] + … + A[n-1]), where 0 < i < n-1`
```

2021-11-25 05:51 UTC, amanraj-iit commented
Done , please review

2021-11-25 06:27 UTC, vasu-1 commented
![image](https://user-images.githubusercontent.com/76911582/143390765-48bcb730-3074-440f-bd5a-d05e5360c433.png)
still lots of plagiarised content !
Please make it unique !

2021-11-25 06:28 UTC, vasu-1 commented
Add your file link into respective readme.md

2021-11-25 07:22 UTC, amanraj-iit commented
@vasu-1 please review

2021-11-25 07:24 UTC, vasu-1 requested changes

2021-11-25 07:24 UTC, vasu-1 commented on C_CPP/Competitive Programming/Array_and_Equilibrium_index.md
> + if (left[i] == right) {
fix this comment

2021-11-25 07:25 UTC, vasu-1 requested changes
Please add file link first !!!!!!!!!!!!!!!!!!!!!!!!!!

2021-11-25 07:49 UTC, vasu-1 requested changes

2021-11-25 07:49 UTC, vasu-1 commented on C_CPP/Competitive Programming/Array_and_Equilibrium_index.md
> +
fix this

2021-11-25 07:50 UTC, amanraj-iit commented
Done @vasu-1 please review

2021-11-25 07:50 UTC, vasu-1 commented
pahle for loop ke niche jo dikh raha h usko fix karo

2021-11-25 07:59 UTC, amanraj-iit commented
@vasu-1  Done

2021-11-25 14:36 UTC, vasu-1 requested changes

2021-11-25 14:36 UTC, vasu-1 commented on C_CPP/Competitive Programming/Array_and_Equilibrium_index.md
> +        */
```suggestion
```

Remove this

2021-11-25 14:36 UTC, vasu-1 commented on C_CPP/Competitive Programming/Array_and_Equilibrium_index.md
> +Element at index i isn't enclosed in either half as we all know that and it's expressed that if quite one equilibrium index is gift, we'd like to come back the primary one. Also, come back -1 if no e
Make it Appropriate !

Then you are good to go for merge !

2021-11-25 17:27 UTC, amanraj-iit commented
@vasu-1 please review

2021-11-26 09:00 UTC, vasu-1 requested changes
![image](https://user-images.githubusercontent.com/76911582/143554684-32014ec6-403e-4770-9a10-4793f50bef1b.png)
Make it complete
Lots of error in the code snippet and in document

2021-11-26 11:08 UTC, amanraj-iit commented
@vasu-1 sir

2021-11-26 13:59 UTC, vasu-1 requested changes

2021-11-26 13:59 UTC, vasu-1 commented on C_CPP/Competitive Programming/Array_and_Equilibrium_index.md
> +```
> 

do this change

2021-11-26 14:01 UTC, vasu-1 requested changes
.

2021-11-26 14:30 UTC, vasu-1 approved these changes
@Suvraneel @Saviour1001 check it

2021-11-26 15:19 UTC, merged

2021-11-26 15:19 UTC, Suvraneel commented
@amanraj-iit  LGTM 🚀  Good work :octocat: