[Competitive programming]: K- Concatenation Problem codechef
girlscript/winter-of-contributing pull request #8437
Opened 2021-11-25 13:17 UTC by vishvarana

<hr>

## Description 📜

Added solution to K-concatenation problem from codechef using C++ language

Fixes #5052

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [√] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [√] Competitive #Programming
<hr>

## Checklist ✅

- [√] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [√] I have performed a self-review of my own code or work.
- [√] I have commented my code, particularly in hard-to-understand areas.
- [√] My changes generates no new warnings.
- [√] I'm GWOC'21 contributor

<hr>

2021-11-26 07:50 UTC, ravireddy07 requested changes
before going to the code, Please explain the approach in words that you used to solve this problem.
And add Complexity details along with few testcase examples.

2021-11-29 08:08 UTC, ravireddy07 requested changes

2021-11-29 08:08 UTC, ravireddy07 commented on Competitive_Programming/C++/Array/K_concatenation_prob.md
> +**Complexities**
Use header(#) here instead of Bold

2021-11-29 08:08 UTC, ravireddy07 commented on Competitive_Programming/C++/Array/K_concatenation_prob.md
> +**Complexities**
```suggestion
## Complexity
```

2021-11-29 08:08 UTC, ravireddy07 commented on Competitive_Programming/C++/Array/K_concatenation_prob.md
> +**Explanation**
```suggestion
## Explanation
```

2021-11-29 08:08 UTC, ravireddy07 commented on Competitive_Programming/C++/Array/K_concatenation_prob.md
> +2
remove empty lines

2021-11-29 09:06 UTC, ravireddy07 requested changes

2021-11-29 09:06 UTC, ravireddy07 commented on Competitive_Programming/C++/Array/K_concatenation_prob.md
> +
remove empty lines(don't leave extra lines)

2021-11-30 09:26 UTC, vishvarana commented
Bold replaced with heading tags, removed unnecessary spaces except the ones in input and output test cases because they come in a single line if not left an extra line @ravireddy07

2021-11-30 09:48 UTC, ravireddy07 approved these changes

2021-11-30 17:08 UTC, merged