New Contribution
girlscript/winter-of-contributing pull request #8466
Opened 2021-11-25 17:05 UTC by Kanishk0412

<hr>

## Description 📜
I have added Programming Components, Structure and Keywords in C

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #911

<hr>

## Type of change 📝

- [x] Documentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x] C/CPP

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-25 17:05 UTC, Kanishk0412 commented
@Suvraneel Please review it.

2021-11-26 06:17 UTC, vasu-1 requested changes

2021-11-26 06:17 UTC, vasu-1 commented on C_CPP/Fundamentals/Programming components, Structure & Keyword/Programming Components Structure_Keywords_C.md
> +    ```
```suggestion
```c
    /* Program in C */
```
```

remove this space for syntax effect from all the code snippets

2021-11-26 06:17 UTC, vasu-1 commented on C_CPP/Fundamentals/Programming components, Structure & Keyword/Programming Components Structure_Keywords_C.md
> +    A variable, function, or any other user-defined item is identified by a C identifier. An identifier begins with a letter from A to Z, a to z, or an underscore '_', then zero or more letters, unde
don't use `<br>` tags !
Remove all the html tags

2021-11-26 06:17 UTC, vasu-1 commented on C_CPP/Fundamentals/Programming components, Structure & Keyword/Programming Components Structure_Keywords_C.md
> +    ```
Remove all front space

2021-11-26 06:17 UTC, vasu-1 commented on C_CPP/Fundamentals/Programming components, Structure & Keyword/Programming Components Structure_Keywords_C.md
> +    ```
Remove all front space

2021-11-26 06:17 UTC, vasu-1 commented on C_CPP/Fundamentals/Programming components, Structure & Keyword/Programming Components Structure_Keywords_C.md
> +    ```
Remove all front space from all the code snippets

2021-11-26 06:17 UTC, vasu-1 commented on C_CPP/Fundamentals/Programming components, Structure & Keyword/Programming Components Structure_Keywords_C.md
> +
REmove all unwanted empty lines

2021-11-26 12:07 UTC, Kanishk0412 commented
All Changes have been resolved @vasu-1. Please review it once

2021-11-26 14:11 UTC, vasu-1 requested changes
Remove all unwanted empty lines

2021-11-26 14:11 UTC, vasu-1 commented on C_CPP/Fundamentals/Programming components, Structure & Keyword/Programming Components Structure_Keywords_C.md
> +
remove this empty line

2021-11-26 14:11 UTC, vasu-1 commented on C_CPP/Fundamentals/Programming components, Structure & Keyword/Programming Components Structure_Keywords_C.md
> +
remove this empty line

2021-11-26 14:11 UTC, vasu-1 commented on C_CPP/Fundamentals/Programming components, Structure & Keyword/Programming Components Structure_Keywords_C.md
> +
remove this empty line

2021-11-26 14:21 UTC, Kanishk0412 commented
@vasu-1 Changes has been resolved.

2021-11-26 14:27 UTC, vasu-1 approved these changes
LGTM @Kanishk0412 

@Suvraneel @Saviour1001

2021-11-26 15:05 UTC, merged