Equilibrium Index of an Array
girlscript/winter-of-contributing pull request #8558
Opened 2021-11-26 15:35 UTC by yellowberard

<hr>

## Description 📜
Explanation about how to find equilibrium index of an array.
Fixes #8395 

<hr>

## Type of change 📝

- [x] Doc#umentation (Content Creation in the form of codes or tutorials)

<hr>

## Domain of Contribution 📊

- [x]  C/#CPP
<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

<hr>

2021-11-26 15:36 UTC, yellowberard commented
@vasu-1 Please review my PR.

2021-11-26 19:47 UTC, Suvraneel requested changes
Do a spell-check before a mentor reviews this... Mistake in file name too

2021-11-26 19:47 UTC, Suvraneel commented on C_CPP/Data Structures/Array/Equlibrium_index.md
> +I hve given a example to under stand it better.
```suggestion
I have given a example to under stand it better.
```

2021-11-26 19:47 UTC, Suvraneel commented on C_CPP/Data Structures/Array/Equlibrium_index.md
> +Equlibrium index means that index i such that the sum all the lower indexes is same to the sum of the higher indexes.
```suggestion
Equilibrium index means that index i such that the sum all the lower indexes is same to the sum of the higher indexes.
```

2021-11-26 21:33 UTC, yellowberard commented
@Suvraneel I have made the changes. Sorry for spelling mistakes.

2021-11-27 12:41 UTC, Suvraneel requested changes
@yellowberard  No need to be Sorry... 😅 
These are not wrong...
But the objective is to make you understand opensource formatting standards...

Here, you've used 2 newline characters for each new paragraph...
But line cunts in commit matters...
So, instead of pressing Enter key twice, you need to add 2 spaces at End of line & press Enter

2021-11-27 12:41 UTC, Suvraneel commented on C_CPP/Data Structures/Array/Equilibrium_index.md
> +**Output**: 3
```suggestion
# Equilibrium Index of a Array
```suggestion
# Equilibrium Index of a Array

Here we will see how to find a equilibrium index in a array.

Equilibrium index means that index i such that the sum of all the lower indexes is same to the sum of the higher indexes.

I have given a example to understand it better.

## Example

**Input**: Arr[] = {-7, 1, 5, 2, -4, 3, 0}  
**Output**: 3
```
Here we will see how to find a equilibrium index in a array.  
Equilibrium index means that index i such that the sum of all the lower indexes is same to the sum of the higher indexes.  
I have given a example to understand it better.

## Example  
**Input**: Arr[] = {-7, 1, 5, 2, -4, 3, 0}  
**Output**: 3  
```

2021-11-27 12:41 UTC, Suvraneel commented on C_CPP/Data Structures/Array/Equilibrium_index.md
> +O(1)
```suggestion
### Time Complexity  
O(n)  
### Space Complexity  
O(1)
```

2021-11-27 12:43 UTC, Suvraneel requested changes

2021-11-27 12:43 UTC, Suvraneel commented on C_CPP/Data Structures/Array/readme.md
> +- [Equilibrium Index of a Array](Equlibrium_index.md)
```suggestion
- [Equilibrium Index of a Array](Equilibrium_index.md)
```
Fix Link

2021-11-27 18:16 UTC, yellowberard commented
@Suvraneel I have made the changes.

2021-11-28 07:18 UTC, merged

2021-11-28 07:19 UTC, Suvraneel commented
@yellowberard  Noice work 🚀  LGTM ❤️

2021-11-28 07:39 UTC, yellowberard commented
> @yellowberard Noice work 🚀 LGTM ❤️

Thank you