Create Binary_Tree_sum_of_nodes_at_kth_level.md
girlscript/winter-of-contributing pull request #8713
Opened 2021-11-28 13:27 UTC by saloni33

<hr>

## Description 📜

Documentation for sum of all nodes present at kth level in binary tree
Fixes  #8705 

<hr>

## Type of change 📝

- [ ] Au#dio (Should be in mp3 format Includes speech clarity, Concise ,Low distortion)
- [ ] Vi#deo (Animations, screen-recordings, presentations and regular explanatory films are all possibilties etc)
- [x] Documentation (Content Creation in the form of codes or tutorials)
- [ ] Other (If you choose other, Please mention changes below) 

<hr>

## Domain of Contribution 📊

- [ ] Android Dev #(Flutter)
- [ ] Android Dev #(Java)
- [ ] Android Dev #(Kotlin)
- [ ] Backend Dev #(Java)
- [ ] Backend Dev #(.NET)
- [ ] Backend Dev #(PHP)
- [ ] Backend Dev #(Python)
- [x] C/CPP
- [ ] Competitive #Programming
- [ ] Cyber #Security
- [ ] DS#A
- [ ] Data#base
- [ ] Datascience with #Python
- [ ] Datascience with #R
- [ ] Frontend Dev #HTML/CSS/JS
- [ ] Frontend Dev #React/Angular/Vue
- [ ] Go#lang
- [ ] Interview #Prep
- [ ] Java_#Domain
- [ ] JavaScript_#Domain
- [ ] ME#RN
- [ ] Machine #Learning
- [ ] Open #Source
- [ ] Python_#Domain
- [ ] Ru#st
- [ ] Statis#tics
- [ ] UI/#UX

<hr>

## Checklist ✅

- [x] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [x] I have performed a self-review of my own code or work.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generates no new warnings.
- [x] I'm GWOC'21 contributor

<hr>

## Screenshots / Gif (Optional) 📸

<hr>

2021-11-28 13:29 UTC, saloni33 commented
@vasu-1 and @Suvraneel  please review

2021-11-28 19:01 UTC, apeksha235 requested changes
@saloni33 
- Add a link of your file to the readme file of the folder 
- Please mention the approach/algorithm of your code
- Avoid using html tags as done in lines 5-9

2021-11-28 19:25 UTC, saloni33 commented
@apeksha235  can you tell me what to use instead of &nbsp; . I am unable to find another method.

2021-11-28 19:34 UTC, saloni33 commented
@apeksha235  made the changes can you review again

2021-11-28 21:25 UTC, Suvraneel requested changes
@saloni33  Good content

2021-11-28 21:25 UTC, Suvraneel commented on C_CPP/Data Structures/Binary Tree/Binary_Tree_sum_of_nodes_at_kth_level.md
> +Consider a binary tree as -  <br/>
```suggestion
Consider a binary tree as -   
```

Avoid using HTML tags in md unless inevitable cz they tend to break
Convention for line break is 2 spaces at end of the line

2021-11-28 21:25 UTC, Suvraneel commented on C_CPP/Data Structures/Binary Tree/Binary_Tree_sum_of_nodes_at_kth_level.md
> +## Approach <br/>
Ditto
Also, br not required in headings
```suggestion
## Approach  
```

2021-11-28 21:25 UTC, Suvraneel commented on C_CPP/Data Structures/Binary Tree/Binary_Tree_sum_of_nodes_at_kth_level.md
> +## Code:  <br/>
"

2021-11-28 21:25 UTC, Suvraneel commented on C_CPP/Data Structures/Binary Tree/Binary_Tree_sum_of_nodes_at_kth_level.md
> +```
```suggestion
```cpp
```
Use code highlighting

2021-11-28 21:25 UTC, Suvraneel commented on C_CPP/Data Structures/Binary Tree/Binary_Tree_sum_of_nodes_at_kth_level.md
> +O(n) where n is the number of nodes in the binary tree
All br s to be removed

2021-11-28 23:20 UTC, saloni33 commented
@Suvraneel sir done all the required changes

2021-11-29 12:05 UTC, Suvraneel commented
@saloni33  GG 💯  Noice work 🚀 ❤️ :octocat:  LGTM

2021-11-29 12:05 UTC, merged