Create Find_Day_of_a_given_Date.md
girlscript/winter-of-contributing pull request #8728
Opened 2021-11-28 15:58 UTC by varnikarathee

<hr>

## Description 📜Find_Day_of_a_given_Date.md

Fixes #8438 

<hr>

## Type of change 📝Find_Day_of_a_given_Date.md

- [X] Documentation (Content Creation in the form of codes or tutorials)
 
<hr>

## Domain of Contribution 📊

- [X] C/CPP

<hr>

## Checklist ✅

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.
- [X] I have performed a self-review of my own code or work.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] My changes generates no new warnings.
- [X] I'm GWOC'21 contributor

<hr>

2021-11-28 16:02 UTC, varnikarathee commented
@vasu-1 Made a new branch varnikarathee-patch1 and made changes. Please merge now.

2021-11-28 18:46 UTC, apeksha235 requested changes
@varnikarathee

2021-11-28 18:46 UTC, apeksha235 commented on C_CPP/Competitive Programming/Find_Day_of_a_given_Date.md
> +Now we implement the above approach in cpp using OOPS concept:
add comments to your code

2021-11-29 02:30 UTC, varnikarathee commented
@apeksha235 Made the changes as requested. Can u please merge now?

2021-11-29 12:18 UTC, varnikarathee commented
@vasu-1can u please merge this . I made all changes

2021-11-29 12:27 UTC, Suvraneel commented
@apeksha235  Can you give this a final LGTM (or request changes) before I merge this ?

2021-11-29 12:30 UTC, apeksha235 approved these changes
@Suvraneel yes please merge this

2021-11-29 12:33 UTC, merged